-- ======================================================================
-- Module: hexm.client.ui.consts.cc_consts
-- Source: package.loaded
-- Type: table
-- Order: #2316
-- ======================================================================

-- Module type: table

ANIMATIONTYPE_PT_ANIMATION_COMPLETE: 3

ANIMATIONTYPE_PT_ANIMATION_DISPOSE: 4

ANIMATIONTYPE_PT_ANIMATION_END: 2

ANIMATIONTYPE_PT_ANIMATION_EVENT: 5

ANIMATIONTYPE_PT_ANIMATION_INTERRUPT: 1

ANIMATIONTYPE_PT_ANIMATION_START: 0

CAMERAFLAG_DEFAULT: 1

CAMERAFLAG_USER1: 2

CAMERAFLAG_USER2: 4

CAMERAFLAG_USER3: 8

CAMERAFLAG_USER4: 16

CAMERAFLAG_USER5: 32

CAMERAFLAG_USER6: 64

CAMERAFLAG_USER7: 128

CAMERAFLAG_USER8: 256

CCSCRIPTTYPE_KSCRIPTTYPEJAVASCRIPT: 2

CCSCRIPTTYPE_KSCRIPTTYPELUA: 1

CCSCRIPTTYPE_KSCRIPTTYPENONE: 0

CCSCRIPTTYPE_KSCRIPTTYPEPYTHON: 3

CCZ_COMPRESSION_BZIP2: 1

CCZ_COMPRESSION_GZIP: 2

CCZ_COMPRESSION_NONE: 3

CCZ_COMPRESSION_ZLIB: 0

CONFIGTYPE_COCOSTUDIO: 1

CONFIGTYPE_NONE: 0

DICTTYPE_KDICTINT: 2

DICTTYPE_KDICTSTR: 1

DICTTYPE_KDICTUNKNOWN: 0

DIRECTOR_PROJECTION_CUSTOM: 2

DIRECTOR_PROJECTION_DEFAULT: 1

DIRECTOR_PROJECTION__2D: 0

DIRECTOR_PROJECTION__3D: 1

EVENTDISPATCHER_DIRTYFLAG_ALL: 3

EVENTDISPATCHER_DIRTYFLAG_FIXED_PRIORITY: 1

EVENTDISPATCHER_DIRTYFLAG_NONE: 0

EVENTDISPATCHER_DIRTYFLAG_SCENE_GRAPH_PRIORITY: 2

EVENTKEYBOARD_KEYCODE_KEY_0: 76

EVENTKEYBOARD_KEYCODE_KEY_1: 77

EVENTKEYBOARD_KEYCODE_KEY_2: 78

EVENTKEYBOARD_KEYCODE_KEY_3: 79

EVENTKEYBOARD_KEYCODE_KEY_4: 80

EVENTKEYBOARD_KEYCODE_KEY_5: 81

EVENTKEYBOARD_KEYCODE_KEY_6: 82

EVENTKEYBOARD_KEYCODE_KEY_7: 83

EVENTKEYBOARD_KEYCODE_KEY_8: 84

EVENTKEYBOARD_KEYCODE_KEY_9: 85

EVENTKEYBOARD_KEYCODE_KEY_A: 124

EVENTKEYBOARD_KEYCODE_KEY_ALT: 16

EVENTKEYBOARD_KEYCODE_KEY_AMPERSAND: 66

EVENTKEYBOARD_KEYCODE_KEY_APOSTROPHE: 67

EVENTKEYBOARD_KEYCODE_KEY_ASTERISK: 70

EVENTKEYBOARD_KEYCODE_KEY_AT: 92

EVENTKEYBOARD_KEYCODE_KEY_B: 125

EVENTKEYBOARD_KEYCODE_KEY_BACK: 6

EVENTKEYBOARD_KEYCODE_KEY_BACKSPACE: 7

EVENTKEYBOARD_KEYCODE_KEY_BACK_SLASH: 120

EVENTKEYBOARD_KEYCODE_KEY_BACK_TAB: 9

EVENTKEYBOARD_KEYCODE_KEY_BAR: 151

EVENTKEYBOARD_KEYCODE_KEY_BREAK: 5

EVENTKEYBOARD_KEYCODE_KEY_C: 126

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_A: 93

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_B: 94

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_C: 95

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_D: 96

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_E: 97

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_F: 98

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_G: 99

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_H: 100

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_I: 101

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_J: 102

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_K: 103

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_L: 104

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_M: 105

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_N: 106

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_O: 107

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_P: 108

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_Q: 109

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_R: 110

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_S: 111

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_T: 112

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_U: 113

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_V: 114

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_W: 115

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_X: 116

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_Y: 117

EVENTKEYBOARD_KEYCODE_KEY_CAPITAL_Z: 118

EVENTKEYBOARD_KEYCODE_KEY_CAPS_LOCK: 11

EVENTKEYBOARD_KEYCODE_KEY_CIRCUMFLEX: 65

EVENTKEYBOARD_KEYCODE_KEY_COLON: 86

EVENTKEYBOARD_KEYCODE_KEY_COMMA: 72

EVENTKEYBOARD_KEYCODE_KEY_CTRL: 14

EVENTKEYBOARD_KEYCODE_KEY_D: 127

EVENTKEYBOARD_KEYCODE_KEY_DELETE: 23

EVENTKEYBOARD_KEYCODE_KEY_DOLLAR: 63

EVENTKEYBOARD_KEYCODE_KEY_DOWN_ARROW: 29

EVENTKEYBOARD_KEYCODE_KEY_DPAD_CENTER: 163

EVENTKEYBOARD_KEYCODE_KEY_DPAD_DOWN: 162

EVENTKEYBOARD_KEYCODE_KEY_DPAD_LEFT: 159

EVENTKEYBOARD_KEYCODE_KEY_DPAD_RIGHT: 160

EVENTKEYBOARD_KEYCODE_KEY_DPAD_UP: 161

EVENTKEYBOARD_KEYCODE_KEY_E: 128

EVENTKEYBOARD_KEYCODE_KEY_END: 24

EVENTKEYBOARD_KEYCODE_KEY_ENTER: 164

EVENTKEYBOARD_KEYCODE_KEY_EQUAL: 89

EVENTKEYBOARD_KEYCODE_KEY_ESCAPE: 6

EVENTKEYBOARD_KEYCODE_KEY_EURO: 154

EVENTKEYBOARD_KEYCODE_KEY_EXCLAM: 60

EVENTKEYBOARD_KEYCODE_KEY_F: 129

EVENTKEYBOARD_KEYCODE_KEY_F1: 47

EVENTKEYBOARD_KEYCODE_KEY_F10: 56

EVENTKEYBOARD_KEYCODE_KEY_F11: 57

EVENTKEYBOARD_KEYCODE_KEY_F12: 58

EVENTKEYBOARD_KEYCODE_KEY_F2: 48

EVENTKEYBOARD_KEYCODE_KEY_F3: 49

EVENTKEYBOARD_KEYCODE_KEY_F4: 50

EVENTKEYBOARD_KEYCODE_KEY_F5: 51

EVENTKEYBOARD_KEYCODE_KEY_F6: 52

EVENTKEYBOARD_KEYCODE_KEY_F7: 53

EVENTKEYBOARD_KEYCODE_KEY_F8: 54

EVENTKEYBOARD_KEYCODE_KEY_F9: 55

EVENTKEYBOARD_KEYCODE_KEY_G: 130

EVENTKEYBOARD_KEYCODE_KEY_GRAVE: 123

EVENTKEYBOARD_KEYCODE_KEY_GREATER_THAN: 90

EVENTKEYBOARD_KEYCODE_KEY_H: 131

EVENTKEYBOARD_KEYCODE_KEY_HOME: 21

EVENTKEYBOARD_KEYCODE_KEY_HYPER: 19

EVENTKEYBOARD_KEYCODE_KEY_I: 132

EVENTKEYBOARD_KEYCODE_KEY_INSERT: 20

EVENTKEYBOARD_KEYCODE_KEY_J: 133

EVENTKEYBOARD_KEYCODE_KEY_K: 134

EVENTKEYBOARD_KEYCODE_KEY_KP_DELETE: 46

EVENTKEYBOARD_KEYCODE_KEY_KP_DIVIDE: 34

EVENTKEYBOARD_KEYCODE_KEY_KP_DOWN: 43

EVENTKEYBOARD_KEYCODE_KEY_KP_END: 42

EVENTKEYBOARD_KEYCODE_KEY_KP_ENTER: 35

EVENTKEYBOARD_KEYCODE_KEY_KP_FIVE: 40

EVENTKEYBOARD_KEYCODE_KEY_KP_HOME: 36

EVENTKEYBOARD_KEYCODE_KEY_KP_INSERT: 45

EVENTKEYBOARD_KEYCODE_KEY_KP_LEFT: 39

EVENTKEYBOARD_KEYCODE_KEY_KP_MINUS: 32

EVENTKEYBOARD_KEYCODE_KEY_KP_MULTIPLY: 33

EVENTKEYBOARD_KEYCODE_KEY_KP_PG_DOWN: 44

EVENTKEYBOARD_KEYCODE_KEY_KP_PG_UP: 38

EVENTKEYBOARD_KEYCODE_KEY_KP_PLUS: 31

EVENTKEYBOARD_KEYCODE_KEY_KP_RIGHT: 41

EVENTKEYBOARD_KEYCODE_KEY_KP_UP: 37

EVENTKEYBOARD_KEYCODE_KEY_L: 135

EVENTKEYBOARD_KEYCODE_KEY_LEFT_ALT: 16

EVENTKEYBOARD_KEYCODE_KEY_LEFT_ARROW: 26

EVENTKEYBOARD_KEYCODE_KEY_LEFT_BRACE: 150

EVENTKEYBOARD_KEYCODE_KEY_LEFT_BRACKET: 119

EVENTKEYBOARD_KEYCODE_KEY_LEFT_CTRL: 14

EVENTKEYBOARD_KEYCODE_KEY_LEFT_PARENTHESIS: 68

EVENTKEYBOARD_KEYCODE_KEY_LEFT_SHIFT: 12

EVENTKEYBOARD_KEYCODE_KEY_LESS_THAN: 88

EVENTKEYBOARD_KEYCODE_KEY_M: 136

EVENTKEYBOARD_KEYCODE_KEY_MENU: 18

EVENTKEYBOARD_KEYCODE_KEY_MIDDLE_DOT: 157

EVENTKEYBOARD_KEYCODE_KEY_MINUS: 73

EVENTKEYBOARD_KEYCODE_KEY_N: 137

EVENTKEYBOARD_KEYCODE_KEY_NONE: 0

EVENTKEYBOARD_KEYCODE_KEY_NUMBER: 62

EVENTKEYBOARD_KEYCODE_KEY_NUM_LOCK: 30

EVENTKEYBOARD_KEYCODE_KEY_O: 138

EVENTKEYBOARD_KEYCODE_KEY_P: 139

EVENTKEYBOARD_KEYCODE_KEY_PAUSE: 1

EVENTKEYBOARD_KEYCODE_KEY_PERCENT: 64

EVENTKEYBOARD_KEYCODE_KEY_PERIOD: 74

EVENTKEYBOARD_KEYCODE_KEY_PG_DOWN: 25

EVENTKEYBOARD_KEYCODE_KEY_PG_UP: 22

EVENTKEYBOARD_KEYCODE_KEY_PLAY: 165

EVENTKEYBOARD_KEYCODE_KEY_PLUS: 71

EVENTKEYBOARD_KEYCODE_KEY_POUND: 155

EVENTKEYBOARD_KEYCODE_KEY_PRINT: 3

EVENTKEYBOARD_KEYCODE_KEY_Q: 140

EVENTKEYBOARD_KEYCODE_KEY_QUESTION: 91

EVENTKEYBOARD_KEYCODE_KEY_QUOTE: 61

EVENTKEYBOARD_KEYCODE_KEY_R: 141

EVENTKEYBOARD_KEYCODE_KEY_RETURN: 10

EVENTKEYBOARD_KEYCODE_KEY_RIGHT_ALT: 17

EVENTKEYBOARD_KEYCODE_KEY_RIGHT_ARROW: 27

EVENTKEYBOARD_KEYCODE_KEY_RIGHT_BRACE: 152

EVENTKEYBOARD_KEYCODE_KEY_RIGHT_BRACKET: 121

EVENTKEYBOARD_KEYCODE_KEY_RIGHT_CTRL: 15

EVENTKEYBOARD_KEYCODE_KEY_RIGHT_PARENTHESIS: 69

EVENTKEYBOARD_KEYCODE_KEY_RIGHT_SHIFT: 13

EVENTKEYBOARD_KEYCODE_KEY_S: 142

EVENTKEYBOARD_KEYCODE_KEY_SCROLL_LOCK: 2

EVENTKEYBOARD_KEYCODE_KEY_SEARCH: 158

EVENTKEYBOARD_KEYCODE_KEY_SEMICOLON: 87

EVENTKEYBOARD_KEYCODE_KEY_SHIFT: 12

EVENTKEYBOARD_KEYCODE_KEY_SLASH: 75

EVENTKEYBOARD_KEYCODE_KEY_SPACE: 59

EVENTKEYBOARD_KEYCODE_KEY_SYSREQ: 4

EVENTKEYBOARD_KEYCODE_KEY_T: 143

EVENTKEYBOARD_KEYCODE_KEY_TAB: 8

EVENTKEYBOARD_KEYCODE_KEY_TILDE: 153

EVENTKEYBOARD_KEYCODE_KEY_U: 144

EVENTKEYBOARD_KEYCODE_KEY_UNDERSCORE: 122

EVENTKEYBOARD_KEYCODE_KEY_UP_ARROW: 28

EVENTKEYBOARD_KEYCODE_KEY_V: 145

EVENTKEYBOARD_KEYCODE_KEY_W: 146

EVENTKEYBOARD_KEYCODE_KEY_X: 147

EVENTKEYBOARD_KEYCODE_KEY_Y: 148

EVENTKEYBOARD_KEYCODE_KEY_YEN: 156

EVENTKEYBOARD_KEYCODE_KEY_Z: 149

EVENTLISTENER_TYPE_ACCELERATION: 5

EVENTLISTENER_TYPE_CUSTOM: 8

EVENTLISTENER_TYPE_FOCUS: 6

EVENTLISTENER_TYPE_GAME_CONTROLLER: 7

EVENTLISTENER_TYPE_KEYBOARD: 3

EVENTLISTENER_TYPE_MOUSE: 4

EVENTLISTENER_TYPE_TOUCH_ALL_AT_ONCE: 2

EVENTLISTENER_TYPE_TOUCH_ONE_BY_ONE: 1

EVENTLISTENER_TYPE_UNKNOWN: 0

EVENTTOUCH_EVENTCODE_BEGAN: 0

EVENTTOUCH_EVENTCODE_CANCELLED: 3

EVENTTOUCH_EVENTCODE_ENDED: 2

EVENTTOUCH_EVENTCODE_MMOVED: 4

EVENTTOUCH_EVENTCODE_MOVED: 1

EVENT_TYPE_ACCELERATION: 2

EVENT_TYPE_CUSTOM: 6

EVENT_TYPE_FOCUS: 4

EVENT_TYPE_GAME_CONTROLLER: 5

EVENT_TYPE_KEYBOARD: 1

EVENT_TYPE_MOUSE: 3

EVENT_TYPE_TOUCH: 0

IMAGE_FORMAT_ATITC: 7

IMAGE_FORMAT_ETC: 5

IMAGE_FORMAT_JPG: 0

IMAGE_FORMAT_PNG: 1

IMAGE_FORMAT_PVR: 4

IMAGE_FORMAT_RAW_DATA: 9

IMAGE_FORMAT_S3TC: 6

IMAGE_FORMAT_TGA: 8

IMAGE_FORMAT_TIFF: 2

IMAGE_FORMAT_UNKOWN: 10

IMAGE_FORMAT_WEBP: 3

INDEXTYPE_INDEX_TYPE_SHORT_16: 0

INDEXTYPE_INDEX_TYPE_UINT_32: 1

KCOMPONENTONENTER: 0

KCOMPONENTONEXIT: 1

KCOMPONENTONUPDATE: 2

LABELEFFECT_BOLD: 4

LABELEFFECT_EMPHASIZE: 64

LABELEFFECT_GLOW: 3

LABELEFFECT_NORMAL: 0

LABELEFFECT_OUTLINE: 1

LABELEFFECT_SHADOW: 2

LABELEFFECT_STRIKETHROUGH: 32

LABELEFFECT_UNDERLINE: 16

LABEL_LABELTYPE_BMFONT: 1

LABEL_LABELTYPE_CHARMAP: 2

LABEL_LABELTYPE_STRING_TEXTURE: 3

LABEL_LABELTYPE_TTF: 0

LANGUAGETYPE_ARABIC: 12

LANGUAGETYPE_CHINESE: 1

LANGUAGETYPE_DUTCH: 6

LANGUAGETYPE_ENGLISH: 0

LANGUAGETYPE_FRENCH: 2

LANGUAGETYPE_GERMAN: 4

LANGUAGETYPE_HUNGARIAN: 10

LANGUAGETYPE_ITALIAN: 3

LANGUAGETYPE_JAPANESE: 9

LANGUAGETYPE_KOREAN: 8

LANGUAGETYPE_NORWEGIAN: 13

LANGUAGETYPE_POLISH: 14

LANGUAGETYPE_PORTUGUESE: 11

LANGUAGETYPE_RUSSIAN: 7

LANGUAGETYPE_SPANISH: 5

MATRIX_STACK_TYPE_MATRIX_STACK_MODELVIEW: 0

MATRIX_STACK_TYPE_MATRIX_STACK_PROJECTION: 1

MATRIX_STACK_TYPE_MATRIX_STACK_TEXTURE: 2

MENU_STATE_TRACKING_TOUCH: 1

MENU_STATE_WAITING: 0

NODE_FLAGS_CONTENT_SIZE_DIRTY: 2

NODE_FLAGS_DIRTY_MASK: 3

NODE_FLAGS_IS_HITTED: 4

NODE_FLAGS_TRANSFORM_DIRTY: 1

NODE_NODECALLBACKTYPE_ENTER: 0

NODE_NODECALLBACKTYPE_ENTERTRANSITIONDIDFINISH: 3

NODE_NODECALLBACKTYPE_EXIT: 1

NODE_NODECALLBACKTYPE_EXITTRANSITIONDIDSTART: 2

NODE_NODECALLBACKTYPE_RELEASE: 4

PAGETURN3D_STATE_STATE_ROLLING_END: 3

PAGETURN3D_STATE_STATE_TOUCH_BEGIN: 1

PAGETURN3D_STATE_STATE_TOUCH_END: 2

PAGETURN3D_STATE_STATE_TOUCH_NONE: 0

PAGETURN3D_STICK_EDGE_STICK_EDGE_BEGIN: 0

PAGETURN3D_STICK_EDGE_STICK_EDGE_BOTTOM: 1

PAGETURN3D_STICK_EDGE_STICK_EDGE_COUNT: 4

PAGETURN3D_STICK_EDGE_STICK_EDGE_HORIZONTAL: 2

PAGETURN3D_STICK_EDGE_STICK_EDGE_LEFT: 2

PAGETURN3D_STICK_EDGE_STICK_EDGE_RIGHT: 3

PAGETURN3D_STICK_EDGE_STICK_EDGE_TOP: 0

PARTICLESYSTEM_DURATION_INFINITY: -1

PARTICLESYSTEM_MODE_GRAVITY: 0

PARTICLESYSTEM_MODE_RADIUS: 1

PARTICLESYSTEM_POSITIONTYPE_FREE: 0

PARTICLESYSTEM_POSITIONTYPE_GROUPED: 2

PARTICLESYSTEM_POSITIONTYPE_RELATIVE: 1

PARTICLESYSTEM_START_RADIUS_EQUAL_TO_END_RADIUS: -1

PARTICLESYSTEM_START_SIZE_EQUAL_TO_END_SIZE: -1

PIXELFORMAT_A8: 5

PIXELFORMAT_AI88: 7

PIXELFORMAT_ATC_EXPLICIT_ALPHA: 19

PIXELFORMAT_ATC_INTERPOLATED_ALPHA: 20

PIXELFORMAT_ATC_RGB: 18

PIXELFORMAT_AUTO: 0

PIXELFORMAT_BGRA8888: 1

PIXELFORMAT_DEFAULT: 0

PIXELFORMAT_ETC: 14

PIXELFORMAT_I8: 6

PIXELFORMAT_NONE: -1

PIXELFORMAT_PVRTC2: 12

PIXELFORMAT_PVRTC2A: 13

PIXELFORMAT_PVRTC4: 10

PIXELFORMAT_PVRTC4A: 11

PIXELFORMAT_RGB565: 4

PIXELFORMAT_RGB5A1: 9

PIXELFORMAT_RGB888: 3

PIXELFORMAT_RGBA4444: 8

PIXELFORMAT_RGBA8888: 2

PIXELFORMAT_S3TC_DXT1: 15

PIXELFORMAT_S3TC_DXT3: 16

PIXELFORMAT_S3TC_DXT5: 17

PLATFORM_OS_ANDROID: 3

PLATFORM_OS_BLACKBERRY: 6

PLATFORM_OS_EMSCRIPTEN: 8

PLATFORM_OS_IPAD: 5

PLATFORM_OS_IPHONE: 4

PLATFORM_OS_LINUX: 1

PLATFORM_OS_MAC: 2

PLATFORM_OS_NACL: 7

PLATFORM_OS_TIZEN: 9

PLATFORM_OS_WINDOWS: 0

PLATFORM_OS_WINRT: 10

PLATFORM_OS_WP8: 11

QUADTYPE_IQUADTYPE_BASE: 1

QUADTYPE_IQUADTYPE_BEGIN3DGRID: 2048

QUADTYPE_IQUADTYPE_CAMERA: 8192

QUADTYPE_IQUADTYPE_CANMERGE: 17

QUADTYPE_IQUADTYPE_CIRCULAR: 4

QUADTYPE_IQUADTYPE_CLIP: 256

QUADTYPE_IQUADTYPE_CLIPEXTERNAL: 32768

QUADTYPE_IQUADTYPE_CUSTOM: 1024

QUADTYPE_IQUADTYPE_DEPTH: 16384

QUADTYPE_IQUADTYPE_END3DGRID: 4096

QUADTYPE_IQUADTYPE_EXTERNAL: 32

QUADTYPE_IQUADTYPE_GEOMETRY: 128

QUADTYPE_IQUADTYPE_LIVE: 512

QUADTYPE_IQUADTYPE_NONE: 0

QUADTYPE_IQUADTYPE_PARTICLE: 16

QUADTYPE_IQUADTYPE_ROOM: 8

QUADTYPE_IQUADTYPE_TEXT: 2

QUADTYPE_IQUADTYPE_TRAJECTORY: 64

RESOLUTIONPOLICY_EXACT_FIT: 0

RESOLUTIONPOLICY_FIXED_HEIGHT: 3

RESOLUTIONPOLICY_FIXED_WIDTH: 4

RESOLUTIONPOLICY_NO_BORDER: 1

RESOLUTIONPOLICY_SHOW_ALL: 2

RESOLUTIONPOLICY_UNKNOWN: 5

SCRIPTEVENTTYPE_KACCELEROMETEREVENT: 7

SCRIPTEVENTTYPE_KCALLFUNCEVENT: 2

SCRIPTEVENTTYPE_KCOMMONEVENT: 9

SCRIPTEVENTTYPE_KCOMPONENTEVENT: 10

SCRIPTEVENTTYPE_KCONTROLEVENT: 8

SCRIPTEVENTTYPE_KKEYPADEVENT: 6

SCRIPTEVENTTYPE_KMENUCLICKEDEVENT: 1

SCRIPTEVENTTYPE_KNODEEVENT: 0

SCRIPTEVENTTYPE_KSCHEDULEEVENT: 3

SCRIPTEVENTTYPE_KTOUCHESEVENT: 5

SCRIPTEVENTTYPE_KTOUCHEVENT: 4

SPRITE_QUADTYPE_QUADTYPE_BASE: 1

SPRITE_QUADTYPE_QUADTYPE_BASEEX: 256

SPRITE_QUADTYPE_QUADTYPE_CAMERA: 8192

SPRITE_QUADTYPE_QUADTYPE_CIRCULAR: 8

SPRITE_QUADTYPE_QUADTYPE_EXTERNAL: 32

SPRITE_QUADTYPE_QUADTYPE_EXTERNAL_EDIT: 16384

SPRITE_QUADTYPE_QUADTYPE_LIVE: 128

SPRITE_QUADTYPE_QUADTYPE_NONE: 0

SPRITE_QUADTYPE_QUADTYPE_ROOM: 16

SPRITE_QUADTYPE_QUADTYPE_SKIN: 2

SPRITE_QUADTYPE_QUADTYPE_TEXT: 4

SPRITE_QUADTYPE_QUADTYPE_TRAJECTORY: 64

TEXTALIGNMENT_BOTTOM: 16

TEXTALIGNMENT_HCENTER: 2

TEXTALIGNMENT_LEFT: 1

TEXTALIGNMENT_RIGHT: 4

TEXTALIGNMENT_TOP: 0

TEXTALIGNMENT_VCENTER: 8

TEXTALIGN_BOTTOM: 35

TEXTALIGN_BOTTOM_LEFT: 33

TEXTALIGN_BOTTOM_RIGHT: 34

TEXTALIGN_CENTER: 51

TEXTALIGN_LEFT: 49

TEXTALIGN_RIGHT: 50

TEXTALIGN_TOP: 19

TEXTALIGN_TOP_LEFT: 17

TEXTALIGN_TOP_RIGHT: 18

TEXTHALIGNMENT_HCENTER: 2

TEXTHALIGNMENT_LEFT: 1

TEXTHALIGNMENT_RIGHT: 4

TEXTVALIGNMENT_BOTTOM: 16

TEXTVALIGNMENT_TOP: 0

TEXTVALIGNMENT_VCENTER: 8

TOUCH_DISPATCHMODE_ALL_AT_ONCE: 0

TOUCH_DISPATCHMODE_ONE_BY_ONE: 1

TRANSITIONSCENE_ORIENTATION_DOWN_OVER: 1

TRANSITIONSCENE_ORIENTATION_LEFT_OVER: 0

TRANSITIONSCENE_ORIENTATION_RIGHT_OVER: 1

TRANSITIONSCENE_ORIENTATION_UP_OVER: 0

TWEENTYPE_BACK_EASEIN: 25

TWEENTYPE_BACK_EASEINOUT: 27

TWEENTYPE_BACK_EASEOUT: 26

TWEENTYPE_BOUNCE_EASEIN: 28

TWEENTYPE_BOUNCE_EASEINOUT: 30

TWEENTYPE_BOUNCE_EASEOUT: 29

TWEENTYPE_CIRC_EASEIN: 19

TWEENTYPE_CIRC_EASEINOUT: 21

TWEENTYPE_CIRC_EASEOUT: 20

TWEENTYPE_CUBIC_EASEIN: 7

TWEENTYPE_CUBIC_EASEINOUT: 9

TWEENTYPE_CUBIC_EASEOUT: 8

TWEENTYPE_CUSTOM_EASING: -1

TWEENTYPE_ELASTIC_EASEIN: 22

TWEENTYPE_ELASTIC_EASEINOUT: 24

TWEENTYPE_ELASTIC_EASEOUT: 23

TWEENTYPE_EXPO_EASEIN: 16

TWEENTYPE_EXPO_EASEINOUT: 18

TWEENTYPE_EXPO_EASEOUT: 17

TWEENTYPE_LINEAR: 0

TWEENTYPE_QUAD_EASEIN: 4

TWEENTYPE_QUAD_EASEINOUT: 6

TWEENTYPE_QUAD_EASEOUT: 5

TWEENTYPE_QUART_EASEIN: 10

TWEENTYPE_QUART_EASEINOUT: 12

TWEENTYPE_QUART_EASEOUT: 11

TWEENTYPE_QUINT_EASEIN: 13

TWEENTYPE_QUINT_EASEINOUT: 15

TWEENTYPE_QUINT_EASEOUT: 14

TWEENTYPE_SINE_EASEIN: 1

TWEENTYPE_SINE_EASEINOUT: 3

TWEENTYPE_SINE_EASEOUT: 2

TWEENTYPE_TWEEN_EASING_MAX: 10000

TYPE_BATCH_COMMAND: 3

TYPE_BOOLEAN: 5

TYPE_BYTE: 1

TYPE_CUSTOM_COMMAND: 2

TYPE_DOUBLE: 4

TYPE_FLOAT: 3

TYPE_GROUP_COMMAND: 4

TYPE_INTEGER: 2

TYPE_INT_KEY_MAP: 9

TYPE_MAP: 8

TYPE_MESH_COMMAND: 5

TYPE_NONE: 0

TYPE_ORTHOGRAPHIC: 2

TYPE_PERSPECTIVE: 1

TYPE_PRIMITIVE_COMMAND: 6

TYPE_QUAD_COMMAND: 1

TYPE_STRING: 6

TYPE_TRIANGLES_COMMAND: 7

TYPE_UNKNOWN_COMMAND: 0

TYPE_VECTOR: 7

VERTEX_ATTRIB_FLAG_BLEND_INDEX: 32

VERTEX_ATTRIB_FLAG_BLEND_WEIGHT: 16

VERTEX_ATTRIB_FLAG_COLOR: 2

VERTEX_ATTRIB_FLAG_NONE: 0

VERTEX_ATTRIB_FLAG_NORMAL: 8

VERTEX_ATTRIB_FLAG_POSITION: 1

VERTEX_ATTRIB_FLAG_POS_COLOR_TEX: 7

VERTEX_ATTRIB_FLAG_TEX_COORD: 4


-- End of hexm.client.ui.consts.cc_consts