-- ======================================================================
-- Module: hexm.client.ui.consts.ccui_consts
-- Source: package.loaded
-- Type: table
-- Order: #1207
-- ======================================================================

-- Module type: table

ANIMATIONTYPE_ANIMATION_LOOP_BACK: 1

ANIMATIONTYPE_ANIMATION_LOOP_FRONT: 0

ANIMATIONTYPE_ANIMATION_MAX: 2

ANIMATIONTYPE_ANIMATION_NO_LOOP: -3

ANIMATIONTYPE_ANIMATION_TO_LOOP_BACK: -1

ANIMATIONTYPE_ANIMATION_TO_LOOP_FRONT: -2

ANIMATIONTYPE_SINGLE_FRAME: -4

BLENDTYPE_BLEND_ADD: 8

BLENDTYPE_BLEND_ALPHA: 12

BLENDTYPE_BLEND_DARKEN: 2

BLENDTYPE_BLEND_DIFFERENCE: 10

BLENDTYPE_BLEND_ERASE: 13

BLENDTYPE_BLEND_HARD_LIGHT: 7

BLENDTYPE_BLEND_INVERT: 11

BLENDTYPE_BLEND_LAYER: 1

BLENDTYPE_BLEND_LIGHTEN: 4

BLENDTYPE_BLEND_MULTIPLY: 3

BLENDTYPE_BLEND_NORMAL: 0

BLENDTYPE_BLEND_OVERLAY: 6

BLENDTYPE_BLEND_SCREEN: 5

BLENDTYPE_BLEND_SUBSTRACT: 9

CHECKBOX_EVENTTYPE_SELECTED: 0

CHECKBOX_EVENTTYPE_UNSELECTED: 1

CHECKBOX_STATE_EVENT_SELECTED: 0

CHECKBOX_STATE_EVENT_UNSELECTED: 1

CONFIGTYPE_COCOSTUDIO_BINARY: 2

CONFIGTYPE_COCOSTUDIO_JSON: 1

CONFIGTYPE_DRAGONBONE_XML: 0

DISPLAYTYPE_CS_DISPLAY_ARMATURE: 1

DISPLAYTYPE_CS_DISPLAY_MAX: 3

DISPLAYTYPE_CS_DISPLAY_PARTICLE: 2

DISPLAYTYPE_CS_DISPLAY_SPRITE: 0

FRAMEEASETYPE_BACK_EASEIN: 25

FRAMEEASETYPE_BACK_EASEINOUT: 27

FRAMEEASETYPE_BACK_EASEOUT: 26

FRAMEEASETYPE_BOUNCE_EASEIN: 28

FRAMEEASETYPE_BOUNCE_EASEINOUT: 30

FRAMEEASETYPE_BOUNCE_EASEOUT: 29

FRAMEEASETYPE_CIRC_EASEIN: 19

FRAMEEASETYPE_CIRC_EASEINOUT: 21

FRAMEEASETYPE_CIRC_EASEOUT: 20

FRAMEEASETYPE_CUBIC_EASEIN: 7

FRAMEEASETYPE_CUBIC_EASEINOUT: 9

FRAMEEASETYPE_CUBIC_EASEOUT: 8

FRAMEEASETYPE_CUSTOM: -1

FRAMEEASETYPE_ELASTIC_EASEIN: 22

FRAMEEASETYPE_ELASTIC_EASEINOUT: 24

FRAMEEASETYPE_ELASTIC_EASEOUT: 23

FRAMEEASETYPE_EXPO_EASEIN: 16

FRAMEEASETYPE_EXPO_EASEINOUT: 18

FRAMEEASETYPE_EXPO_EASEOUT: 17

FRAMEEASETYPE_LINERAR: 0

FRAMEEASETYPE_QUAD_EASEIN: 4

FRAMEEASETYPE_QUAD_EASEINOUT: 6

FRAMEEASETYPE_QUAD_EASEOUT: 5

FRAMEEASETYPE_QUART_EASEIN: 10

FRAMEEASETYPE_QUART_EASEINOUT: 12

FRAMEEASETYPE_QUART_EASEOUT: 11

FRAMEEASETYPE_QUINT_EASEIN: 13

FRAMEEASETYPE_QUINT_EASEINOUT: 15

FRAMEEASETYPE_QUINT_EASEOUT: 14

FRAMEEASETYPE_SINE_EASEIN: 1

FRAMEEASETYPE_SINE_EASEINOUT: 3

FRAMEEASETYPE_SINE_EASEOUT: 2

FRAMEEASETYPE_TWEEN_EASING_MAX: 10000

FRAMEEASINGTYPE_KFRAMEEASINGBACKIN: 11

FRAMEEASINGTYPE_KFRAMEEASINGBACKINOUT: 13

FRAMEEASINGTYPE_KFRAMEEASINGBACKOUT: 12

FRAMEEASINGTYPE_KFRAMEEASINGBOUNCEIN: 8

FRAMEEASINGTYPE_KFRAMEEASINGBOUNCEINOUT: 10

FRAMEEASINGTYPE_KFRAMEEASINGBOUNCEOUT: 9

FRAMEEASINGTYPE_KFRAMEEASINGCUBICIN: 2

FRAMEEASINGTYPE_KFRAMEEASINGCUBICINOUT: 4

FRAMEEASINGTYPE_KFRAMEEASINGCUBICOUT: 3

FRAMEEASINGTYPE_KFRAMEEASINGELASTICIN: 5

FRAMEEASINGTYPE_KFRAMEEASINGELASTICINOUT: 7

FRAMEEASINGTYPE_KFRAMEEASINGELASTICOUT: 6

FRAMEEASINGTYPE_KFRAMEEASINGINSTANT: 0

FRAMEEASINGTYPE_KFRAMEEASINGLINEAR: 1

FRAMETYPE_KKEYFRAMEFADE: 4

FRAMETYPE_KKEYFRAMEMAX: 5

FRAMETYPE_KKEYFRAMEMOVE: 0

FRAMETYPE_KKEYFRAMEROTATE: 2

FRAMETYPE_KKEYFRAMESCALE: 1

FRAMETYPE_KKEYFRAMETINT: 3

GRAVITY_BOTTOM: 4

GRAVITY_CENTER_HORIZONTAL: 2

GRAVITY_CENTER_VERTICAL: 5

GRAVITY_LEFT: 0

GRAVITY_RIGHT: 1

GRAVITY_TOP: 3

INNERACTIONTYPE_LOOPACTION: 0

INNERACTIONTYPE_NOLOOPACTION: 1

INNERACTIONTYPE_SINGLEFRAME: 2

LABEL_LABELTYPE_BMFONT: 1

LABEL_LABELTYPE_CHARMAP: 2

LABEL_LABELTYPE_STRING_TEXTURE: 3

LABEL_LABELTYPE_TTF: 0

LAYOUTCOMPONENT_HORIZONTALEDGE_CENTER: 3

LAYOUTCOMPONENT_HORIZONTALEDGE_LEFT: 1

LAYOUTCOMPONENT_HORIZONTALEDGE_NONE: 0

LAYOUTCOMPONENT_HORIZONTALEDGE_RIGHT: 2

LAYOUTCOMPONENT_VERTICALEDGE_BOTTOM: 1

LAYOUTCOMPONENT_VERTICALEDGE_CENTER: 3

LAYOUTCOMPONENT_VERTICALEDGE_NONE: 0

LAYOUTCOMPONENT_VERTICALEDGE_TOP: 2

LAYOUTPARAMETER_TYPE_LINEAR: 1

LAYOUTPARAMETER_TYPE_NONE: 0

LAYOUTPARAMETER_TYPE_RELATIVE: 2

LAYOUT_BACKGROUNDCOLORTYPE_GRADIENT: 2

LAYOUT_BACKGROUNDCOLORTYPE_NONE: 0

LAYOUT_BACKGROUNDCOLORTYPE_SOLID: 1

LAYOUT_CLIPPINGTYPE_SCISSOR: 1

LAYOUT_CLIPPINGTYPE_STENCIL: 0

LAYOUT_TYPE_ABSOLUTE: 0

LAYOUT_TYPE_HORIZONTAL: 2

LAYOUT_TYPE_RELATIVE: 3

LAYOUT_TYPE_VERTICAL: 1

LINEARLAYOUTPARAMETER_LINEARGRAVITY_BOTTOM: 4

LINEARLAYOUTPARAMETER_LINEARGRAVITY_CENTER_HORIZONTAL: 6

LINEARLAYOUTPARAMETER_LINEARGRAVITY_CENTER_VERTICAL: 5

LINEARLAYOUTPARAMETER_LINEARGRAVITY_LEFT: 1

LINEARLAYOUTPARAMETER_LINEARGRAVITY_NONE: 0

LINEARLAYOUTPARAMETER_LINEARGRAVITY_RIGHT: 3

LINEARLAYOUTPARAMETER_LINEARGRAVITY_TOP: 2

LISTVIEW_EVENTTYPE_ON_SELECTED_ITEM_END: 1

LISTVIEW_EVENTTYPE_ON_SELECTED_ITEM_START: 0

LISTVIEW_GRAVITY_BOTTOM: 4

LISTVIEW_GRAVITY_CENTER_HORIZONTAL: 2

LISTVIEW_GRAVITY_CENTER_VERTICAL: 5

LISTVIEW_GRAVITY_LEFT: 0

LISTVIEW_GRAVITY_RIGHT: 1

LISTVIEW_GRAVITY_TOP: 3

LISTVIEW_ONSELECTEDITEM_END: 1

LISTVIEW_ONSELECTEDITEM_START: 0

LOADINGBAR_DIRECTION_LEFT: 0

LOADINGBAR_DIRECTION_RIGHT: 1

MOBILEINPUTTYPE_MOBILEINPUTTYPE_ALPHABER: 2

MOBILEINPUTTYPE_MOBILEINPUTTYPE_ALPHANUMERIC: 3

MOBILEINPUTTYPE_MOBILEINPUTTYPE_EMAILADDRESS: 4

MOBILEINPUTTYPE_MOBILEINPUTTYPE_NONE: -1

MOBILEINPUTTYPE_MOBILEINPUTTYPE_NORMAL: 0

MOBILEINPUTTYPE_MOBILEINPUTTYPE_NUMBER: 1

MOBILEINPUTTYPE_MOBILEINPUTTYPE_PASSWORD: 5

MOVEMENTEVENTTYPE_COMPLETE: 1

MOVEMENTEVENTTYPE_LOOP_COMPLETE: 2

MOVEMENTEVENTTYPE_START: 0

NODE_FLAGS_CONTENT_SIZE_DIRTY: 2

NODE_FLAGS_DIRTY_MASK: 3

NODE_FLAGS_IS_HITTED: 4

NODE_FLAGS_TRANSFORM_DIRTY: 1

NODE_NODECALLBACKTYPE_ENTER: 0

NODE_NODECALLBACKTYPE_ENTERTRANSITIONDIDFINISH: 3

NODE_NODECALLBACKTYPE_EXIT: 1

NODE_NODECALLBACKTYPE_EXITTRANSITIONDIDSTART: 2

NODE_NODECALLBACKTYPE_RELEASE: 4

PAGEVIEW_AUTOSCROLLDIRECTION_LEFT: 0

PAGEVIEW_AUTOSCROLLDIRECTION_RIGHT: 1

PAGEVIEW_EVENTTYPE_TURNING: 0

PAGEVIEW_EVENT_TURNING: 0

PAGEVIEW_TOUCHDIRECTION_LEFT: 0

PAGEVIEW_TOUCHDIRECTION_RIGHT: 1

PROGRESSTIMER_TYPE_BAR: 1

PROGRESSTIMER_TYPE_RADIAL: 0

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_CENTER_IN_PARENT: 5

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_LOCATION_ABOVE_CENTER: 11

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_LOCATION_ABOVE_LEFTALIGN: 10

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_LOCATION_ABOVE_RIGHTALIGN: 12

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_LOCATION_BELOW_CENTER: 20

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_LOCATION_BELOW_LEFTALIGN: 19

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_LOCATION_BELOW_RIGHTALIGN: 21

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_LOCATION_LEFT_OF_BOTTOMALIGN: 15

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_LOCATION_LEFT_OF_CENTER: 14

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_LOCATION_LEFT_OF_TOPALIGN: 13

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_LOCATION_RIGHT_OF_BOTTOMALIGN: 18

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_LOCATION_RIGHT_OF_CENTER: 17

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_LOCATION_RIGHT_OF_TOPALIGN: 16

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_NONE: 0

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_PARENT_BOTTOM_CENTER_HORIZONTAL: 8

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_PARENT_LEFT_BOTTOM: 7

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_PARENT_LEFT_CENTER_VERTICAL: 4

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_PARENT_RIGHT_BOTTOM: 9

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_PARENT_RIGHT_CENTER_VERTICAL: 6

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_PARENT_TOP_CENTER_HORIZONTAL: 2

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_PARENT_TOP_LEFT: 1

RELATIVELAYOUTPARAMETER_RELATIVEALIGN_PARENT_TOP_RIGHT: 3

RICHELEMENT_TYPE_CUSTOM: 2

RICHELEMENT_TYPE_IMAGE: 1

RICHELEMENT_TYPE_TEXT: 0

SCENEREADER_ATTACHCOMPONENTTYPE_DEFAULT: 0

SCENEREADER_ATTACHCOMPONENTTYPE_EMPTY_NODE: 0

SCENEREADER_ATTACHCOMPONENTTYPE_RENDER_NODE: 1

SCROLLVIEW_BOUNCETYPE_AUTO_SPEED_ACCELERATION_OF_DIS: 2

SCROLLVIEW_BOUNCETYPE_AUTO_SPEED_ATTENUATED_OF_DIS: 1

SCROLLVIEW_BOUNCETYPE_AUTO_SPEED_ATTENUATED_OF_TIME: 4

SCROLLVIEW_BOUNCETYPE_AUTO_SPEED_OF_DIS: 0

SCROLLVIEW_BOUNCETYPE_AUTO_SPEED_OF_TIME: 3

SCROLLVIEW_BOUNCETYPE_CUSTOMSIZE: 5

SCROLLVIEW_DIRECTION_BOTH: 3

SCROLLVIEW_DIRECTION_HORIZONTAL: 2

SCROLLVIEW_DIRECTION_NONE: 0

SCROLLVIEW_DIRECTION_VERTICAL: 1

SCROLLVIEW_EVENTTYPE_AUTO_SCROLLING: 12

SCROLLVIEW_EVENTTYPE_BOUNCE_BOTTOM: 6

SCROLLVIEW_EVENTTYPE_BOUNCE_LEFT: 7

SCROLLVIEW_EVENTTYPE_BOUNCE_RIGHT: 8

SCROLLVIEW_EVENTTYPE_BOUNCE_TOP: 5

SCROLLVIEW_EVENTTYPE_BOUNCE_TOUCH_BEGAN: 9

SCROLLVIEW_EVENTTYPE_BOUNCE_TOUCH_CANCELLED: 11

SCROLLVIEW_EVENTTYPE_BOUNCE_TOUCH_ENDED: 10

SCROLLVIEW_EVENTTYPE_SCROLLING: 4

SCROLLVIEW_EVENTTYPE_SCROLL_TO_BOTTOM: 1

SCROLLVIEW_EVENTTYPE_SCROLL_TO_LEFT: 2

SCROLLVIEW_EVENTTYPE_SCROLL_TO_RIGHT: 3

SCROLLVIEW_EVENTTYPE_SCROLL_TO_TOP: 0

SCROLLVIEW_EVENT_BOUNCE_BOTTOM: 6

SCROLLVIEW_EVENT_BOUNCE_LEFT: 7

SCROLLVIEW_EVENT_BOUNCE_RIGHT: 8

SCROLLVIEW_EVENT_BOUNCE_TOP: 5

SCROLLVIEW_EVENT_SCROLLING: 4

SCROLLVIEW_EVENT_SCROLL_TO_BOTTOM: 1

SCROLLVIEW_EVENT_SCROLL_TO_LEFT: 2

SCROLLVIEW_EVENT_SCROLL_TO_RIGHT: 3

SCROLLVIEW_EVENT_SCROLL_TO_TOP: 0

SLIDER_EVENTTYPE_ON_PERCENTAGE_CHANGED: 0

SLIDER_PERCENTCHANGED: 6

SPRITE_QUADTYPE_QUADTYPE_BASE: 1

SPRITE_QUADTYPE_QUADTYPE_BASEEX: 256

SPRITE_QUADTYPE_QUADTYPE_CAMERA: 8192

SPRITE_QUADTYPE_QUADTYPE_CIRCULAR: 8

SPRITE_QUADTYPE_QUADTYPE_EXTERNAL: 32

SPRITE_QUADTYPE_QUADTYPE_EXTERNAL_EDIT: 16384

SPRITE_QUADTYPE_QUADTYPE_LIVE: 128

SPRITE_QUADTYPE_QUADTYPE_NONE: 0

SPRITE_QUADTYPE_QUADTYPE_ROOM: 16

SPRITE_QUADTYPE_QUADTYPE_SKIN: 2

SPRITE_QUADTYPE_QUADTYPE_TEXT: 4

SPRITE_QUADTYPE_QUADTYPE_TRAJECTORY: 64

STYLE_STYLEATTRTYPE_ATTRTYPEALPHA: 2

STYLE_STYLEATTRTYPE_ATTRTYPECOLOR: 1

STYLE_STYLEATTRTYPE_ATTRTYPESCALE: 3

STYLE_STYLESTATE_STATE_DISABLED: 4

STYLE_STYLESTATE_STATE_DOWN: 2

STYLE_STYLESTATE_STATE_NONE: 0

STYLE_STYLESTATE_STATE_NORMAL: 1

STYLE_STYLESTATE_STATE_SELECT: 3

TEXTFIELD_EVENTTYPE_ATTACH_WITH_IME: 0

TEXTFIELD_EVENTTYPE_DELETE_BACKWARD: 3

TEXTFIELD_EVENTTYPE_DETACH_WITH_IME: 1

TEXTFIELD_EVENTTYPE_INSERT_TEXT: 2

TEXTFIELD_EVENTTYPE_TEXT_CHANGED: 2

TEXTFIELD_EVENT_ATTACH_WITH_IME: 0

TEXTFIELD_EVENT_DELETE_BACKWARD: 3

TEXTFIELD_EVENT_DETACH_WITH_IME: 1

TEXTFIELD_EVENT_INSERT_TEXT: 2

TEXTFIELD_FONTTYPE_SYSTEM: 0

TEXTFIELD_FONTTYPE_TTF: 1

TOUCH_EVENT_BEGAN: 0

TOUCH_EVENT_CANCELED: 3

TOUCH_EVENT_ENDED: 2

TOUCH_EVENT_MOVED: 1

TextHAlignment_HCENTER: 2

TextHAlignment_LEFT: 1

TextHAlignment_RIGHT: 4

TextVAlignment_BOTTOM: 16

TextVAlignment_TOP: 0

TextVAlignment_VCENTER: 8

WIDGET_BRIGHTSTYLE_HIGHLIGHT: 1

WIDGET_BRIGHTSTYLE_NONE: -1

WIDGET_BRIGHTSTYLE_NORMAL: 0

WIDGET_POSITIONTYPE_ABSOLUTE: 0

WIDGET_POSITIONTYPE_PERCENT: 1

WIDGET_SIZETYPE_ABSOLUTE: 0

WIDGET_SIZETYPE_PERCENT: 1

WIDGET_TEXTURERESTYPE_LOCAL: 0

WIDGET_TEXTURERESTYPE_PLIST: 1

WIDGET_TOUCHEVENTTYPE_BEGAN: 0

WIDGET_TOUCHEVENTTYPE_CANCELED: 3

WIDGET_TOUCHEVENTTYPE_ENDED: 2

WIDGET_TOUCHEVENTTYPE_MOVED: 1

WIDGET_TOUCHEVENTTYPE_MOVEDENTER: 4

WIDGET_TOUCHEVENTTYPE_MOVEDLEAVE: 5


-- End of hexm.client.ui.consts.ccui_consts