-- ======================================================================
-- Module: hexm.common.property_define.npc.attr
-- Source: package.loaded
-- Type: table
-- Order: #2554
-- ======================================================================

-- Module type: table

NpcAttr: class {
  -- Metatable:
  --   __tostring: yes
  __non_zero_attrs__: instance {
    -- Metatable:
    --   __index: table
    --   __tostring: yes
    BASH_UP: 1
    BASH_UP_RDC: 1
    BODY_STRENGTH_1: 1
    BODY_STRENGTH_2: 1
    BODY_STRENGTH_3: 1
    BODY_STRENGTH_4: 1
    GP_BEHIT_DMG_IND: 1
    GP_DIR: 1
    GP_DMG_IND: 1
    GP_REAL_DMG_IND: 1
    HP_MAX: 1
    HS_ATK_RATE: 1
    HS_BIANSHI: 1
    HS_BUXIE: 1
    HS_BUXIE_ATK: 2.8
    HS_BUXIE_DEF: 2.2
    HS_BUXIE_MAX: 1.6
    HS_CAIHUA: 1
    HS_CAIHUA_ATK: 2.8
    HS_CAIHUA_DEF: 2.2
    HS_CAIHUA_MAX: 1.6
    HS_CONGHUI: 1
    HS_CONGHUI_ATK: 2.8
    HS_CONGHUI_DEF: 2.2
    HS_CONGHUI_MAX: 1.6
    HS_CRI_A: 1.6
    HS_CRI_A_DEF: 1.6
    HS_CRI_A_rate: 1
    HS_CRI_A_reduce_rate: 1
    HS_CRI_B: 1.6
    HS_CRI_B_DEF: 1.6
    HS_CRI_B_rate: 1
    HS_CRI_B_reduce_rate: 1
    HS_KONGCHANG: 1
    HS_KOUCAI: 1
    HS_SIKAO: 1
    HS_ZIXIN: 1
    HS_ZIXIN_ATK: 2.8
    HS_ZIXIN_DEF: 2.2
    HS_ZIXIN_MAX: 1.6
    LIFE_COLD_ATK: 1
    LIFE_COLD_DEF: 1
    LIFE_HOT_ATK: 1
    LIFE_HOT_DEF: 1
    LIFE_MIND_ATK: 1
    LIFE_MIND_DEF: 1
    LIFE_TOXIC_ATK: 1
    LIFE_TOXIC_DEF: 1
    LZ_BODY_MAX: 1
    LZ_DETECT_1: 1
    LZ_DETECT_2: 1
    LZ_DETECT_3: 1
    LZ_DETECT_4: 1
    LZ_HP_MAX_DOCTOR: 1.6
    LZ_M_DEF_DOCTOR: 2.2
    LZ_M_DMG_DOCTOR: 1.6
    LZ_P_DEF_DOCTOR: 2.2
    LZ_P_DMG_DOCTOR: 1.6
    LZ_TREAT_1: 1
    LZ_TREAT_2: 1
    LZ_TREAT_3: 1
    MAX_PRO_ATK_A: 1
    MAX_PRO_ATK_B: 1
    MAX_PRO_ATK_C: 1
    MAX_PRO_ATK_D: 1
    MAX_PRO_ATK_E: 1
    MAX_W_ATK: 1
    MIN_PRO_ATK_A: 1
    MIN_PRO_ATK_B: 1
    MIN_PRO_ATK_C: 1
    MIN_PRO_ATK_D: 1
    MIN_PRO_ATK_E: 1
    MIN_W_ATK: 1
    NPC_FEAST: 1
    NPC_HEALTH: 1
    NPC_MOOD: 1
    NPC_REST_MAX: 1
    PRO_ATK_A_SCALE: 1
    PRO_ATK_B_SCALE: 1
    PRO_ATK_CRI_UP: 1
    PRO_ATK_CRI_UP_RDC: 1
    PRO_ATK_C_SCALE: 1
    PRO_ATK_D_SCALE: 1
    PRO_ATK_E_SCALE: 1
    PRO_DEF_A: 1
    PRO_DEF_A_SCALE: 1
    PRO_DEF_B: 1
    PRO_DEF_B_SCALE: 1
    PRO_DEF_C: 1
    PRO_DEF_C_SCALE: 1
    PRO_DEF_D: 1
    PRO_DEF_D_SCALE: 1
    PRO_DEF_E: 1
    PRO_DEF_E_SCALE: 1
    PRO_HEAL_SCALE: 1
    PRO_PEN_A: 1
    PRO_PEN_B: 1
    PRO_PEN_C: 1
    PRO_PEN_D: 1
    PRO_PEN_E: 1
    QIJUE_DAMAGE_SCALE: 1
    QIJUE_REDUCE: 1
    WEAK_DMGUP_RATE: 1
    W_ATK_CRI_UP: 1
    W_ATK_CRI_UP_RDC: 1
    W_ATK_PEN: 1
    W_ATK_PEN_RDC: 1
    W_ATK_SCALE: 1
    W_DEF: 1
    W_DEF_SCALE: 1
    W_HEAL_RDC_SCALE: 1
    W_HEAL_SCALE: 1
    XUEWEI_A_DEF: 1
    XUEWEI_B_DEF: 1
    XUEWEI_C_DEF: 1
    XUEWEI_D_DEF: 1
    XUEWEI_E_DEF: 1
    YS_BUILD_1: 1
    YS_BUILD_2: 1
    YS_BUILD_3: 1
    YS_BUILD_DEF_1: 1.6
    YS_BUILD_DEF_2: 1.6
    YS_BUILD_HP: 1.6
    YS_MACHINE_ATK_1: 1.6
    YS_MACHINE_ATK_2: 2.2
    ZY_DMG_SUPPORT: 1
    ZY_DRAW_1: 1
    ZY_DRAW_2: 1
    ZY_DRAW_3: 1
    ZY_DRAW_4: 1
    ZY_HP_GOUZAI_MAX: 1.6
    ZY_MP_SCHEME: 1.6
    ZY_MP_SUSPECT: 1
    ZY_P_ATK_1: 1.6
    ZY_P_ATK_2: 1.6
    ZY_P_DEF_FAKE: 1
  }
  __property_all__: instance {
    -- Metatable:
    --   __index: table
    --   __tostring: yes
    ABR_AVOID_PROB: 0.0
    ACR_PROB: 0.0
    ADD_ACR_PROB: 0.0
    ADD_ACR_RESIST_PROB: 0.0
    ADD_BASH_PROB: 0.0
    ADD_BASH_RESIST_PROB: 0.0
    ADD_CRI_PROB: 0.0
    ADD_CRI_RESIST_PROB: 0.0
    ALL_ONELEVEL_ATTR: 0.0
    BASH_PROB: 0.0
    BASH_UP: 1
    BASH_UP_RDC: 1
    BODY_STRENGTH_1: 1
    BODY_STRENGTH_2: 1
    BODY_STRENGTH_3: 1
    BODY_STRENGTH_4: 1
    CRI_PROB: 0.0
    CS_ITS: 0.0
    DAMAGE_REDUCE: 0
    DIRECT_BASH_PROB: 0.0
    DIRECT_CRI_PROB: 0.0
    GP_BEHIT_DMG_IND: 1
    GP_DIR: 1
    GP_DMG_IND: 1
    GP_REAL_DMG_IND: 1
    HEAL_CRI_UP: 0.0
    HP: -1.0
    HP_MAX: 1
    HS_ATK_RATE: 1
    HS_BIANSHI: 1
    HS_BUXIE: 1
    HS_BUXIE_ATK: 2.8
    HS_BUXIE_DEF: 2.2
    HS_BUXIE_MAX: 1.6
    HS_CAIHUA: 1
    HS_CAIHUA_ATK: 2.8
    HS_CAIHUA_DEF: 2.2
    HS_CAIHUA_MAX: 1.6
    HS_CONGHUI: 1
    HS_CONGHUI_ATK: 2.8
    HS_CONGHUI_DEF: 2.2
    HS_CONGHUI_MAX: 1.6
    HS_CRI_A: 1.6
    HS_CRI_A_DEF: 1.6
    HS_CRI_A_rate: 1
    HS_CRI_A_reduce_rate: 1
    HS_CRI_B: 1.6
    HS_CRI_B_DEF: 1.6
    HS_CRI_B_rate: 1
    HS_CRI_B_reduce_rate: 1
    HS_KONGCHANG: 1
    HS_KOUCAI: 1
    HS_SIKAO: 1
    HS_ZIXIN: 1
    HS_ZIXIN_ATK: 2.8
    HS_ZIXIN_DEF: 2.2
    HS_ZIXIN_MAX: 1.6
    LIFE_ALT_ATK: 0.0
    LIFE_ALT_DEF: 0.0
    LIFE_ALT_HP: 0
    LIFE_ALT_HP_MAX: 0.0
    LIFE_COLD_ATK: 1
    LIFE_COLD_DEF: 1
    LIFE_COLD_HP: 0
    LIFE_COLD_HP_MAX: 0.0
    LIFE_HOT_ATK: 1
    LIFE_HOT_DEF: 1
    LIFE_HOT_HP: 0
    LIFE_HOT_HP_MAX: 0.0
    LIFE_MIND_ATK: 1
    LIFE_MIND_DEF: 1
    LIFE_MIND_HP: 0
    LIFE_MIND_HP_MAX: 0.0
    LIFE_SWIM_ATK: 0.0
    LIFE_SWIM_DEF: 0.0
    LIFE_SWIM_HP: 0
    LIFE_SWIM_HP_MAX: 0.0
    LIFE_TOXIC_ATK: 1
    LIFE_TOXIC_DEF: 1
    LIFE_TOXIC_HP: 0
    LIFE_TOXIC_HP_MAX: 0.0
    LIFE_WET_ATK: 0.0
    LIFE_WET_DEF: 0.0
    LIFE_WET_HP: 0
    LIFE_WET_HP_MAX: 0.0
    LZ_BODY: 0
    LZ_BODY_MAX: 1
    LZ_DETECT_1: 1
    LZ_DETECT_2: 1
    LZ_DETECT_3: 1
    LZ_DETECT_4: 1
    LZ_HP_DOCTOR: 0
    LZ_HP_MAX_DOCTOR: 1.6
    LZ_M_DEF_DOCTOR: 2.2
    LZ_M_DMG_DOCTOR: 1.6
    LZ_P_DEF_DOCTOR: 2.2
    LZ_P_DMG_DOCTOR: 1.6
    LZ_TREAT_1: 1
    LZ_TREAT_2: 1
    LZ_TREAT_3: 1
    LZ_TREAT_4: 0.0
    MACHINE_HP: 0.0
    MAX_N_ATK: 0.0
    MAX_PRO_ATK_A: 1
    MAX_PRO_ATK_B: 1
    MAX_PRO_ATK_C: 1
    MAX_PRO_ATK_D: 1
    MAX_PRO_ATK_E: 1
    MAX_W_ATK: 1
    MIN_N_ATK: 0.0
    MIN_PRO_ATK_A: 1
    MIN_PRO_ATK_B: 1
    MIN_PRO_ATK_C: 1
    MIN_PRO_ATK_D: 1
    MIN_PRO_ATK_E: 1
    MIN_W_ATK: 1
    NPC_FEAST: 1
    NPC_HEALTH: 1
    NPC_MOOD: 1
    NPC_REST: 0
    NPC_REST_MAX: 1
    N_ATK: 0.0
    N_ATK_CRI_UP: 0.0
    N_ATK_CRI_UP_RDC: 0.0
    N_ATK_DEF_MAX: 0.0
    N_ATK_IGR: 0.0
    N_ATK_IGR_RDC: 0.0
    N_ATK_PEN: 0.0
    N_ATK_PEN_MAX: 0.0
    N_ATK_PEN_RDC: 0.0
    N_ATK_SCALE: 0.0
    N_DEF: 0.0
    N_DEF_SCALE: 0.0
    N_HEAL: 0.0
    N_HEAL_RDC_SCALE: 0.0
    N_HEAL_SCALE: 0.0
    PRO_ATK_A_SCALE: 1
    PRO_ATK_B_SCALE: 1
    PRO_ATK_CRI_UP: 1
    PRO_ATK_CRI_UP_RDC: 1
    PRO_ATK_C_SCALE: 1
    PRO_ATK_D_SCALE: 1
    PRO_ATK_E_SCALE: 1
    PRO_ATK_H: 0.0
    PRO_DEF_A: 1
    PRO_DEF_A_SCALE: 1
    PRO_DEF_B: 1
    PRO_DEF_B_SCALE: 1
    PRO_DEF_C: 1
    PRO_DEF_C_SCALE: 1
    PRO_DEF_D: 1
    PRO_DEF_D_SCALE: 1
    PRO_DEF_E: 1
    PRO_DEF_E_SCALE: 1
    PRO_HEAL_SCALE: 1
    PRO_PEN_A: 1
    PRO_PEN_B: 1
    PRO_PEN_C: 1
    PRO_PEN_D: 1
    PRO_PEN_E: 1
    PRO_PEN_H: 0.0
    QIJUE_DAMAGE_SCALE: 1
    QIJUE_REDUCE: 1
    STATE_LEVEL_EXPLORE: 1
    STATE_LEVEL_KUNGFU: 1
    STATE_LEVEL_TRADE: 1
    TOTAL_PRO_ATK_MAX: 0.0
    TOTAL_PRO_ATK_MIN: 0.0
    WEAK_DMGUP_RATE: 1
    W_ATK: 0.0
    W_ATK_CRI_UP: 1
    W_ATK_CRI_UP_RDC: 1
    W_ATK_IGR: 0.0
    W_ATK_IGR_RDC: 0.0
    W_ATK_PEN: 1
    W_ATK_PEN_RDC: 1
    W_ATK_SCALE: 1
    W_DEF: 1
    W_DEF_SCALE: 1
    W_HEAL_RDC_SCALE: 1
    W_HEAL_SCALE: 1
    XIUWEI_EXPLORE: 0
    XIUWEI_KUNGFU: 0
    XIUWEI_TRADE: 0
    XUEWEI_ATK: 0
    XUEWEI_A_DEF: 1
    XUEWEI_B_DEF: 1
    XUEWEI_C_DEF: 1
    XUEWEI_D_DEF: 1
    XUEWEI_E_DEF: 1
    YS_BUILD_1: 1
    YS_BUILD_2: 1
    YS_BUILD_3: 1
    YS_BUILD_DEF_1: 1.6
    YS_BUILD_DEF_2: 1.6
    YS_BUILD_HP: 1.6
    YS_MACHINE_ATK_1: 1.6
    YS_MACHINE_ATK_2: 2.2
    YS_MACHINE_ATK_LOSS: 0.0
    YS_REAL_ATK: 0.0
    YS_REAL_HP: 0.0
    ZHENQI_DAMAGE: 0.0
    ZHENQI_DEF: 0.0
    ZHENQI_REPLY: 0.0
    ZY_DMG_SUPPORT: 1
    ZY_DRAW_1: 1
    ZY_DRAW_2: 1
    ZY_DRAW_3: 1
    ZY_DRAW_4: 1
    ZY_HP_GOUZAI: 0
    ZY_HP_GOUZAI_MAX: 1.6
    ZY_MP_SCHEME: 1.6
    ZY_MP_SUSPECT: 1
    ZY_P_ATK_1: 1.6
    ZY_P_ATK_2: 1.6
    ZY_P_DEF_FAKE: 1
    __packed_data__: ""
    cr_refreshing: class {
      -- Metatable:
      --   __tostring: yes
      __property_all__: <dict>
      __property_flag__: <dict>
      __property_index__: <instance>
      _initProperty: function(arg1, arg2)  -- @engine/common/classutils.lua:310-330
    }
    dynamic_attr: class {
      -- Metatable:
      --   __tostring: yes
      __property_all__: <dict>
      __property_flag__: <dict>
      __property_index__: <instance>
      _initProperty: function(arg1, arg2)  -- @engine/common/classutils.lua:310-330
    }
    res_recover_ts: class {
      -- Metatable:
      --   __tostring: yes
      __property_all__: <dict>
      __property_flag__: <dict>
      __property_index__: <instance>
      _initProperty: function(arg1, arg2)  -- @engine/common/classutils.lua:310-330
    }
    resource_empty: class {
      -- Metatable:
      --   __tostring: yes
      IS_CUSTOM_TYPE: true
      __len: nil
      __metaclass__: function(arg1)  -- @engine/common/classutils.lua:592-594
      __property_all__: <dict>
      __property_flag__: <dict>
      __property_index__: <instance>
      _initProperty: function(arg1, arg2)  -- @engine/common/classutils.lua:286-308
      ctor: function(arg1, arg2)  -- @engine/common/classutils.lua:612-621
      items: function(arg1)  -- @engine/common/classutils.lua:655-661
      keys: function(arg1)  -- @engine/common/classutils.lua:639-645
      on_assign: function(arg1)  -- @engine/common/classutils.lua:632-633
      on_clear: function(arg1)  -- @engine/common/classutils.lua:626-627
      on_init: function(arg1, arg2)  -- @engine/common/classutils.lua:623-624
      on_setattr: function(arg1, arg2, arg3, arg4)  -- @engine/common/classutils.lua:636-637
      on_update: function(arg1, arg2)  -- @engine/common/classutils.lua:629-630
      setdefault: function(arg1, arg2, arg3)  -- @engine/common/classutils.lua:663-670
      to_valid_dict: function(arg1)  -- @engine/common/classutils.lua:672-709
      values: function(arg1)  -- @engine/common/classutils.lua:647-653
    }
    resource_id_map: <circular>
    salt: 0
  }
  __property_flag__: instance {
    -- Metatable:
    --   __index: table
    --   __tostring: yes
    ABR_AVOID_PROB: 4
    ACR_PROB: 4
    ADD_ACR_PROB: 4
    ADD_ACR_RESIST_PROB: 4
    ADD_BASH_PROB: 4
    ADD_BASH_RESIST_PROB: 4
    ADD_CRI_PROB: 4
    ADD_CRI_RESIST_PROB: 4
    ALL_ONELEVEL_ATTR: 4
    BASH_PROB: 4
    BASH_UP: 4
    BASH_UP_RDC: 4
    BODY_STRENGTH_1: 4
    BODY_STRENGTH_2: 4
    BODY_STRENGTH_3: 4
    BODY_STRENGTH_4: 4
    CRI_PROB: 4
    CS_ITS: 4
    DAMAGE_REDUCE: 4
    DIRECT_BASH_PROB: 4
    DIRECT_CRI_PROB: 4
    GP_BEHIT_DMG_IND: 4
    GP_DIR: 4
    GP_DMG_IND: 4
    GP_REAL_DMG_IND: 4
    HEAL_CRI_UP: 4
    HP: 4
    HP_MAX: 4
    HS_ATK_RATE: 4
    HS_BIANSHI: 4
    HS_BUXIE: 4
    HS_BUXIE_ATK: 4
    HS_BUXIE_DEF: 4
    HS_BUXIE_MAX: 4
    HS_CAIHUA: 4
    HS_CAIHUA_ATK: 4
    HS_CAIHUA_DEF: 4
    HS_CAIHUA_MAX: 4
    HS_CONGHUI: 4
    HS_CONGHUI_ATK: 4
    HS_CONGHUI_DEF: 4
    HS_CONGHUI_MAX: 4
    HS_CRI_A: 4
    HS_CRI_A_DEF: 4
    HS_CRI_A_rate: 4
    HS_CRI_A_reduce_rate: 4
    HS_CRI_B: 4
    HS_CRI_B_DEF: 4
    HS_CRI_B_rate: 4
    HS_CRI_B_reduce_rate: 4
    HS_KONGCHANG: 4
    HS_KOUCAI: 4
    HS_SIKAO: 4
    HS_ZIXIN: 4
    HS_ZIXIN_ATK: 4
    HS_ZIXIN_DEF: 4
    HS_ZIXIN_MAX: 4
    LIFE_ALT_ATK: 1
    LIFE_ALT_DEF: 1
    LIFE_ALT_HP: 1
    LIFE_ALT_HP_MAX: 1
    LIFE_COLD_ATK: 1
    LIFE_COLD_DEF: 4
    LIFE_COLD_HP: 1
    LIFE_COLD_HP_MAX: 1
    LIFE_HOT_ATK: 1
    LIFE_HOT_DEF: 4
    LIFE_HOT_HP: 1
    LIFE_HOT_HP_MAX: 1
    LIFE_MIND_ATK: 1
    LIFE_MIND_DEF: 4
    LIFE_MIND_HP: 1
    LIFE_MIND_HP_MAX: 1
    LIFE_SWIM_ATK: 1
    LIFE_SWIM_DEF: 1
    LIFE_SWIM_HP: 1
    LIFE_SWIM_HP_MAX: 1
    LIFE_TOXIC_ATK: 1
    LIFE_TOXIC_DEF: 4
    LIFE_TOXIC_HP: 1
    LIFE_TOXIC_HP_MAX: 1
    LIFE_WET_ATK: 1
    LIFE_WET_DEF: 1
    LIFE_WET_HP: 1
    LIFE_WET_HP_MAX: 1
    LZ_BODY: 4
    LZ_BODY_MAX: 4
    LZ_DETECT_1: 4
    LZ_DETECT_2: 4
    LZ_DETECT_3: 4
    LZ_DETECT_4: 4
    LZ_HP_DOCTOR: 4
    LZ_HP_MAX_DOCTOR: 4
    LZ_M_DEF_DOCTOR: 4
    LZ_M_DMG_DOCTOR: 4
    LZ_P_DEF_DOCTOR: 4
    LZ_P_DMG_DOCTOR: 4
    LZ_TREAT_1: 4
    LZ_TREAT_2: 4
    LZ_TREAT_3: 4
    LZ_TREAT_4: 4
    MACHINE_HP: 4
    MAX_N_ATK: 4
    MAX_PRO_ATK_A: 4
    MAX_PRO_ATK_B: 4
    MAX_PRO_ATK_C: 4
    MAX_PRO_ATK_D: 4
    MAX_PRO_ATK_E: 4
    MAX_W_ATK: 4
    MIN_N_ATK: 4
    MIN_PRO_ATK_A: 4
    MIN_PRO_ATK_B: 4
    MIN_PRO_ATK_C: 4
    MIN_PRO_ATK_D: 4
    MIN_PRO_ATK_E: 4
    MIN_W_ATK: 4
    NPC_FEAST: 4
    NPC_HEALTH: 4
    NPC_MOOD: 4
    NPC_REST: 4
    NPC_REST_MAX: 4
    N_ATK: 4
    N_ATK_CRI_UP: 4
    N_ATK_CRI_UP_RDC: 4
    N_ATK_DEF_MAX: 4
    N_ATK_IGR: 4
    N_ATK_IGR_RDC: 4
    N_ATK_PEN: 4
    N_ATK_PEN_MAX: 4
    N_ATK_PEN_RDC: 4
    N_ATK_SCALE: 4
    N_DEF: 4
    N_DEF_SCALE: 4
    N_HEAL: 4
    N_HEAL_RDC_SCALE: 4
    N_HEAL_SCALE: 4
    PRO_ATK_A_SCALE: 4
    PRO_ATK_B_SCALE: 4
    PRO_ATK_CRI_UP: 4
    PRO_ATK_CRI_UP_RDC: 4
    PRO_ATK_C_SCALE: 4
    PRO_ATK_D_SCALE: 4
    PRO_ATK_E_SCALE: 4
    PRO_ATK_H: 4
    PRO_DEF_A: 4
    PRO_DEF_A_SCALE: 4
    PRO_DEF_B: 4
    PRO_DEF_B_SCALE: 4
    PRO_DEF_C: 4
    PRO_DEF_C_SCALE: 4
    PRO_DEF_D: 4
    PRO_DEF_D_SCALE: 4
    PRO_DEF_E: 4
    PRO_DEF_E_SCALE: 4
    PRO_HEAL_SCALE: 4
    PRO_PEN_A: 4
    PRO_PEN_B: 4
    PRO_PEN_C: 4
    PRO_PEN_D: 4
    PRO_PEN_E: 4
    PRO_PEN_H: 4
    QIJUE_DAMAGE_SCALE: 4
    QIJUE_REDUCE: 4
    STATE_LEVEL_EXPLORE: 1
    STATE_LEVEL_KUNGFU: 1
    STATE_LEVEL_TRADE: 1
    TOTAL_PRO_ATK_MAX: 4
    TOTAL_PRO_ATK_MIN: 4
    WEAK_DMGUP_RATE: 4
    W_ATK: 4
    W_ATK_CRI_UP: 4
    W_ATK_CRI_UP_RDC: 4
    W_ATK_IGR: 4
    W_ATK_IGR_RDC: 4
    W_ATK_PEN: 4
    W_ATK_PEN_RDC: 4
    W_ATK_SCALE: 4
    W_DEF: 4
    W_DEF_SCALE: 4
    W_HEAL_RDC_SCALE: 4
    W_HEAL_SCALE: 4
    XIUWEI_EXPLORE: 1
    XIUWEI_KUNGFU: 4
    XIUWEI_TRADE: 1
    XUEWEI_ATK: 4
    XUEWEI_A_DEF: 4
    XUEWEI_B_DEF: 4
    XUEWEI_C_DEF: 4
    XUEWEI_D_DEF: 4
    XUEWEI_E_DEF: 4
    YS_BUILD_1: 4
    YS_BUILD_2: 4
    YS_BUILD_3: 4
    YS_BUILD_DEF_1: 4
    YS_BUILD_DEF_2: 4
    YS_BUILD_HP: 4
    YS_MACHINE_ATK_1: 4
    YS_MACHINE_ATK_2: 4
    YS_MACHINE_ATK_LOSS: 4
    YS_REAL_ATK: 4
    YS_REAL_HP: 4
    ZHENQI_DAMAGE: 4
    ZHENQI_DEF: 4
    ZHENQI_REPLY: 4
    ZY_DMG_SUPPORT: 4
    ZY_DRAW_1: 4
    ZY_DRAW_2: 4
    ZY_DRAW_3: 4
    ZY_DRAW_4: 4
    ZY_HP_GOUZAI: 4
    ZY_HP_GOUZAI_MAX: 4
    ZY_MP_SCHEME: 4
    ZY_MP_SUSPECT: 4
    ZY_P_ATK_1: 4
    ZY_P_ATK_2: 4
    ZY_P_DEF_FAKE: 4
    __packed_data__: 1
    cr_refreshing: 4
    dynamic_attr: 4
    res_recover_ts: 4
    resource_empty: 4
    resource_id_map: 4
    salt: 4
  }
  on_setattr: function(arg1, arg2, arg3, arg4)  -- @hexm/common/property_define/common_prop/attr_base.lua:48-57
}

NpcAttrBase: class {
  -- Metatable:
  --   __tostring: yes
  __property_all__: instance {
    -- Metatable:
    --   __index: table
    --   __tostring: yes
    NPC_FEAST: 0
    NPC_HEALTH: 0
    NPC_MOOD: 0
    NPC_REST: 0
    NPC_REST_MAX: 0
  }
  __property_flag__: instance {
    -- Metatable:
    --   __index: table
    --   __tostring: yes
    NPC_FEAST: 4
    NPC_HEALTH: 4
    NPC_MOOD: 4
    NPC_REST: 4
    NPC_REST_MAX: 4
  }
  __property_index__: <instance>
  _initProperty: function(arg1, arg2)  -- @engine/common/classutils.lua:310-330
}


-- End of hexm.common.property_define.npc.attr