-- ======================================================================
-- Module: hexm.common.property_define.ai_avatar.attr
-- Source: package.loaded
-- Type: table
-- Order: #4810
-- ======================================================================

-- Module type: table

AIAvtAttr: class {
  -- Metatable:
  --   __tostring: yes
  __non_zero_attrs__: instance {
    -- Metatable:
    --   __index: table
    --   __tostring: yes
    ABR_AVOID_PROB: 1
    ACR_PROB: 1
    ADD_ACR_PROB: 1
    ADD_ACR_RESIST_PROB: 1
    ADD_BASH_PROB: 1
    ADD_BASH_RESIST_PROB: 1
    ADD_CRI_PROB: 1
    ADD_CRI_RESIST_PROB: 1
    ALL_ONELEVEL_ATTR: 1
    ARCHER_AIM_RANGE: 1
    ARCHER_ARROW_DISTANCE: 1
    ARCHER_ARROW_SPEED: 1
    ARCHER_DAMAGE: 1
    ARCHER_DAMAGE_SCALE: 1
    ARCHER_FIRE_RESOURCE: 1
    ARCHER_FLY_SPEED: 1
    ARCHER_LOOP_TIME: 1
    ARCHER_POISIN_RESOURCE: 1
    ARCHER_SHOOT_SPEED: 1
    ARCHER_TIMESTOP_COST: 1
    ARCHER_TIMESTOP_EFFECT: 1
    ARCHER_TIMESTOP_TIME: 1
    ARCHER_WEAKPOINT_DAMAGE: 1
    ARCHER_WEAKPOINT_DAMAGE_SCALE: 1
    BASH_PROB: 1.00076
    BASH_UP: 1
    BASH_UP_RDC: 1
    BODY_STRENGTH_1: 1
    BODY_STRENGTH_2: 1
    BODY_STRENGTH_3: 1
    BODY_STRENGTH_4: 1
    CRI_PROB: 1.00152
    CS_ITS: 1
    DIRECT_BASH_PROB: 1
    DIRECT_CRI_PROB: 1
    GP_BEHIT_DMG_IND: 1
    GP_DIR: 1
    GP_DMG_IND: 1
    GP_REAL_DMG_IND: 1
    HEAL_CRI_UP: 1
    HP_MAX: 155.0
    HS_ATK_RATE: 1
    HS_BIANSHI: 2
    HS_BUXIE: 1
    HS_BUXIE_ATK: 7
    HS_BUXIE_DEF: 5
    HS_BUXIE_MAX: 3
    HS_CAIHUA: 1
    HS_CAIHUA_ATK: 7
    HS_CAIHUA_DEF: 5
    HS_CAIHUA_MAX: 3
    HS_CONGHUI: 1
    HS_CONGHUI_ATK: 7
    HS_CONGHUI_DEF: 5
    HS_CONGHUI_MAX: 3
    HS_CRI_A: 3
    HS_CRI_A_DEF: 3
    HS_CRI_A_rate: 1
    HS_CRI_A_reduce_rate: 1
    HS_CRI_B: 3
    HS_CRI_B_DEF: 3
    HS_CRI_B_rate: 1
    HS_CRI_B_reduce_rate: 1
    HS_KONGCHANG: 2
    HS_KOUCAI: 2
    HS_SIKAO: 2
    HS_ZIXIN: 1
    HS_ZIXIN_ATK: 7
    HS_ZIXIN_DEF: 5
    HS_ZIXIN_MAX: 3
    LIFE_COLD_ATK: 1
    LIFE_COLD_DEF: 1
    LIFE_HOT_ATK: 1
    LIFE_HOT_DEF: 1
    LIFE_MIND_ATK: 1
    LIFE_MIND_DEF: 1
    LIFE_TOXIC_ATK: 1
    LIFE_TOXIC_DEF: 1
    LZ_BODY_MAX: 1
    LZ_DETECT_1: 2
    LZ_DETECT_2: 2
    LZ_DETECT_3: 2
    LZ_DETECT_4: 2
    LZ_HP_MAX_DOCTOR: 3
    LZ_M_DEF_DOCTOR: 5
    LZ_M_DMG_DOCTOR: 3
    LZ_P_DEF_DOCTOR: 5
    LZ_P_DMG_DOCTOR: 3
    LZ_TREAT_1: 2
    LZ_TREAT_2: 2
    LZ_TREAT_3: 2
    MAX_PRO_ATK_A: 1
    MAX_PRO_ATK_B: 1
    MAX_PRO_ATK_C: 1
    MAX_PRO_ATK_D: 1
    MAX_PRO_ATK_E: 1
    MAX_W_ATK: 5.52
    MIN_PRO_ATK_A: 1
    MIN_PRO_ATK_B: 1
    MIN_PRO_ATK_C: 1
    MIN_PRO_ATK_D: 1
    MIN_PRO_ATK_E: 1
    MIN_W_ATK: 3.24
    PRO_ATK_A_SCALE: 1
    PRO_ATK_B_SCALE: 1
    PRO_ATK_CRI_UP: 1
    PRO_ATK_CRI_UP_RDC: 1
    PRO_ATK_C_SCALE: 1
    PRO_ATK_D_SCALE: 1
    PRO_ATK_E_SCALE: 1
    PRO_DEF_A: 1
    PRO_DEF_A_SCALE: 1
    PRO_DEF_B: 1
    PRO_DEF_B_SCALE: 1
    PRO_DEF_C: 1
    PRO_DEF_C_SCALE: 1
    PRO_DEF_D: 1
    PRO_DEF_D_SCALE: 1
    PRO_DEF_E: 1
    PRO_DEF_E_SCALE: 1
    PRO_HEAL_SCALE: 1
    PRO_PEN_A: 1
    PRO_PEN_B: 1
    PRO_PEN_C: 1
    PRO_PEN_D: 1
    PRO_PEN_E: 1
    WEAK_DMGUP_RATE: 1
    W_ATK_CRI_UP: 1
    W_ATK_CRI_UP_RDC: 1
    W_ATK_PEN: 1
    W_ATK_PEN_RDC: 1
    W_ATK_SCALE: 1
    W_DEF: 2.14
    W_DEF_SCALE: 1
    W_HEAL_RDC_SCALE: 1
    W_HEAL_SCALE: 1
    XIUWEI_EXPLORE: 1016
    XUEWEI_ATK: 1
    XUEWEI_A_DEF: 1
    XUEWEI_B_DEF: 1
    XUEWEI_C_DEF: 1
    XUEWEI_D_DEF: 1
    XUEWEI_E_DEF: 1
    YS_BUILD_1: 1
    YS_BUILD_2: 1
    YS_BUILD_3: 1
    YS_BUILD_DEF_1: 2
    YS_BUILD_DEF_2: 2
    YS_BUILD_HP: 2
    YS_MACHINE_ATK_1: 2
    YS_MACHINE_ATK_2: 3
    ZY_DMG_SUPPORT: 1
    ZY_DRAW_1: 1
    ZY_DRAW_2: 1
    ZY_DRAW_3: 1
    ZY_DRAW_4: 1
    ZY_HP_GOUZAI_MAX: 2
    ZY_MP_SCHEME: 2
    ZY_MP_SUSPECT: 1
    ZY_P_ATK_1: 2
    ZY_P_ATK_2: 2
    ZY_P_DEF_FAKE: 1
  }
  __property_all__: instance {
    -- Metatable:
    --   __index: table
    --   __tostring: yes
    ABR_AVOID_PROB: 1
    ACR_PROB: 1
    ADD_ACR_PROB: 1
    ADD_ACR_RESIST_PROB: 1
    ADD_BASH_PROB: 1
    ADD_BASH_RESIST_PROB: 1
    ADD_CRI_PROB: 1
    ADD_CRI_RESIST_PROB: 1
    ALL_DAMAGE_SCALE: 0
    ALL_ONELEVEL_ATTR: 1
    ARCHER_AIM_RANGE: 1
    ARCHER_ARROW_DISTANCE: 1
    ARCHER_ARROW_SPEED: 1
    ARCHER_DAMAGE: 1
    ARCHER_DAMAGE_SCALE: 1
    ARCHER_FIRE_RESOURCE: 1
    ARCHER_FLY_SPEED: 1
    ARCHER_LOOP_TIME: 1
    ARCHER_POISIN_RESOURCE: 1
    ARCHER_SHOOT_SPEED: 1
    ARCHER_TIMESTOP_COST: 1
    ARCHER_TIMESTOP_EFFECT: 1
    ARCHER_TIMESTOP_TIME: 1
    ARCHER_WEAKPOINT_DAMAGE: 1
    ARCHER_WEAKPOINT_DAMAGE_SCALE: 1
    BAINIAO_DAMAGE_SCALE: 0
    BASH_PROB: 1.00076
    BASH_UP: 1
    BASH_UP_RDC: 1
    BODY_STRENGTH_1: 1
    BODY_STRENGTH_2: 1
    BODY_STRENGTH_3: 1
    BODY_STRENGTH_4: 1
    CHU_DAMAGE_SCALE: 0
    CRI_PROB: 1.00152
    CS_ITS: 1
    DAMAGE_REDUCE: 0
    DAOLANG_DAMAGE_SCALE: 0
    DIRECT_BASH_PROB: 1
    DIRECT_CRI_PROB: 1
    GP_BEHIT_DMG_IND: 1
    GP_DIR: 1
    GP_DMG_IND: 1
    GP_REAL_DMG_IND: 1
    HEAL_CRI_UP: 1
    HONGCHEN_DAMAGE_SCALE: 0
    HP: -1.0
    HP_MAX: 155.0
    HS_ATK_RATE: 1
    HS_BIANSHI: 2
    HS_BUXIE: 1
    HS_BUXIE_ATK: 7
    HS_BUXIE_DEF: 5
    HS_BUXIE_MAX: 3
    HS_CAIHUA: 1
    HS_CAIHUA_ATK: 7
    HS_CAIHUA_DEF: 5
    HS_CAIHUA_MAX: 3
    HS_CONGHUI: 1
    HS_CONGHUI_ATK: 7
    HS_CONGHUI_DEF: 5
    HS_CONGHUI_MAX: 3
    HS_CRI_A: 3
    HS_CRI_A_DEF: 3
    HS_CRI_A_rate: 1
    HS_CRI_A_reduce_rate: 1
    HS_CRI_B: 3
    HS_CRI_B_DEF: 3
    HS_CRI_B_rate: 1
    HS_CRI_B_reduce_rate: 1
    HS_KONGCHANG: 2
    HS_KOUCAI: 2
    HS_SIKAO: 2
    HS_ZIXIN: 1
    HS_ZIXIN_ATK: 7
    HS_ZIXIN_DEF: 5
    HS_ZIXIN_MAX: 3
    JIAN_DAMAGE_SCALE: 0
    JINCHAN_DAMAGE_SCALE: 0
    KAIFENGJING_DAMAGE_SCALE: 0
    KAIFENGJING_REDUCE: 0
    KAIFENGSHOU_DAMAGE_SCALE: 0
    KAIFENGSHOU_REDUCE: 0
    KAIFENGXIAO_DAMAGE_SCALE: 0
    KAIFENGXIAO_REDUCE: 0
    KONG_DAMAGE_SCALE: 0
    LIANREN_DAMAGE_SCALE: 0
    LIFE_ALT_ATK: 0.0
    LIFE_ALT_DEF: 0.0
    LIFE_ALT_HP: 0.0
    LIFE_ALT_HP_MAX: 0.0
    LIFE_COLD_ATK: 1
    LIFE_COLD_DEF: 1
    LIFE_COLD_HP: 0
    LIFE_COLD_HP_MAX: 0.0
    LIFE_HOT_ATK: 1
    LIFE_HOT_DEF: 1
    LIFE_HOT_HP: 0
    LIFE_HOT_HP_MAX: 0.0
    LIFE_MIND_ATK: 1
    LIFE_MIND_DEF: 1
    LIFE_MIND_HP: 0
    LIFE_MIND_HP_MAX: 0.0
    LIFE_SWIM_ATK: 0.0
    LIFE_SWIM_DEF: 0.0
    LIFE_SWIM_HP: 0.0
    LIFE_SWIM_HP_MAX: 0.0
    LIFE_TOXIC_ATK: 1
    LIFE_TOXIC_DEF: 1
    LIFE_TOXIC_HP: 0
    LIFE_TOXIC_HP_MAX: 0.0
    LIFE_WET_ATK: 0.0
    LIFE_WET_DEF: 0.0
    LIFE_WET_HP: 0.0
    LIFE_WET_HP_MAX: 0.0
    LIUMAO_DAMAGE_SCALE: 0
    LZ_BODY: 0
    LZ_BODY_MAX: 1
    LZ_DETECT_1: 2
    LZ_DETECT_2: 2
    LZ_DETECT_3: 2
    LZ_DETECT_4: 2
    LZ_HP_DOCTOR: 0
    LZ_HP_MAX_DOCTOR: 3
    LZ_M_DEF_DOCTOR: 5
    LZ_M_DMG_DOCTOR: 3
    LZ_P_DEF_DOCTOR: 5
    LZ_P_DMG_DOCTOR: 3
    LZ_TREAT_1: 2
    LZ_TREAT_2: 2
    LZ_TREAT_3: 2
    LZ_TREAT_4: 0.0
    MACHINE_HP: 0.0
    MAX_N_ATK: 0.0
    MAX_PRO_ATK_A: 1
    MAX_PRO_ATK_B: 1
    MAX_PRO_ATK_C: 1
    MAX_PRO_ATK_D: 1
    MAX_PRO_ATK_E: 1
    MAX_W_ATK: 5.52
    MIN_N_ATK: 0.0
    MIN_PRO_ATK_A: 1
    MIN_PRO_ATK_B: 1
    MIN_PRO_ATK_C: 1
    MIN_PRO_ATK_D: 1
    MIN_PRO_ATK_E: 1
    MIN_W_ATK: 3.24
    MODAO_DAMAGE_SCALE: 0
    MOVE_JOYSTICK_TYPE: 0
    N_ATK: 0.0
    N_ATK_CRI_UP: 0.0
    N_ATK_CRI_UP_RDC: 0.0
    N_ATK_DEF_MAX: 0.0
    N_ATK_IGR: 0.0
    N_ATK_IGR_RDC: 0.0
    N_ATK_PEN: 0.0
    N_ATK_PEN_MAX: 0.0
    N_ATK_PEN_RDC: 0.0
    N_ATK_SCALE: 0.0
    N_DEF: 0.0
    N_DEF_SCALE: 0.0
    N_HEAL: 0.0
    N_HEAL_RDC_SCALE: 0.0
    N_HEAL_SCALE: 0.0
    ORG_XIUWEI_KUNGFU: 0
    POKONG_DAMAGE_SCALE: 0
    PRO_ATK_A_SCALE: 1
    PRO_ATK_B_SCALE: 1
    PRO_ATK_CRI_UP: 1
    PRO_ATK_CRI_UP_RDC: 1
    PRO_ATK_C_SCALE: 1
    PRO_ATK_D_SCALE: 1
    PRO_ATK_E_SCALE: 1
    PRO_ATK_H: 0.0
    PRO_DEF_A: 1
    PRO_DEF_A_SCALE: 1
    PRO_DEF_B: 1
    PRO_DEF_B_SCALE: 1
    PRO_DEF_C: 1
    PRO_DEF_C_SCALE: 1
    PRO_DEF_D: 1
    PRO_DEF_D_SCALE: 1
    PRO_DEF_E: 1
    PRO_DEF_E_SCALE: 1
    PRO_HEAL_SCALE: 1
    PRO_PEN_A: 1
    PRO_PEN_B: 1
    PRO_PEN_C: 1
    PRO_PEN_D: 1
    PRO_PEN_E: 1
    PRO_PEN_H: 0.0
    QIANG_DAMAGE_SCALE: 0
    QIJUE_DAMAGE_SCALE: 0
    QIJUE_REDUCE: 0
    QING_DAMAGE_SCALE: 0
    QINHEJING_DAMAGE_SCALE: 0
    QINHEJING_REDUCE: 0
    QINHESHOU_DAMAGE_SCALE: 0
    QINHESHOU_REDUCE: 0
    QINHEXIAO_DAMAGE_SCALE: 0
    QINHEXIAO_REDUCE: 0
    QISHEN_DAMAGE_SCALE: 0
    SAN_DAMAGE_SCALE: 0
    SHAN_DAMAGE_SCALE: 0
    SHAN_TREATE_SCALE: 0
    SHENLONG_DAMAGE_SCALE: 0
    SHIHOU_DAMAGE_SCALE: 0
    SHUANGDAO_DAMAGE_SCALE: 0
    SKILL_BAFANG_ADD: 0
    SKILL_BAILU_ADD: 0
    SKILL_BUXIE_ADD: 0
    SKILL_CAIFENG_ADD: 0
    SKILL_CHAOYU_ADD: 0
    SKILL_CHUNJIN_ADD: 0
    SKILL_CHUWEI_ADD: 0
    SKILL_CIER_ADD: 0
    SKILL_CISAN_ADD: 0
    SKILL_DUANPENG_ADD: 0
    SKILL_FENGLEIXIAO_ADD: 0
    SKILL_HENGSAO_ADD: 0
    SKILL_KONGSHAN_ADD: 0
    SKILL_MINGYUE_ADD: 0
    SKILL_MODAOXU_ADD: 0
    SKILL_MODAOZHU_ADD: 0
    SKILL_NEIYI_ADD: 0
    SKILL_QIANGXU_ADD: 0
    SKILL_QIANGZHU_ADD: 0
    SKILL_QIANSHI_ADD: 0
    SKILL_QINGTIAN_ADD: 0
    SKILL_SHIHENG_ADD: 0
    SKILL_SHUANGKONG_ADD: 0
    SKILL_SHUANGNU_ADD: 0
    SKILL_SHUANGSHANG_ADD: 0
    SKILL_SUZI_TSJ_ADD: 0
    SKILL_SUZI_WXJ_ADD: 0
    SKILL_SUZI_XLJ_ADD: 0
    SKILL_TUIYI_ADD: 0
    SKILL_WENSHI_ADD: 0
    SKILL_WUYI_ADD: 0
    SKILL_XINGHUA_ADD: 0
    SKILL_YINIAN_ADD: 0
    SKILL_ZHIXUN_ADD: 0
    SKILL_ZUOKAN_ADD: 0
    SKLL_TIAOQIANG_ADD: 0
    STATE_LEVEL_EXPLORE: 1
    STATE_LEVEL_KUNGFU: 1
    STATE_LEVEL_TRADE: 1
    STATE_LEVEL_TRADE1: 1
    STATE_LEVEL_TRADE2: 1
    STATE_LEVEL_TRADE3: 1
    STATE_LEVEL_TRADE4: 1
    STATE_LEVEL_TRADE5: 1
    TAIBAI_DAMAGE_SCALE: 0
    TIAOYIN_JINGYAN_ADD: 0.0
    TIAOYIN_MAX_ADD: 0.0
    TIAO_DAMAGE_SCALE: 0
    TOTAL_PRO_ATK_MAX: 0.0
    TOTAL_PRO_ATK_MIN: 0.0
    TU_DAMAGE_SCALE: 0
    WEAK_DMGUP_RATE: 1
    WEITUO_DAMAGE_SCALE: 0
    W_ATK: 0.0
    W_ATK_CRI_UP: 1
    W_ATK_CRI_UP_RDC: 1
    W_ATK_IGR: 0.0
    W_ATK_IGR_RDC: 0.0
    W_ATK_PEN: 1
    W_ATK_PEN_RDC: 1
    W_ATK_SCALE: 1
    W_DEF: 2.14
    W_DEF_SCALE: 1
    W_HEAL_RDC_SCALE: 1
    W_HEAL_SCALE: 1
    XIAOFENG_DAMAGE_SCALE: 0
    XIUWEI_EXPLORE: 1016
    XIUWEI_KUNGFU: -1834
    XIUWEI_TRADE: 0
    XIUWEI_TRADE1: 0
    XIUWEI_TRADE2: 0
    XIUWEI_TRADE3: 0
    XIUWEI_TRADE4: 0
    XIUWEI_TRADE5: 0
    XUEWEI_ATK: 1
    XUEWEI_A_DEF: 1
    XUEWEI_B_DEF: 1
    XUEWEI_C_DEF: 1
    XUEWEI_D_DEF: 1
    XUEWEI_E_DEF: 1
    YINZHUA_DAMAGE_SCALE: 0
    YITU_DAMAGE_SCALE: 0
    YIWU_DAMAGE_SCALE: 0
    YS_BUILD_1: 1
    YS_BUILD_2: 1
    YS_BUILD_3: 1
    YS_BUILD_DEF_1: 2
    YS_BUILD_DEF_2: 2
    YS_BUILD_HP: 2
    YS_MACHINE_ATK_1: 2
    YS_MACHINE_ATK_2: 3
    YS_MACHINE_ATK_LOSS: 0.0
    YS_REAL_ATK: 0.0
    YS_REAL_HP: 0.0
    ZHENQI_DAMAGE: 0
    ZHENQI_DEF: 0
    ZHENQI_REPLY: 0
    ZHONG_DAMAGE_SCALE: 0
    ZY_DMG_SUPPORT: 1
    ZY_DRAW_1: 1
    ZY_DRAW_2: 1
    ZY_DRAW_3: 1
    ZY_DRAW_4: 1
    ZY_HP_GOUZAI: 0
    ZY_HP_GOUZAI_MAX: 2
    ZY_MP_SCHEME: 2
    ZY_MP_SUSPECT: 1
    ZY_P_ATK_1: 2
    ZY_P_ATK_2: 2
    ZY_P_DEF_FAKE: 1
    __packed_data__: ""
    cr_refreshing: class {
      -- Metatable:
      --   __tostring: yes
      __property_all__: <dict>
      __property_flag__: <dict>
      __property_index__: <instance>
      _initProperty: function(arg1, arg2)  -- @engine/common/classutils.lua:310-330
    }
    dynamic_attr: class {
      -- Metatable:
      --   __tostring: yes
      __property_all__: <dict>
      __property_flag__: <dict>
      __property_index__: <instance>
      _initProperty: function(arg1, arg2)  -- @engine/common/classutils.lua:310-330
    }
    humanpro: class {
      -- Metatable:
      --   __tostring: yes
      __property_all__: <dict>
      __property_flag__: <dict>
      __property_index__: <instance>
      _initProperty: function(arg1, arg2)  -- @engine/common/classutils.lua:310-330
    }
    res_recover_ts: class {
      -- Metatable:
      --   __tostring: yes
      __property_all__: <dict>
      __property_flag__: <dict>
      __property_index__: <instance>
      _initProperty: function(arg1, arg2)  -- @engine/common/classutils.lua:310-330
    }
    resource_empty: class {
      -- Metatable:
      --   __tostring: yes
      IS_CUSTOM_TYPE: true
      __len: nil
      __metaclass__: function(arg1)  -- @engine/common/classutils.lua:592-594
      __property_all__: <dict>
      __property_flag__: <dict>
      __property_index__: <instance>
      _initProperty: function(arg1, arg2)  -- @engine/common/classutils.lua:286-308
      ctor: function(arg1, arg2)  -- @engine/common/classutils.lua:612-621
      items: function(arg1)  -- @engine/common/classutils.lua:655-661
      keys: function(arg1)  -- @engine/common/classutils.lua:639-645
      on_assign: function(arg1)  -- @engine/common/classutils.lua:632-633
      on_clear: function(arg1)  -- @engine/common/classutils.lua:626-627
      on_init: function(arg1, arg2)  -- @engine/common/classutils.lua:623-624
      on_setattr: function(arg1, arg2, arg3, arg4)  -- @engine/common/classutils.lua:636-637
      on_update: function(arg1, arg2)  -- @engine/common/classutils.lua:629-630
      setdefault: function(arg1, arg2, arg3)  -- @engine/common/classutils.lua:663-670
      to_valid_dict: function(arg1)  -- @engine/common/classutils.lua:672-709
      values: function(arg1)  -- @engine/common/classutils.lua:647-653
    }
    resource_id_map: <circular>
    salt: 0
  }
  __property_flag__: instance {
    -- Metatable:
    --   __index: table
    --   __tostring: yes
    ABR_AVOID_PROB: 4
    ACR_PROB: 4
    ADD_ACR_PROB: 4
    ADD_ACR_RESIST_PROB: 4
    ADD_BASH_PROB: 4
    ADD_BASH_RESIST_PROB: 4
    ADD_CRI_PROB: 4
    ADD_CRI_RESIST_PROB: 4
    ALL_DAMAGE_SCALE: 4
    ALL_ONELEVEL_ATTR: 4
    ARCHER_AIM_RANGE: 4
    ARCHER_ARROW_DISTANCE: 4
    ARCHER_ARROW_SPEED: 4
    ARCHER_DAMAGE: 4
    ARCHER_DAMAGE_SCALE: 4
    ARCHER_FIRE_RESOURCE: 4
    ARCHER_FLY_SPEED: 4
    ARCHER_LOOP_TIME: 4
    ARCHER_POISIN_RESOURCE: 4
    ARCHER_SHOOT_SPEED: 4
    ARCHER_TIMESTOP_COST: 4
    ARCHER_TIMESTOP_EFFECT: 4
    ARCHER_TIMESTOP_TIME: 4
    ARCHER_WEAKPOINT_DAMAGE: 4
    ARCHER_WEAKPOINT_DAMAGE_SCALE: 4
    BAINIAO_DAMAGE_SCALE: 4
    BASH_PROB: 4
    BASH_UP: 4
    BASH_UP_RDC: 4
    BODY_STRENGTH_1: 4
    BODY_STRENGTH_2: 4
    BODY_STRENGTH_3: 4
    BODY_STRENGTH_4: 4
    CHU_DAMAGE_SCALE: 4
    CRI_PROB: 4
    CS_ITS: 4
    DAMAGE_REDUCE: 4
    DAOLANG_DAMAGE_SCALE: 4
    DIRECT_BASH_PROB: 4
    DIRECT_CRI_PROB: 4
    GP_BEHIT_DMG_IND: 4
    GP_DIR: 4
    GP_DMG_IND: 4
    GP_REAL_DMG_IND: 4
    HEAL_CRI_UP: 4
    HONGCHEN_DAMAGE_SCALE: 4
    HP: 12
    HP_MAX: 12
    HS_ATK_RATE: 4
    HS_BIANSHI: 4
    HS_BUXIE: 4
    HS_BUXIE_ATK: 4
    HS_BUXIE_DEF: 4
    HS_BUXIE_MAX: 4
    HS_CAIHUA: 4
    HS_CAIHUA_ATK: 4
    HS_CAIHUA_DEF: 4
    HS_CAIHUA_MAX: 4
    HS_CONGHUI: 4
    HS_CONGHUI_ATK: 4
    HS_CONGHUI_DEF: 4
    HS_CONGHUI_MAX: 4
    HS_CRI_A: 4
    HS_CRI_A_DEF: 4
    HS_CRI_A_rate: 4
    HS_CRI_A_reduce_rate: 4
    HS_CRI_B: 4
    HS_CRI_B_DEF: 4
    HS_CRI_B_rate: 4
    HS_CRI_B_reduce_rate: 4
    HS_KONGCHANG: 4
    HS_KOUCAI: 4
    HS_SIKAO: 4
    HS_ZIXIN: 4
    HS_ZIXIN_ATK: 4
    HS_ZIXIN_DEF: 4
    HS_ZIXIN_MAX: 4
    JIAN_DAMAGE_SCALE: 4
    JINCHAN_DAMAGE_SCALE: 4
    KAIFENGJING_DAMAGE_SCALE: 4
    KAIFENGJING_REDUCE: 4
    KAIFENGSHOU_DAMAGE_SCALE: 4
    KAIFENGSHOU_REDUCE: 4
    KAIFENGXIAO_DAMAGE_SCALE: 4
    KAIFENGXIAO_REDUCE: 4
    KONG_DAMAGE_SCALE: 4
    LIANREN_DAMAGE_SCALE: 4
    LIFE_ALT_ATK: 1
    LIFE_ALT_DEF: 1
    LIFE_ALT_HP: 1
    LIFE_ALT_HP_MAX: 1
    LIFE_COLD_ATK: 1
    LIFE_COLD_DEF: 4
    LIFE_COLD_HP: 1
    LIFE_COLD_HP_MAX: 1
    LIFE_HOT_ATK: 1
    LIFE_HOT_DEF: 4
    LIFE_HOT_HP: 1
    LIFE_HOT_HP_MAX: 1
    LIFE_MIND_ATK: 1
    LIFE_MIND_DEF: 4
    LIFE_MIND_HP: 1
    LIFE_MIND_HP_MAX: 1
    LIFE_SWIM_ATK: 1
    LIFE_SWIM_DEF: 1
    LIFE_SWIM_HP: 1
    LIFE_SWIM_HP_MAX: 1
    LIFE_TOXIC_ATK: 1
    LIFE_TOXIC_DEF: 4
    LIFE_TOXIC_HP: 1
    LIFE_TOXIC_HP_MAX: 1
    LIFE_WET_ATK: 1
    LIFE_WET_DEF: 1
    LIFE_WET_HP: 1
    LIFE_WET_HP_MAX: 1
    LIUMAO_DAMAGE_SCALE: 4
    LZ_BODY: 4
    LZ_BODY_MAX: 4
    LZ_DETECT_1: 4
    LZ_DETECT_2: 4
    LZ_DETECT_3: 4
    LZ_DETECT_4: 4
    LZ_HP_DOCTOR: 4
    LZ_HP_MAX_DOCTOR: 4
    LZ_M_DEF_DOCTOR: 4
    LZ_M_DMG_DOCTOR: 4
    LZ_P_DEF_DOCTOR: 4
    LZ_P_DMG_DOCTOR: 4
    LZ_TREAT_1: 4
    LZ_TREAT_2: 4
    LZ_TREAT_3: 4
    LZ_TREAT_4: 4
    MACHINE_HP: 4
    MAX_N_ATK: 4
    MAX_PRO_ATK_A: 4
    MAX_PRO_ATK_B: 4
    MAX_PRO_ATK_C: 4
    MAX_PRO_ATK_D: 4
    MAX_PRO_ATK_E: 4
    MAX_W_ATK: 4
    MIN_N_ATK: 4
    MIN_PRO_ATK_A: 4
    MIN_PRO_ATK_B: 4
    MIN_PRO_ATK_C: 4
    MIN_PRO_ATK_D: 4
    MIN_PRO_ATK_E: 4
    MIN_W_ATK: 4
    MODAO_DAMAGE_SCALE: 4
    MOVE_JOYSTICK_TYPE: 4
    N_ATK: 4
    N_ATK_CRI_UP: 4
    N_ATK_CRI_UP_RDC: 4
    N_ATK_DEF_MAX: 4
    N_ATK_IGR: 4
    N_ATK_IGR_RDC: 4
    N_ATK_PEN: 4
    N_ATK_PEN_MAX: 4
    N_ATK_PEN_RDC: 4
    N_ATK_SCALE: 4
    N_DEF: 4
    N_DEF_SCALE: 4
    N_HEAL: 4
    N_HEAL_RDC_SCALE: 4
    N_HEAL_SCALE: 4
    ORG_XIUWEI_KUNGFU: 4
    POKONG_DAMAGE_SCALE: 4
    PRO_ATK_A_SCALE: 4
    PRO_ATK_B_SCALE: 4
    PRO_ATK_CRI_UP: 4
    PRO_ATK_CRI_UP_RDC: 4
    PRO_ATK_C_SCALE: 4
    PRO_ATK_D_SCALE: 4
    PRO_ATK_E_SCALE: 4
    PRO_ATK_H: 4
    PRO_DEF_A: 4
    PRO_DEF_A_SCALE: 4
    PRO_DEF_B: 4
    PRO_DEF_B_SCALE: 4
    PRO_DEF_C: 4
    PRO_DEF_C_SCALE: 4
    PRO_DEF_D: 4
    PRO_DEF_D_SCALE: 4
    PRO_DEF_E: 4
    PRO_DEF_E_SCALE: 4
    PRO_HEAL_SCALE: 4
    PRO_PEN_A: 4
    PRO_PEN_B: 4
    PRO_PEN_C: 4
    PRO_PEN_D: 4
    PRO_PEN_E: 4
    PRO_PEN_H: 4
    QIANG_DAMAGE_SCALE: 4
    QIJUE_DAMAGE_SCALE: 4
    QIJUE_REDUCE: 4
    QING_DAMAGE_SCALE: 4
    QINHEJING_DAMAGE_SCALE: 4
    QINHEJING_REDUCE: 4
    QINHESHOU_DAMAGE_SCALE: 4
    QINHESHOU_REDUCE: 4
    QINHEXIAO_DAMAGE_SCALE: 4
    QINHEXIAO_REDUCE: 4
    QISHEN_DAMAGE_SCALE: 4
    SAN_DAMAGE_SCALE: 4
    SHAN_DAMAGE_SCALE: 4
    SHAN_TREATE_SCALE: 4
    SHENLONG_DAMAGE_SCALE: 4
    SHIHOU_DAMAGE_SCALE: 4
    SHUANGDAO_DAMAGE_SCALE: 4
    SKILL_BAFANG_ADD: 4
    SKILL_BAILU_ADD: 4
    SKILL_BUXIE_ADD: 4
    SKILL_CAIFENG_ADD: 4
    SKILL_CHAOYU_ADD: 4
    SKILL_CHUNJIN_ADD: 4
    SKILL_CHUWEI_ADD: 4
    SKILL_CIER_ADD: 4
    SKILL_CISAN_ADD: 4
    SKILL_DUANPENG_ADD: 4
    SKILL_FENGLEIXIAO_ADD: 4
    SKILL_HENGSAO_ADD: 4
    SKILL_KONGSHAN_ADD: 4
    SKILL_MINGYUE_ADD: 4
    SKILL_MODAOXU_ADD: 4
    SKILL_MODAOZHU_ADD: 4
    SKILL_NEIYI_ADD: 4
    SKILL_QIANGXU_ADD: 4
    SKILL_QIANGZHU_ADD: 4
    SKILL_QIANSHI_ADD: 4
    SKILL_QINGTIAN_ADD: 4
    SKILL_SHIHENG_ADD: 4
    SKILL_SHUANGKONG_ADD: 4
    SKILL_SHUANGNU_ADD: 4
    SKILL_SHUANGSHANG_ADD: 4
    SKILL_SUZI_TSJ_ADD: 4
    SKILL_SUZI_WXJ_ADD: 4
    SKILL_SUZI_XLJ_ADD: 4
    SKILL_TUIYI_ADD: 4
    SKILL_WENSHI_ADD: 4
    SKILL_WUYI_ADD: 4
    SKILL_XINGHUA_ADD: 4
    SKILL_YINIAN_ADD: 4
    SKILL_ZHIXUN_ADD: 4
    SKILL_ZUOKAN_ADD: 4
    SKLL_TIAOQIANG_ADD: 4
    STATE_LEVEL_EXPLORE: 10
    STATE_LEVEL_KUNGFU: 10
    STATE_LEVEL_TRADE: 10
    STATE_LEVEL_TRADE1: 10
    STATE_LEVEL_TRADE2: 10
    STATE_LEVEL_TRADE3: 10
    STATE_LEVEL_TRADE4: 10
    STATE_LEVEL_TRADE5: 10
    TAIBAI_DAMAGE_SCALE: 4
    TIAOYIN_JINGYAN_ADD: 4
    TIAOYIN_MAX_ADD: 4
    TIAO_DAMAGE_SCALE: 4
    TOTAL_PRO_ATK_MAX: 4
    TOTAL_PRO_ATK_MIN: 4
    TU_DAMAGE_SCALE: 4
    WEAK_DMGUP_RATE: 4
    WEITUO_DAMAGE_SCALE: 4
    W_ATK: 4
    W_ATK_CRI_UP: 4
    W_ATK_CRI_UP_RDC: 4
    W_ATK_IGR: 4
    W_ATK_IGR_RDC: 4
    W_ATK_PEN: 4
    W_ATK_PEN_RDC: 4
    W_ATK_SCALE: 4
    W_DEF: 4
    W_DEF_SCALE: 4
    W_HEAL_RDC_SCALE: 4
    W_HEAL_SCALE: 4
    XIAOFENG_DAMAGE_SCALE: 4
    XIUWEI_EXPLORE: 10
    XIUWEI_KUNGFU: 10
    XIUWEI_TRADE: 10
    XIUWEI_TRADE1: 10
    XIUWEI_TRADE2: 10
    XIUWEI_TRADE3: 10
    XIUWEI_TRADE4: 10
    XIUWEI_TRADE5: 10
    XUEWEI_ATK: 4
    XUEWEI_A_DEF: 4
    XUEWEI_B_DEF: 4
    XUEWEI_C_DEF: 4
    XUEWEI_D_DEF: 4
    XUEWEI_E_DEF: 4
    YINZHUA_DAMAGE_SCALE: 4
    YITU_DAMAGE_SCALE: 4
    YIWU_DAMAGE_SCALE: 4
    YS_BUILD_1: 4
    YS_BUILD_2: 4
    YS_BUILD_3: 4
    YS_BUILD_DEF_1: 4
    YS_BUILD_DEF_2: 4
    YS_BUILD_HP: 4
    YS_MACHINE_ATK_1: 4
    YS_MACHINE_ATK_2: 4
    YS_MACHINE_ATK_LOSS: 4
    YS_REAL_ATK: 4
    YS_REAL_HP: 4
    ZHENQI_DAMAGE: 4
    ZHENQI_DEF: 4
    ZHENQI_REPLY: 4
    ZHONG_DAMAGE_SCALE: 4
    ZY_DMG_SUPPORT: 4
    ZY_DRAW_1: 4
    ZY_DRAW_2: 4
    ZY_DRAW_3: 4
    ZY_DRAW_4: 4
    ZY_HP_GOUZAI: 4
    ZY_HP_GOUZAI_MAX: 4
    ZY_MP_SCHEME: 4
    ZY_MP_SUSPECT: 4
    ZY_P_ATK_1: 4
    ZY_P_ATK_2: 4
    ZY_P_DEF_FAKE: 4
    __packed_data__: 1
    cr_refreshing: 4
    dynamic_attr: 12
    humanpro: 4
    res_recover_ts: 4
    resource_empty: 4
    resource_id_map: 12
    salt: 4
  }
  __property_index__: <instance>
  _initProperty: function(arg1, arg2)  -- @engine/common/classutils.lua:310-330
  on_setattr: function(arg1, arg2, arg3, arg4)  -- @hexm/common/property_define/common_prop/attr_base.lua:48-57
}


-- End of hexm.common.property_define.ai_avatar.attr