-- ======================================================================
-- Module: hexm.common.consts.bot_consts
-- Source: package.loaded
-- Type: table
-- Order: #5167
-- ======================================================================

-- Module type: table

BTREE_NONE: "none"

DUNGEON_BOT: 1

E_BOT_DUNGEON_ARBIT_TO_COMPLEX_KILLBOSS: 4021

E_BOT_DUNGEON_ARBIT_TO_GOTRAP: 4022

E_BOT_DUNGEON_ARBIT_TO_KILLMONSTER: 4019

E_BOT_DUNGEON_ARBIT_TO_NAVI: 4018

E_BOT_DUNGEON_ARBIT_TO_SIMPLE_KILLBOSS: 4020

E_BOT_DUNGEON_ARBIT_TO_STOP: 4017

E_BOT_DUNGEON_TO_ARBIT: 4023

E_BOT_END_FIGHT: 4003

E_BOT_FIGHT: 4002

E_BOT_FOLLOW_FOLLOW_ARBIT_TO_CC: 4011

E_BOT_FOLLOW_FOLLOW_ARBIT_TO_CU: 4010

E_BOT_FOLLOW_FOLLOW_ARBIT_TO_UC: 4009

E_BOT_FOLLOW_FOLLOW_ARBIT_TO_UU: 4008

E_BOT_FOLLOW_FOLLOW_TO_NAVI_DIFF_SCENE: 4014

E_BOT_FOLLOW_FOLLOW_TO_NAVI_SAME_SCENE_CANT_TRANSMIT: 4013

E_BOT_FOLLOW_FOLLOW_TO_NAVI_SAME_SCENE_CAN_TRANSMIT: 4012

E_BOT_FOLLOW_FOLLOW_TO_TRANSMIT: 4015

E_BOT_FOLLOW_STATE_ARBIT_TO_FIGHT: 4007

E_BOT_FOLLOW_STATE_ARBIT_TO_FOLLOW: 4006

E_BOT_FOLLOW_STATE_TO_ARBITER: 4016

E_BOT_LEVEL_BOT_TO_COMMON: 4029

E_BOT_LEVEL_BOT_TO_FIGHT: 4030

E_BOT_NAVIGATE: 4001

E_BOT_QUERY_ENTITY_POS: 4005

E_BOT_QUERY_TEAM_LEADER_STATE_DATA: 4004

E_BOT_TASK_ARBIT_TO_INTERACT: 4026

E_BOT_TASK_ARBIT_TO_NAVI: 4025

E_BOT_TASK_ARBIT_TO_STOP: 4024

E_BOT_TASK_TO_ARBIT: 4027

E_BOT_TASK_TO_STOP: 4028

FOLLOW_BOT: 3

LEVEL_BOT: 5

NO_BOT: 0

SERVER_FOLLOW_BOT: 4

TASK_BOT: 2

bot_events: instance {
  -- Metatable:
  --   __index: table
  --   __tostring: yes
  E_BOT_DUNGEON_ARBIT_TO_COMPLEX_KILLBOSS: 4021
  E_BOT_DUNGEON_ARBIT_TO_GOTRAP: 4022
  E_BOT_DUNGEON_ARBIT_TO_KILLMONSTER: 4019
  E_BOT_DUNGEON_ARBIT_TO_NAVI: 4018
  E_BOT_DUNGEON_ARBIT_TO_SIMPLE_KILLBOSS: 4020
  E_BOT_DUNGEON_ARBIT_TO_STOP: 4017
  E_BOT_DUNGEON_TO_ARBIT: 4023
  E_BOT_END_FIGHT: 4003
  E_BOT_FIGHT: 4002
  E_BOT_FOLLOW_FOLLOW_ARBIT_TO_CC: 4011
  E_BOT_FOLLOW_FOLLOW_ARBIT_TO_CU: 4010
  E_BOT_FOLLOW_FOLLOW_ARBIT_TO_UC: 4009
  E_BOT_FOLLOW_FOLLOW_ARBIT_TO_UU: 4008
  E_BOT_FOLLOW_FOLLOW_TO_NAVI_DIFF_SCENE: 4014
  E_BOT_FOLLOW_FOLLOW_TO_NAVI_SAME_SCENE_CANT_TRANSMIT: 4013
  E_BOT_FOLLOW_FOLLOW_TO_NAVI_SAME_SCENE_CAN_TRANSMIT: 4012
  E_BOT_FOLLOW_FOLLOW_TO_TRANSMIT: 4015
  E_BOT_FOLLOW_STATE_ARBIT_TO_FIGHT: 4007
  E_BOT_FOLLOW_STATE_ARBIT_TO_FOLLOW: 4006
  E_BOT_FOLLOW_STATE_TO_ARBITER: 4016
  E_BOT_LEVEL_BOT_TO_COMMON: 4029
  E_BOT_LEVEL_BOT_TO_FIGHT: 4030
  E_BOT_NAVIGATE: 4001
  E_BOT_QUERY_ENTITY_POS: 4005
  E_BOT_QUERY_TEAM_LEADER_STATE_DATA: 4004
  E_BOT_TASK_ARBIT_TO_INTERACT: 4026
  E_BOT_TASK_ARBIT_TO_NAVI: 4025
  E_BOT_TASK_ARBIT_TO_STOP: 4024
  E_BOT_TASK_TO_ARBIT: 4027
  E_BOT_TASK_TO_STOP: 4028
}

bot_events_reverse: instance {
  -- Metatable:
  --   __index: table
  --   __tostring: yes
  4001: "E_BOT_NAVIGATE"
  4002: "E_BOT_FIGHT"
  4003: "E_BOT_END_FIGHT"
  4004: "E_BOT_QUERY_TEAM_LEADER_STATE_DATA"
  4005: "E_BOT_QUERY_ENTITY_POS"
  4006: "E_BOT_FOLLOW_STATE_ARBIT_TO_FOLLOW"
  4007: "E_BOT_FOLLOW_STATE_ARBIT_TO_FIGHT"
  4008: "E_BOT_FOLLOW_FOLLOW_ARBIT_TO_UU"
  4009: "E_BOT_FOLLOW_FOLLOW_ARBIT_TO_UC"
  4010: "E_BOT_FOLLOW_FOLLOW_ARBIT_TO_CU"
  4011: "E_BOT_FOLLOW_FOLLOW_ARBIT_TO_CC"
  4012: "E_BOT_FOLLOW_FOLLOW_TO_NAVI_SAME_SCENE_CAN_TRANSMIT"
  4013: "E_BOT_FOLLOW_FOLLOW_TO_NAVI_SAME_SCENE_CANT_TRANSMIT"
  4014: "E_BOT_FOLLOW_FOLLOW_TO_NAVI_DIFF_SCENE"
  4015: "E_BOT_FOLLOW_FOLLOW_TO_TRANSMIT"
  4016: "E_BOT_FOLLOW_STATE_TO_ARBITER"
  4017: "E_BOT_DUNGEON_ARBIT_TO_STOP"
  4018: "E_BOT_DUNGEON_ARBIT_TO_NAVI"
  4019: "E_BOT_DUNGEON_ARBIT_TO_KILLMONSTER"
  4020: "E_BOT_DUNGEON_ARBIT_TO_SIMPLE_KILLBOSS"
  4021: "E_BOT_DUNGEON_ARBIT_TO_COMPLEX_KILLBOSS"
  4022: "E_BOT_DUNGEON_ARBIT_TO_GOTRAP"
  4023: "E_BOT_DUNGEON_TO_ARBIT"
  4024: "E_BOT_TASK_ARBIT_TO_STOP"
  4025: "E_BOT_TASK_ARBIT_TO_NAVI"
  4026: "E_BOT_TASK_ARBIT_TO_INTERACT"
  4027: "E_BOT_TASK_TO_ARBIT"
  4028: "E_BOT_TASK_TO_STOP"
  4029: "E_BOT_LEVEL_BOT_TO_COMMON"
  4030: "E_BOT_LEVEL_BOT_TO_FIGHT"
}


-- End of hexm.common.consts.bot_consts