-- ======================================================================
-- Module: hexm.common.consts.common_building_consts
-- Source: package.loaded
-- Type: table
-- Order: #6448
-- ======================================================================

-- Module type: table

ACCESS_BLUEPRINT_ADD: 5

ACCESS_BLUEPRINT_AUTO_BUILD: 7

ACCESS_BLUEPRINT_COMP_FILL: 3

ACCESS_BLUEPRINT_COMP_UNFILL: 4

ACCESS_BLUEPRINT_COMP_UNFILL_OTHER: 15

ACCESS_BLUEPRINT_COMP_UNFILL_SELF: 14

ACCESS_BLUEPRINT_DEL: 6

ACCESS_BLUEPRINT_DEL_OTHER: 13

ACCESS_BLUEPRINT_DEL_SELF: 12

ACCESS_ENTER_DELETE_MODE: 9

ACCESS_FREE_BUILDING_ADD: 1

ACCESS_FREE_BUILDING_DEL: 2

ACCESS_FREE_BUILDING_DEL_OTHER: 11

ACCESS_FREE_BUILDING_DEL_SELF: 10

ACCESS_FREE_CAMERA: 8

AREA_LIMIT: 3

BLUEPRINT_PREVIEW_SPACE: 5005

BLUEPRINT_SPACE: 5001

BP_BUILD_FINISH_TXT: 130355

BP_CHUNK_FIELDS: instance {
  -- Metatable:
  --   __index: table
  --   __tostring: yes
  ex: 1
  ts: 1
}

BP_COMPS_SAVE_NUM_LIMIT: 500

BP_SAVE_TIME_GAP: 10

BP_UPDATE_FIELDS: instance {
  -- Metatable:
  --   __index: table
  --   __tostring: yes
  design_size: 1
  ex: 1
  name: 1
  state: 1
}

BUILD_ADD_GADGET_LIMIT: 100

BUILD_GAD_NUM: 5

BUILD_LV_LIMIT: 5

CLUB_COMPS_NUM_LIMIT: 8000

COMPS_FRAME_LIMIT: 1000

COMPS_SAVE_NUM_LIMIT: 300

DELAY_LOAD: 3

DT_AREA_RENEW: 10

ENTER_MODE_EDIT: 1

ENTER_MODE_NEW_CREATE: 0

ENTER_MODE_VIEW: 2

ERR_AREA_BE_TAKEN: 131588

ERR_AREA_EXPIRED: 676078

ERR_AREA_LIMIT: 131578

ERR_AREA_NUM_LIMIT: 101879

ERR_AREA_RENEW_NOT_IN_HOMEWOLRD: 101830

ERR_BIG_BP_SPACE_LIMIT: 102015

ERR_BLUEPRINT_SPACE: 101552

ERR_BP_DESIGN_OVER_NUM: 676437

ERR_BP_NUM_LIMIT: 101559

ERR_BUILDING_SPACE: 130213

ERR_BUILD_FENBAO_BAN: 70520

ERR_BUILD_LV_LIMIT: 130367

ERR_BUILD_NUM_LIMIT: 101880

ERR_BUILD_WANFA_IS_BAN: 102017

ERR_CANNOT_BUILD: 101254

ERR_CANNOT_RM_SYS_BP_COMP: 101871

ERR_CANNOT_TO_DESIGN: 102327

ERR_COMP_ALLREADY_IN: 101855

ERR_COMP_NUM_LIMIT: 101878

ERR_DESIGN_NO: 101914

ERR_HAS_BP_COMP: 673132

ERR_HAS_BUILD: 120001

ERR_HAS_BUILD_IN_BUILDING_STATE: 131723

ERR_HAS_COMP: 101557

ERR_HAS_GANG_AREA: 130217

ERR_HAS_NO_SHADOW: 777001

ERR_INDUS_LOCK: 130225

ERR_INDUS_NUM_LIMIT: 130220

ERR_INDUS_REPEAT: 130221

ERR_INS_NOT_READY: 111

ERR_JYT_REPEAT: 131576

ERR_LOCK_COMP: 101562

ERR_LOCK_CORE_BP: 101873

ERR_LOCK_CORE_COMP: 101872

ERR_LOCK_STUFF: 101560

ERR_LOCK_TASK: 101561

ERR_LV_ALREADY: 10026

ERR_LV_LIMIT: 130365

ERR_LV_MAX: 101874

ERR_MAIN_SPACE_AREA_NUM_LIMIT: 102016

ERR_NOT_AREA: 130178

ERR_NOT_AREA_ID: 130215

ERR_NOT_BP: 101554

ERR_NOT_BP_BUILD: 101563

ERR_NOT_BP_STUFF: 777002

ERR_NOT_BUILDING_ENTITY: 130214

ERR_NOT_CLIENT_SPACE: 675521

ERR_NOT_COMP: 101555

ERR_NOT_GADGET: 130223

ERR_NOT_GANG_MASTER: 101564

ERR_NOT_HAS_GANG_AREA: 130218

ERR_NOT_IN_AREA: 130226

ERR_NOT_MAIN_WORLD: 130216

ERR_NOT_SELF_GANG: 130368

ERR_NOT_STUFF: 101556

ERR_NOT_SUB_AREA_ID: 130222

ERR_NO_AREA: 131577

ERR_NO_COMP: 101586

ERR_NO_PAPER: 101553

ERR_NO_PLAYER: 123113

ERR_NO_RIGHT: 674384

ERR_OTHER_SPACE_BAN_BP: 101937

ERR_OTHER_SPACE_BAN_OP: 101947

ERR_PREFAB_HAS_NOT_COMP: 101558

ERR_PRE_INDUS_LOCK: 130224

ERR_WANFA_NOT_UNLOCK: 131589

ESCORT_STATE_BROKEN: 0

ESCORT_STATE_INIT: 1

ESCORT_STATE_PASS: 2

EVENT_ADD_BP_STUFF: "add_bp_stuff"

EVENT_ADD_EDIT_RIGHT: "add_edit_right"

EVENT_BLUEPRINT_ADD_PREFAB_BP_COMP: "bp_build_add_prefab_bp_comp"

EVENT_BLUEPRINT_BAG_DEL: "bp_bag_delete"

EVENT_BLUEPRINT_BUILD: "bp_build"

EVENT_BLUEPRINT_BUILD_BY_CRAFT: "bp_build_by_craft"

EVENT_BLUEPRINT_BUILD_BY_HAND: "bp_build_by_hand"

EVENT_BLUEPRINT_BUILD_PUT: "bp_build_put"

EVENT_BLUEPRINT_BUILD_RECOVER: "bp_build_recover"

EVENT_BLUEPRINT_BUILD_RM: "bp_build_rm"

EVENT_BLUEPRINT_CHANGE_COMP_STATE: "bp_build_change_comp_state"

EVENT_BLUEPRINT_CLEAR: "bp_clear"

EVENT_BLUEPRINT_COMMIT: "bp_commit"

EVENT_BLUEPRINT_ENTER: "bp_space_enter"

EVENT_BLUEPRINT_GO_ON_EDIT: "bp_go_on_edit"

EVENT_BLUEPRINT_INFORM_CHECK: "bp_inform_check"

EVENT_BLUEPRINT_INFORM_result: "bp_inform_result"

EVENT_BLUEPRINT_PREVIEW: "bp_preview"

EVENT_BLUEPRINT_PUT_OUT_PREFAB_BP: "bp_build_put_out_prefab_bp"

EVENT_BLUEPRINT_RM_COMPS: "bp_rm_comps"

EVENT_BLUEPRINT_SAVE: "bp_save"

EVENT_BLUEPRINT_STATE_CHANGE: "bp_state_change"

EVENT_BLUEPRINT_STUFF_COPY_TO_BP: "bp_stuff_copy_tp_bp"

EVENT_BLUEPRINT_TRANS: "bp_trans"

EVENT_BLUEPRINT_UPDATE: "bp_update"

EVENT_BLUEPRINT_VIEW: "bp_view"

EVENT_BLUEPRINT_WHETHER_AGREE_COMMIT: "whether_agree_commit"

EVENT_BP_PREVIEW: "bp_preview"

EVENT_BUILD: 1

EVENT_COOP_MODE_BUILD_PERMISSION_CHANGE: "BuildProp-can_build"

EVENT_GANG_CREATE_AREA: 3

EVENT_GANG_CREATE_AREA_AND_INDUS: 4

EVENT_GANG_CREATE_AREA_CB: 9

EVENT_GANG_CREATE_SUB_AREA: 31

EVENT_GANG_DES_SUB_AREA_BUILDING: 32

EVENT_GANG_FREE_BUILD: 5

EVENT_GANG_GET_AREA_INFO: 6

EVENT_GANG_INDUS_FINISh_CHECK: 8

EVENT_GANG_INDUS_UPGRADE: 7

EVENT_GET_AREA_INFO: 2

EVENT_RM_ALL_EDIT_RIGHT: "rm_all_edit_right"

EVENT_RM_BP_SHADOW: "rm_bp_shadow"

EVENT_RM_BP_STUFF: "rm_bp_stuff"

EVENT_RM_EDIT_RIGHT: "rm_edit_right"

EVENT_SHOW_ALL_RIGHTS: "show_all_rights"

EVENT_SHOW_RIGHT_AVATARS: "show_right_avatars"

GANG_SPACE: 12001

GANG_SPACE_EX: 12003

GANG_XS_BP_DESIGN_NO: 4

GANG_XS_BP_FETCHER: "fetcher"

GANG_XS_BP_PUBLISHER: "publisher"

HOMEWORLD_SPACE: 501

KEY_UNFILLED_COMP_STATUS: "unfilled_comp_status"

LUTOUMEN_TAG: 3

MAIL_NO: 316

MAIN_WORLD_SPACE: 1

MAX_PT_DIS: 150

NO_DEFAULT: 0

NO_GANG_BUILDING: 10

NO_HOMEWORLD_BUILDING: 20

NO_WORLD_BUILDING: 30

OP_GAP: 3

PLAYER_SET: 1

READY_DB_NUM: 2

REASON_AREA_RM: 1009

REASON_BP_DEL_BY_AREA_PRE_INS_NO: 1018

REASON_BROKEN: 1002

REASON_BUILD_DEC_BLOOD: 1008

REASON_BUILD_RM_GADGET: 1010

REASON_CLEAR_ALL_BUILD: 1012

REASON_CLEAR_BY_GK: 1013

REASON_DELETE_BY_INS_NO: 1014

REASON_DEL_SPACE_INS_BUILD: 1006

REASON_DESTROY: 1001

REASON_ESCORT_RESET_PATH: 1004

REASON_FADE: 1003

REASON_GB_RECYCLE: 1017

REASON_NO_BACK_STUFF: instance {
  -- Metatable:
  --   __index: table
  --   __tostring: yes
  1002: 1
  1003: 1
  10003: 1
}

REASON_ON_EXPEDITION_FINISH: 1015

REASON_RECOVER_ALL_BUILD_DATA: 100011

REASON_RPC_RM: 1007

REASON_SPACE_RM_GADGET: 1016

REASON_WANFA_HP: 1005

REASON_WORLD_DESTROY: 10001

REASON_WORLD_FADE: 10003

REASON_WORLD_RM_GADGET: 10016

SHOUBAO_SPACE: 5014

STATES_CAN_FREE_BUILDING: instance {
  -- Metatable:
  --   __index: table
  --   __tostring: yes
  1: 3
  2: 5
}

STATES_NORMAL: instance {
  -- Metatable:
  --   __index: table
  --   __tostring: yes
  1: 2
  2: 3
  3: 5
  4: 6
}

STATE_BUILD: 2

STATE_BUILD_NO_SHADOW: 5

STATE_CRAFT_BUILDING: 7

STATE_DESIGN: 1

STATE_DESIGN_FINISH: 4

STATE_ERROR: 0

STATE_FB_BROKEN: 1

STATE_FB_OK: 0

STATE_FINISH: 3

STATE_PRE_SET: 3

STATE_SHADOW_BAN: 6

SYNC_TIME_GAP: 30

SYS_PRE_SET: 2

TAG_SYS: 1

UNFILLED_COMP_STATUS_DEFAULT: 6

UNFILLED_COMP_STATUS_HIDE_MODEL: 13

_reload_all: true


-- End of hexm.common.consts.common_building_consts