-- ======================================================================
-- Module: hexm.common.consts.cue_consts
-- Source: package.loaded
-- Type: table
-- Order: #4776
-- ======================================================================

-- Module type: table

ANIM_LAYER_SHIELD: 2102

CLIENT_MAIN_PLAYER_TRIGGER_CUE: 3002

CLIENT_TRIGGER_CUE: 3001

CLIENT_TRIGGER_SERVER_SPACE_CUE: 3003

CUE_CINEMA_FINISH: 2078

CUE_COMMON_MOTION_USER_DATA: 2225

CUE_RHAND_ANIM: 365

CUTSCENE_ADD_CLOTH_COL: 2223

CUTSCENE_ADD_FORCE_COLLECT_REGION: 2121

CUTSCENE_ADD_MATERIAL: 2209

CUTSCENE_ADD_SINGLE_PIVOT: 2238

CUTSCENE_APPLY_FACE_DATA: 2215

CUTSCENE_ATTACH_MODEL: 2100

CUTSCENE_BIOMES_ENABLE: 2219

CUTSCENE_CAMERA_SHAKE: 2248

CUTSCENE_CANCEL_SOFT_BONE_FREEZE: 2271

CUTSCENE_CHANGE_BATTLE_MODE: 2073

CUTSCENE_CHANGE_ENV_VOLUME: 2200

CUTSCENE_CHANGE_GUISE: 2125

CUTSCENE_CHANGE_MATERIAL: 2221

CUTSCENE_CHANGE_NPC_AI: 2127

CUTSCENE_CHANGE_SIGHT_REVERSE: 2126

CUTSCENE_CHANGE_STATIC_MODEL_MATERIAL: 2222

CUTSCENE_CHANGE_USER_TAG: 2229

CUTSCENE_CHANGE_WEAPON: 2097

CUTSCENE_CHANGE_WEATHER_TAG: 2216

CUTSCENE_CLOSE_BTEXT: 2089

CUTSCENE_CLOTH_PHYSICS_COLLISION_ENABLE: 830

CUTSCENE_CLOTH_WIND: 2112

CUTSCENE_CUE_ATTACH_WEAPON: 2063

CUTSCENE_CUE_BTEXT: 2053

CUTSCENE_CUE_CAMERA_BLUR: 2057

CUTSCENE_CUE_CHANGE_CHARCTRL: 2061

CUTSCENE_CUE_CHAPTER_NAME: 2064

CUTSCENE_CUE_COMMENT_SUBTITLE: 2130

CUTSCENE_CUE_CREATE_ENTITY: 2059

CUTSCENE_CUE_CREATE_RADIATION: 2062

CUTSCENE_CUE_DISPATCH_EVENT: 2264

CUTSCENE_CUE_DOF: 2054

CUTSCENE_CUE_ENTER_STATE: 2060

CUTSCENE_CUE_HIDE_ACCESSORY: 2066

CUTSCENE_CUE_HIDE_ENTITY: 2049

CUTSCENE_CUE_HIDE_WEAPON: 2056

CUTSCENE_CUE_OPEN_UI: 2055

CUTSCENE_CUE_PLAY_MUSIC: 2052

CUTSCENE_CUE_QTE: 2069

CUTSCENE_CUE_SCENARIO_SPEED: 2051

CUTSCENE_CUE_SUBTITLE: 2050

CUTSCENE_CUE_SWITCH_CLOTH: 2065

CUTSCENE_CUE_SWITCH_NPC_CLOTH: 2071

CUTSCENE_CUE_UNLOCK_CAMERA: 2058

CUTSCENE_CUE_VOICE_ANIM: 2070

CUTSCENE_DISABLE_MAIN_SHADOW: 2116

CUTSCENE_DISABLE_SOUND_SYNC: 2244

CUTSCENE_EDITOR_ENV: 795

CUTSCENE_EDITOR_ENV_FOG: 804

CUTSCENE_EDITOR_SET_GLOBAL_OPTION: 3332

CUTSCENE_EDITOR_SET_RENDER_OPTION: 3331

CUTSCENE_EDIT_EFFECT_COLOR: 3329

CUTSCENE_EDIT_EFFECT_PLAYRATE: 3330

CUTSCENE_ENABLE_CAMERA_GRASS_COLLIDE: 2205

CUTSCENE_ENABLE_CSM_UPDATE: 2123

CUTSCENE_ENABLE_FLAMENCO_SIM: 2276

CUTSCENE_ENABLE_SOFTBONE: 2204

CUTSCENE_ENTITY_AUTO_FILL_LIGHT: 2239

CUTSCENE_ENTITY_RECEIVE_DECAL: 2202

CUTSCENE_ENTITY_STORYBOARD_SPEED: 2095

CUTSCENE_EQUIP_WEAPON: 2099

CUTSCENE_EVENT_ADD_INTERACT: 2235

CUTSCENE_EVENT_BEHAVIOR_EVENT: 2232

CUTSCENE_EVENT_PAUSE_PARALLEL_CUTSCENES: 2233

CUTSCENE_EVENT_SET_TRANSFORM: 2231

CUTSCENE_EVENT_TRACK_TARGET: 2234

CUTSCENE_EVENT_TRIGGER_CONTINUE: 2230

CUTSCENE_FORBID_SERVER_ANIM: 2246

CUTSCENE_GHOST_EFFECT: 2107

CUTSCENE_HIDE_AIRWALL_EFFECT: 2120

CUTSCENE_HIDE_ALL_STATIC_POINTLIGHT: 2214

CUTSCENE_HIDE_ALL_WEAPONS: 2220

CUTSCENE_HIDE_ENTITY_MESH: 2103

CUTSCENE_HIDE_FASHION_EFFECT: 2275

CUTSCENE_HIDE_FOLIAGE: 2249

CUTSCENE_HIDE_HEX_EFFECT: 2240

CUTSCENE_HIDE_NPC_AND_OTHER: 2072

CUTSCENE_HIDE_STATIC_LIGHT: 2206

CUTSCENE_HIDE_STATIC_MODEL: 2203

CUTSCENE_H_MOTION_BLUR: 2218

CUTSCENE_LIMIT_FPS: 2117

CUTSCENE_LOAD_LIMIT_PERFRAME: 2268

CUTSCENE_LOAD_MASK_VIDEO: 2119

CUTSCENE_LOOKAT: 2252

CUTSCENE_MAIN_TASK_POEMS_SHOW: 2262

CUTSCENE_MODEL_EFFECT: 2108

CUTSCENE_MOTION_BLUR: 2106

CUTSCENE_OPEN_PAINTING_BOAT_UI: 2272

CUTSCENE_OVERSEA_PLAY_SPEED: 2141

CUTSCENE_PERSON_INFO_CUE: 2096

CUTSCENE_PERSON_INFO_CUE_NEW: 2217

CUTSCENE_PLAY_ANIM_ACTION: 2236

CUTSCENE_PLAY_EDITABLE_EFFECT: 3328

CUTSCENE_PLAY_FACE_ANIM: 2207

CUTSCENE_PLAY_ISO_VIDEO: 2122

CUTSCENE_PLAY_SOUND_CUE: 2253

CUTSCENE_PLAY_VIDEO: 2090

CUTSCENE_PLAY_VOICE: 2067

CUTSCENE_PRELOAD_SURFACE: 2265

CUTSCENE_PRELOAD_VIDEO: 2118

CUTSCENE_PRE_END_VIDEO: 2133

CUTSCENE_PRE_FINISH: 2251

CUTSCENE_PVS_PEAK_LIMIT: 2279

CUTSCENE_REFRESH_ENV: 2224

CUTSCENE_REPLACE_MATERIAL: 2241

CUTSCENE_RESET_CLOTH: 2075

CUTSCENE_RESET_ENV_PREFAB: 2254

CUTSCENE_RESET_SOFTBONE: 2242

CUTSCENE_SCREEN_MOTION_GRAY_PARAMS: 2261

CUTSCENE_SET_BASE_GRAPH_PARAM: 2208

CUTSCENE_SET_CAMERA_FAR: 2263

CUTSCENE_SET_CAMERA_NEAR: 2083

CUTSCENE_SET_CAMERA_PRINCIPLE: 2085

CUTSCENE_SET_CHAR_GI_SCALE: 2115

CUTSCENE_SET_CLOTH_DIS: 2084

CUTSCENE_SET_COLLISION_CACHE: 2213

CUTSCENE_SET_ENABLE_DROP: 2109

CUTSCENE_SET_EVN_PARAMETER: 2212

CUTSCENE_SET_FOOTFIT_CHECK: 2105

CUTSCENE_SET_GLOBAL_OPTION: 2255

CUTSCENE_SET_HEX_LIGHT: 2250

CUTSCENE_SET_HEX_LOD_DISTANCE: 2211

CUTSCENE_SET_HEX_SPOTLIGHT: 2256

CUTSCENE_SET_HORSE_BRIDLE_PARM: 2258

CUTSCENE_SET_LISTEN_STATE: 2210

CUTSCENE_SET_LOOP_BEGIN: 2259

CUTSCENE_SET_MAIN_PLAYER_PRINCIPLE: 2086

CUTSCENE_SET_MOVABLE: 2267

CUTSCENE_SET_PRINCIPLE: 2074

CUTSCENE_SET_REFLECTION_VISIBLE: 2257

CUTSCENE_SET_RENDER_OPTION: 2098

CUTSCENE_SET_SHADOW_AREA: 2124

CUTSCENE_SET_SOFTBONES_WIND_PARAMS: 2260

CUTSCENE_SET_SOFTBONE_SOFTNESS: 2243

CUTSCENE_SET_USE_FLOOR: 2266

CUTSCENE_SET_WORLD_EFFECT_LEVEL_STATE: 2111

CUTSCENE_SHOWROOM_CAMERA_PARAMS: 2113

CUTSCENE_SHOWROOM_SYNC_CAMERA: 2114

CUTSCENE_SHOW_CHAPTER: 2101

CUTSCENE_SHOW_LEFT_TIP: 2104

CUTSCENE_SHOW_WEATHER_EFFECT: 2274

CUTSCENE_SICK_BLUR: 2110

CUTSCENE_SKYBOX: 2247

CUTSCENE_SOFTBONE_ENSURE_FULL_SIM: 2273

CUTSCENE_SWITCH_CAMERA_MODE: 2227

CUTSCENE_SWITCH_CHARCTRL: 2201

CUTSCENE_SWITCH_MODEL_LOD: 2228

CUTSCENE_WATCH_TARGET: 807

CUTSCENE_WORLD_BEHAVIOR_CHECK: 2237

EDITOR_CLEAR_TIME_OF_DAY: 802

EDITOR_SET_LOCAL_HOUR: 799

EDITOR_SET_SHICHEN_SPEED: 798

EDITOR_SET_TIME_OF_DAY: 801

ENTER_AREA_SIGNAL: 32769

ENTER_CONNECTING_MARK_SIGNAL: 32819

ENTER_HOLDING_MARK_SIGNAL: 32821

ENTER_RIDING_SIGNAL: 32807

ENTITY_CUE_HIDE_ENTITY_PART: 35

EVENT_ANIM_ACTION_UNBLOCK_INTERRUPT: 2278

EVENT_BASE_CUE_ENTER_SPECIAL_IDLE: 2303

EVENT_BASE_CUE_LEAVE_SPECIAL_IDLE: 2304

EVENT_CUE_ACTIVE_WEAPON_ANIM: 773

EVENT_CUE_ADJUST_CLOTH_PART: 131

EVENT_CUE_ANIM_CONTROL_HIT_ANIM: 26

EVENT_CUE_ANIM_END: 27

EVENT_CUE_APPLY_SPEC_STATE: 796

EVENT_CUE_ARCHER_AIM_LOGIC_MODE: 834

EVENT_CUE_ARCHER_AIM_STATUS: 826

EVENT_CUE_ARCHER_AIM_VIEW_ACTION: 833

EVENT_CUE_ARCHER_FLY_CHANGE: 835

EVENT_CUE_ARCHER_PULL_END: 832

EVENT_CUE_ARROW_CHANGE_HAND: 823

EVENT_CUE_ARROW_ENSURE_PLAY_EFFECT: 831

EVENT_CUE_ATTACH_EFFECT_MODE: 2079

EVENT_CUE_ATTACH_ENTITY: 50

EVENT_CUE_BATTLE_END_CHANGE_WEAPON: 337

EVENT_CUE_BATTLE_MODE_CHANGE: 1797

EVENT_CUE_BEGIN_PLAY_CAMERA_ANIM: 330

EVENT_CUE_BEHIT_INPUT_CACHE: 1290

EVENT_CUE_BEHIT_POST: 1283

EVENT_CUE_BEHIT_TO_WEAK: 1285

EVENT_CUE_BIGFLY_LOAD_WEAPON: 813

EVENT_CUE_BIG_FLY_CAMERA: 48

EVENT_CUE_BOSS_TRIGGER_EVENT: 325

EVENT_CUE_BOW_CHANGE_HAND: 819

EVENT_CUE_CAMERA_ANIM: 806

EVENT_CUE_CAMERA_COLLIDER: 68

EVENT_CUE_CAMERA_FOCUS_TOL: 51

EVENT_CUE_CAMERA_OCCLUSION_MIN_RADIUS: 845

EVENT_CUE_CAMERA_SET_YAW: 342

EVENT_CUE_CAMREA_BLUR_WITH_VX: 137

EVENT_CUE_CHANGE_ANIM_ACTION_TYPE: 135

EVENT_CUE_CHANGE_WEAPON_LINK_ANIM: 782

EVENT_CUE_CHANGE_WEAPON_POINT: 772

EVENT_CUE_CHANGE_WEAPON_TACH: 340

EVENT_CUE_CHARCTRL_ENABLE: 358

EVENT_CUE_CLIMB_ROCK_DATA: 829

EVENT_CUE_CLIMB_ROCK_FORBID: 815

EVENT_CUE_CLOSE_DYNAMIC_VISIBILITY_BOX: 335

EVENT_CUE_COLLISION_SOUND_ENABLE: 359

EVENT_CUE_COLLISTION: 128

EVENT_CUE_COLLISTION_CALC: 793

EVENT_CUE_COMBAT_RES_UPDATE: 43

EVENT_CUE_COMBO_SKILL_SET: 1284

EVENT_CUE_CONTINUE_SKILL: 63

EVENT_CUE_CREATE_ARROW: 822

EVENT_CUE_CREATE_DOMAIN: 790

EVENT_CUE_CREATE_ENTITY: 126

EVENT_CUE_CREATE_POPO: 401

EVENT_CUE_CREATE_RADIATION: 300

EVENT_CUE_CREATE_TRAP: 323

EVENT_CUE_CUJU_ACTION_QTE: 361

EVENT_CUE_DEBATE_BATTLE_EMOTION: 329

EVENT_CUE_DEBATE_BATTLE_FLAG_CHANGED: 332

EVENT_CUE_DEBATE_BATTLE_POPO: 327

EVENT_CUE_DESTROY_ENTITY: 350

EVENT_CUE_DESTROY_WEAPON_TRAP: 65

EVENT_CUE_DETACH_PLAY_ANIM: 36

EVENT_CUE_DOCTOR_THERAPY: 64

EVENT_CUE_DO_GOTO: 402

EVENT_CUE_EFFECT: 2076

EVENT_CUE_ENABLE_DEFENCE: 825

EVENT_CUE_ENABLE_FACE_LOD: 824

EVENT_CUE_ENABLE_PHYSIC: 202

EVENT_CUE_ENABLE_STATE: 789

EVENT_CUE_ENABLE_THRUSTER: 321

EVENT_CUE_ENTER_STATE: 349

EVENT_CUE_ENV_DARKEN: 791

EVENT_CUE_ENV_SENSOR_ACTION: 821

EVENT_CUE_EXPOSURE_EFFECT: 808

EVENT_CUE_FALLHURT_ENABLE: 347

EVENT_CUE_FINISH_PLAY_CAMERA_ANIM: 331

EVENT_CUE_FOLLOW_CAMERA_COLLIDE_RETREAT: 42

EVENT_CUE_FOLLOW_CAMERA_ENABLE_INERTIAY: 40

EVENT_CUE_FOLLOW_CAMERA_INERTIA_COEFFY: 41

EVENT_CUE_FOLLOW_IDLE_RUN: 320

EVENT_CUE_FOOTPRINT: 30

EVENT_CUE_FORBID_ANIM_SUFFIX: 837

EVENT_CUE_FORBID_CHANGE_WEAPON_POINT: 787

EVENT_CUE_FORBID_PUSH_PLAYER: 356

EVENT_CUE_FY_H_ENTER_COLLISION: 224

EVENT_CUE_FY_H_LEAVE_COLLISION: 225

EVENT_CUE_FY_V_HIGH_ENTER_COLLISION: 222

EVENT_CUE_FY_V_HIGH_LEAVE_COLLISION: 223

EVENT_CUE_FY_V_LOW_ENTER_COLLISION: 220

EVENT_CUE_FY_V_LOW_LEAVE_COLLISION: 221

EVENT_CUE_FY_V_MAX_ENTER_COLLISION: 228

EVENT_CUE_FY_V_MAX_LEAVE_COLLISION: 229

EVENT_CUE_FY_V_MIN_ENTER_COLLISION: 226

EVENT_CUE_FY_V_MIN_LEAVE_COLLISION: 227

EVENT_CUE_GAMEPLAY_STATE_CHANGED: 326

EVENT_CUE_GHOST_EFFECT: 28

EVENT_CUE_GROUP_ACTION: 310

EVENT_CUE_GROUP_ACTION_QTE: 311

EVENT_CUE_GROUP_BASE: 9

EVENT_CUE_GROUP_CUTSCENE: 8

EVENT_CUE_GROUP_FLAG: 5

EVENT_CUE_GROUP_INTERACT: 7

EVENT_CUE_GROUP_JUMP: 6

EVENT_CUE_GROUP_LIMIT: 126

EVENT_CUE_GROUP_MF: 4

EVENT_CUE_GROUP_SKILL: 3

EVENT_CUE_GUISE_CHANGE: 362

EVENT_CUE_HEAD_ANGLE_OVER: 2081

EVENT_CUE_HIDE_ENTITY: 31

EVENT_CUE_HIDE_MESH: 809

EVENT_CUE_HIDE_WEAPON: 67

EVENT_CUE_IMPACT_BEHIT_MODE: 1286

EVENT_CUE_INTERACT_PICKUP: 1793

EVENT_CUE_INTERACT_PUTDOWN: 1794

EVENT_CUE_INTERACT_TRANS_SEND: 1798

EVENT_CUE_JUMP_DOWN: 33

EVENT_CUE_JUMP_OVER: 1537

EVENT_CUE_KEEP_WEAPON_HOLD: 838

EVENT_CUE_KINK_WEIGHT: 322

EVENT_CUE_LADDER_USER_DATA: 351

EVENT_CUE_LEFT_ARROW_CHANGE: 851

EVENT_CUE_LOAD_EFFECT_PREFAB: 840

EVENT_CUE_LOCAL_BLUR: 47

EVENT_CUE_MAGIC_FIELD: 770

EVENT_CUE_MAKEUP: 324

EVENT_CUE_MARSH_USER_DATA: 352

EVENT_CUE_MINDLAKE_REPLAY: 348

EVENT_CUE_MODEL_EFFECT: 60

EVENT_CUE_MODEL_TRANSPARENT: 354

EVENT_CUE_MODIFY_COLLISION_INFO: 203

EVENT_CUE_MONSTER_DETECT_JUMP: 353

EVENT_CUE_NEIGONG_STATE_END: 346

EVENT_CUE_NEIGONG_STATE_TIAOXI: 3460

EVENT_CUE_NPC_CHANGE_WEAPON_POINT: 2077

EVENT_CUE_OPEN_DYNAMIC_VISIBILITY_BOX: 334

EVENT_CUE_PATH_FINDING_FINISH: 46

EVENT_CUE_PIVOT_MANUAL_ROTATE: 53

EVENT_CUE_PLAY_CONDITIONAL_EFFECT: 846

EVENT_CUE_PLAY_REPLACABLE_EFFECT: 32511

EVENT_CUE_PLAY_SOUND_BY_ID: 805

EVENT_CUE_PLAY_WEAPON_EFFECT: 810

EVENT_CUE_PLAY_WEAPON_STATE_EFFECT: 852

EVENT_CUE_POP_FOLLOW_CAMERA: 45

EVENT_CUE_POS_FLAG: 1282

EVENT_CUE_POS_PITCH_FLAG: 2091

EVENT_CUE_PREFAB_INTERACT: 2094

EVENT_CUE_PUSH_FOLLOW_CAMERA: 44

EVENT_CUE_PUT_RIVER_LAMP: 363

EVENT_CUE_QTE: 130

EVENT_CUE_RANGE_CAMERA_SHAKE: 1287

EVENT_CUE_RECOVER_ZQ: 817

EVENT_CUE_REFRESH_NAVI: 1291

EVENT_CUE_REMOVE_EFFECTS: 786

EVENT_CUE_RESET_CAMERA_YAW: 32

EVENT_CUE_RESET_COMPONENT: 2080

EVENT_CUE_RESET_WEAPON_LINK: 812

EVENT_CUE_RIGHT_ARROW_CHANGE: 850

EVENT_CUE_ROTATE: 125

EVENT_CUE_SBGD_POINT: 811

EVENT_CUE_SCHOOL_LEARN_SPEED: 336

EVENT_CUE_SCREEN_COLOR_TINTCOLOR1: 29

EVENT_CUE_SET_ANIM_SOFTBONE_RANGE_OFFSET: 856

EVENT_CUE_SET_BASE_STATE: 58

EVENT_CUE_SET_CAMERA_TICK_STATE: 38

EVENT_CUE_SET_CAP_BOX: 364

EVENT_CUE_SET_COLLISION_INFO: 360

EVENT_CUE_SET_COLLISION_PRIORITY: 849

EVENT_CUE_SET_COMPOSURE: 201

EVENT_CUE_SET_DIE_FLAG: 200

EVENT_CUE_SET_ENABLE_DROP: 66

EVENT_CUE_SET_ENV_LIST: 343

EVENT_CUE_SET_GRAPH_VARIABLE: 34

EVENT_CUE_SET_SOFTBONE_FORWARD_TIME: 848

EVENT_CUE_SET_SOFTBONE_RANGE_OFFSET: 2270

EVENT_CUE_SET_SOFTBONE_SOFTNESS: 855

EVENT_CUE_SET_WEAPON_DIS: 134

EVENT_CUE_SET_WEAPON_TARGET: 341

EVENT_CUE_SICK_BLUR: 136

EVENT_CUE_SKILL_ANIM_SPEED: 842

EVENT_CUE_SKILL_CAMERA_PIVOT: 3101

EVENT_CUE_SKILL_COMBAT_RES_CMP: 781

EVENT_CUE_SKILL_EVENT: 769

EVENT_CUE_SKILL_GAMEPLAY_FLAG: 54

EVENT_CUE_SKILL_GAME_SPEED: 780

EVENT_CUE_SKILL_LINK_EFFECT: 779

EVENT_CUE_SKILL_PANEL_CONTRACT: 328

EVENT_CUE_SKILL_QTE_SIG: 792

EVENT_CUE_SKILL_ROTATE: 55

EVENT_CUE_SKILL_SLOT_EVENT: 37

EVENT_CUE_SKILL_TACH_ANIM: 778

EVENT_CUE_SKILL_TACH_ENTITY: 777

EVENT_CUE_SKILL_TELEPORT: 774

EVENT_CUE_SKILL_TRIGGER_EVENT: 794

EVENT_CUE_SOUND: 8

EVENT_CUE_SPECIAL_HIT: 788

EVENT_CUE_SP_HIT: 836

EVENT_CUE_START_VAT_DISSOLVE: 2082

EVENT_CUE_STOP_BIG_FLY_CAMERA: 49

EVENT_CUE_SWITCH_CLOTH_PART: 132

EVENT_CUE_SWITCH_SOFTBONE: 844

EVENT_CUE_SWITCH_SOFTBONE_FLOOR: 847

EVENT_CUE_SWITCH_WEAPON_CLOTH: 133

EVENT_CUE_TACH_EFFECT: 1289

EVENT_CUE_TARGET_DIST: 61

EVENT_CUE_TARGET_EFFECT: 4004

EVENT_CUE_TARGET_SKILL_SLOT_DYEFFECT: 59

EVENT_CUE_TRIGGER_CALC_POINT: 771

EVENT_CUE_TRIGGER_FIRE_EFFECT: 841

EVENT_CUE_UI: 127

EVENT_CUE_UPDATE_FOLLOW_PARAMS: 345

EVENT_CUE_UPPERLAYER_STATUS: 827

EVENT_CUE_USER_DATA: 129

EVENT_CUE_VATMODEL: 56

EVENT_CUE_WATCH_ENABLE: 843

EVENT_CUE_WEAPON_ANIM: 57

EVENT_CUE_WEAPON_ON_ANIM: 355

EVENT_CUE_WEAPON_SHIELD_DEFENCE: 828

EVENT_CUE_WEAPON_THROW_END: 62

EVENT_CUE_WEATHER_EFFECT: 4000

EVENT_FILTER_TURN: 1028

EVENT_FORBID_CAMERA_ROTATE: 839

EVENT_H_MOTION_BLUR: 22

EVENT_JOYSTICK_SOUND_MOTION_SWITCH: 23

EVENT_MOTION_BLUR: 20

EVENT_PAOWUXIAN_STOP: 4001

EVENT_PART_BLUR: 21

EVENT_PATH_LAUNCHER_FAIL: 339

EVENT_PATH_LAUNCHER_SUCC: 338

EVENT_PLAY_JOYSTICK_MOTION_SOUND: 816

EVENT_PUTDOWN_TEMP_WEAPON: 357

EVENT_RESET_SKILL_MOTION_CTRL: 2092

EVENT_SET_ROAD_SIGN: 4002

EVENT_SKILL_PRE_CALC_TIP: 2093

EVENT_SKILL_TUOLI_START: 814

EVENT_SUMO_ENHANCE_EFFECT: 4003

EVENT_SYNC_SKILL_CUE: 803

EVENT_WEAPON_RESET_DEFAULT_LINK: 820

INTERACT_CUE_AHEAD_ACTION: 1796

INTERACT_CUE_PICK_UP: 1793

INTERACT_CUE_PUT_DOWN: 1794

INTERACT_CUE_RESULT: 1795

LAUNCHER_FINISHED: 1026

LEAVE_AREA_SIGNAL: 32770

LEAVE_CONNECTING_MARK_SIGNAL: 32820

LEAVE_HOLDING_MARK_SIGNAL: 32822

LEAVE_RIDING_SIGNAL: 32808

MAGIC_FIELD_HIT: 1025

NODE_ACTIVATED_SIGNAL: 32777

NODE_DEACTIVATED_SIGNAL: 32778

SERVER_EVENT_LEARN_SKILL: "event_learn_skill"

SERVER_EVENT_RESET_RES: "reset_res"

SET_CLOTH_WIND: 1027

SET_ENABLE_CONTROL_CAMERA: 2087

SET_MAIN_PLAYER_ENABLE_CONTROL_CAMERA: 2088

SET_WORLD_EFFECT_LEVEL_STATE: 797

SKILL_CUE_ACTIVE_WEAPON_ANIM: 5

SKILL_CUE_CALC_POINT: 3

SKILL_CUE_CHANGE_WEAPON_LINK_ANIM: 14

SKILL_CUE_CHANGE_WEAPON_POINT: 4

SKILL_CUE_CREATE_DOMAIN: 22

SKILL_CUE_ENABLE_STATE: 21

SKILL_CUE_ENV_DARKEN: 23

SKILL_CUE_FORBID_CHANGE_WEAPON_POINT: 19

SKILL_CUE_MAGIC_FIELD: 2

SKILL_CUE_REMOVE_EFFECTS: 18

SKILL_CUE_SKILL_CLIENT_GAME_SPEED: 818

SKILL_CUE_SKILL_COMBAT_RES_CMP: 13

SKILL_CUE_SKILL_GAME_SPEED: 12

SKILL_CUE_SKILL_LINK_EFFECT: 11

SKILL_CUE_SKILL_TACH_ANIM: 10

SKILL_CUE_SKILL_TACH_ENTITY: 9

SKILL_CUE_SPECIL_HIT: 20

SKILL_CUE_STATE: 1

SKILL_CUE_TELEPORT: 6

SKILL_CUE_TRIGGER_EVENT: 26

SKILL_QTE_SIG: 24

SLAVE_POP_GRAPH_SIGNAL: 32902

SLAVE_PUSH_GRAPH_SIGNAL: 32901

SYSTEM_CUE_EFFECT_ATTACH: 32765

SYSTEM_CUE_EFFECT_ATTACH_TARGET: 32764

SYSTEM_CUE_SOUND_FX: 1

SYSTEM_SIGNAL_BASE: 32767

TARGET_MARK_CHANGE_SIGNAL: 32817

TARGET_MARK_EMPTY_SIGNAL: 32818

TRANSITION_EXCUTE_SIGNAL: 32797

TRAVERSING_MARK_SIGNAL: 32823


-- End of hexm.common.consts.cue_consts