-- ======================================================================
-- Module: hexm.common.consts.langzhong_therapy_consts
-- Source: package.loaded
-- Type: table
-- Order: #6383
-- ======================================================================

-- Module type: table

BUFF_TARGET_SELF: 0

BUFF_TARGET_TARGET: 1

CONSUME_DISCARD: 0

CONSUME_ETHEREAL: 2

CONSUME_EXHAUST: 1

CONSUME_EXHAUST_KEEP: 3

CONSUME_EXHAUST_TYPE: instance {
  -- Metatable:
  --   __index: table
  --   __tostring: yes
  1: 1
  2: 2
  3: 3
}

FORCE_IN_DECK: 1

FORCE_IN_DISCARD: 3

FORCE_IN_EXHAUST: 4

FORCE_IN_HAND: 2

INTEREST_SKILL_ID: 16

LZ_RESOURCE_YINYANG: 10000

MARK_BAN_LAST: "ban_last"

MARK_RANDOM_COST: "random_cost"

MARK_SYS_D_KEY: instance {
  -- Metatable:
  --   __index: table
  --   __tostring: yes
  ban_last: "ban_card_last_turn"
  random_cost: "card_cost_random"
}

MULTI_THERAPY_CONFIG_NO: 1692

MULTI_THERAPY_CONFIRM_NO: 57

MULTI_THERAPY_DAILY_REWARD_KEY: "multi_therapy_daily_reward"

MULTI_THERAPY_DAILY_SCORE_KEY: "multi_therapy_daily_score"

MULTI_THERAPY_IDENTITY_LANGZHONG: 1

MULTI_THERAPY_IDENTITY_PATIENT: 2

MULTI_THERAPY_IDENTITY_PATIENT_BECURED: 3

MULTI_THERAPY_PATIENT_BUFF: 900000

MULTI_THERAPY_PATIENT_NO: 1700002

MULTI_THERAPY_STATE_GAME: 1

MULTI_THERAPY_STATE_INIT: 0

MULTI_THERAPY_TRAP_SERIAL_ID: 36

PATIENT_ANSWER_STATE_INIT: -1

PATIENT_ANSWER_STATE_RIGHT: 1

PATIENT_ANSWER_STATE_WRONG: 0

PM_TYPE_BOTH: 2

PM_TYPE_M: 0

PM_TYPE_P: 1

SKILL_TAG_ATK: 1

SKILL_TAG_FUNC: 6

SKILL_TAG_HEAL: 3

SKILL_TAG_REFLICT: 4

SKILL_TAG_RES: 5

SKILL_TAG_SHIELD: 2

SPECIAL_DAM_DISCARD_ALL: 4

SPECIAL_DAM_HURT_SELF: 3

SPECIAL_DAM_SHIELD_M: 2

SPECIAL_DAM_SHIELD_P: 1

TAG_MULTI_EVENT: "multi_event"

TAG_MWZX: "mwzx"

THERAPY_END_REASON_ABANDON: "abandon"

THERAPY_END_REASON_DEFAULT: ""

THERAPY_END_REASON_DISEASE_DEAD: "disease_dead"

THERAPY_END_REASON_EXPIRE_TIME: "expire_time"

THERAPY_END_REASON_INTERRUPT: "interrupt"

THERAPY_END_REASON_LEAVE_STATE: "leave_state_therapy"

THERAPY_END_REASON_LEVEL_CRASH: "level_crash"

THERAPY_END_REASON_PLAYER_DEAD: "player_dead"

THERAPY_INTERRUPT_EVENT_ABANDON_BY_DOCTOR: 0

THERAPY_INTERRUPT_EVENT_ABANDON_BY_PATIENT: -1

THERAPY_INTERRUPT_EVENT_DISTANCED: 6

THERAPY_INTERRUPT_EVENT_LEAVE_SPACE: 1

THERAPY_INTERRUPT_EVENT_LEAVE_SPACE_LEVEL: 4

THERAPY_INTERRUPT_EVENT_LOSE_CLIENT: 2

THERAPY_INTERRUPT_EVENT_RPC_FENGYUN: 3

THERAPY_INTERRUPT_EVENT_UNREACHED: 5

THERAPY_STAGE_END_DRAW: 4

THERAPY_STAGE_END_FAIL: 3

THERAPY_STAGE_END_SUCCESS: 2

THERAPY_STAGE_START: 1

USE_ENEMY_ALL: 2

USE_ENEMY_SINGLE: 1

USE_SELF: 0

USE_SELF_CARD: 3

_reload_all: true


-- End of hexm.common.consts.langzhong_therapy_consts