-- ======================================================================
-- Module: hexm.common.consts.vehicle_consts
-- Source: package.loaded
-- Type: table
-- Order: #2063
-- ======================================================================

-- Module type: table

BOAT_SPEED_BACK_MOVE: 4

BOAT_SPEED_BACK_MOVE_BRAKE: 6

BOAT_SPEED_DEFAULT_MOVE: 1

BOAT_SPEED_MOVE_BRAKE: 5

BOAT_SPEED_RUSH_MAX_MOVE: 3

BOAT_SPEED_RUSH_MOVE: 2

CLIENT_PLATFORM_IDX: 15

CREATE_SERVER_TAG_DEFAULT: "vehicle_default"

CREATE_VEHICLE_TAG_KAIFENG_ADVENTURE: "kaifeng_adventure"

E_ALREADY_OFF: 2

E_ALREADY_ON: 1

E_SUCCESS: 0

MAX_PLATFORM_IDX: 14

PLATFORM_ANGULAR_SPEED_NOTIFY_TOLERANCE: 0.0174532924

PLATFORM_LINEAR_SPEED_NOTIFY_TOLERANCE: 0.001

PLATFORM_TYPE_CLIENT: 2

PLATFORM_TYPE_NEW_V1: 2

PLATFORM_TYPE_NEW_V2: 3

PLATFORM_TYPE_OLD: 1

PLATFORM_TYPE_SERVER: 1

TYPE_DRIVE: 1

TYPE_PLATFORM: 2

VEHICLE_LOCKED: 1000000

VEHICLE_NORMAL: 1000013

VEHICLE_PAINTING_BOAT: 1

VEHICLE_UNDER_BUILDING: 1000012

_reload_all: true


-- End of hexm.common.consts.vehicle_consts