-- ======================================================================
-- Module: hexm.client.ui.handlers.goto_event_handler
-- Source: package.loaded
-- Type: table
-- Order: #2833
-- ======================================================================

-- Module type: table

GotoEventHandler: class {
  -- Metatable:
  --   __tostring: yes
  _add_events: function(arg1)  -- @hexm/client/ui/handlers/goto_event_handler.lua:31-431
  _goto_compound: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2265-2357
  _handel_chase_player: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1254-1256
  _handel_replace_title: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1250-1252
  _handle_MPlatform_goto_url: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4109-4114
  _handle_ask_pray_drop: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1606-1613
  _handle_ask_pray_real_name: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1590-1604
  _handle_call_object_func: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4059-4107
  _handle_change_remark: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1484-1497
  _handle_change_second_password: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3974-3976
  _handle_character_interest_skill_unlock: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3947-3952
  _handle_chat_clear_msg: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1824-1840
  _handle_chat_link_stuff: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1144-1190
  _handle_chat_open_player_float: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1546-1570
  _handle_chat_open_stuff_float: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1572-1588
  _handle_chat_player_delete: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1811-1822
  _handle_chat_send_msg: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1974-1990
  _handle_chat_show_team_history: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1842-1843
  _handle_clear_team_tank: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1670-1687
  _handle_club_info_back: function(arg1, arg2, arg3, arg4)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1029-1086
  _handle_club_room_invite_friend_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2519-2547
  _handle_common_share_navigate: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2025-2040
  _handle_debate_battle: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2074-2098
  _handle_debate_battle_spectate: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2120-2132
  _handle_debate_eval_share_goto: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2766-2780
  _handle_del_friend: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1703-1712
  _handle_del_friend_confirm: function(arg1, arg2)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1714-1724
  _handle_delete_black: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1130-1132
  _handle_delete_enemy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1122-1124
  _handle_delete_master: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1623-1629
  _handle_delete_second_password: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3978-3980
  _handle_delete_student: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1615-1621
  _handle_dispatch_str_event: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4044-4057
  _handle_edit_building_area: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2151-2155
  _handle_employee_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2688-2703
  _handle_employer_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2669-2686
  _handle_enter_blueprint_space: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:920-923
  _handle_expedition_team_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:913-918
  _handle_fast_chat: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1192-1194
  _handle_focus_nearest_judian: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4116-4120
  _handle_gang_blueprint_build_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:934-938
  _handle_gang_blueprint_design_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:930-932
  _handle_gang_ui: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2157-2163
  _handle_go_explore: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2145-2149
  _handle_goto_url: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4005-4023
  _handle_goto_webview_url: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4025-4028
  _handle_group_change_name: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1802-1809
  _handle_group_change_owner: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1862-1867
  _handle_group_create: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1726-1734
  _handle_group_dismiss: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1750-1775
  _handle_group_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1777-1784
  _handle_group_invite_person: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1786-1793
  _handle_group_kick_person: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1869-1874
  _handle_group_leave: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1876-1879
  _handle_group_manage: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1736-1748
  _handle_group_tip_off: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1881-1908
  _handle_guise_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1499-1512
  _handle_gymnastics_share_goto: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2705-2729
  _handle_identity_pvp_observe: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:842-847
  _handle_identity_pvp_single_attend: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:830-840
  _handle_identity_pvp_team_attend: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:849-860
  _handle_industry_accept_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:771-780
  _handle_industry_open_detail: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:743-748
  _handle_industry_open_main: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:750-755
  _handle_industry_open_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:764-769
  _handle_industry_remove_land: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:757-762
  _handle_interact_gang_boite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2622-2637
  _handle_interact_gang_pitch_pot: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2639-2652
  _handle_interact_with_employee: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2447-2460
  _handle_jieyi_change_leader: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3884-3887
  _handle_jieyi_confirm_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3808-3810
  _handle_jieyi_confirm_request: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3836-3838
  _handle_jieyi_force_quit: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3889-3892
  _handle_jieyi_notify: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3840-3842
  _handle_jieyi_open_chat: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3844-3846
  _handle_join_donate_shop: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:925-928
  _handle_join_group: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1207-1223
  _handle_look_person_info: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1845-1860
  _handle_make_black: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1126-1128
  _handle_make_enemy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1118-1120
  _handle_move_event: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2191-2216
  _handle_news_share_detail: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3812-3822
  _handle_npc_interact_intimacy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:862-869
  _handle_open_bomb_qte: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:782-799
  _handle_open_danmu: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1514-1525
  _handle_open_gameplay_task: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2654-2667
  _handle_open_group_invite_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1795-1800
  _handle_open_identity_main_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2013-2023
  _handle_open_jianwen_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2796-2799
  _handle_open_main_store: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2485-2487
  _handle_open_newspaper_by_id: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3824-3833
  _handle_open_player_float: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1134-1142
  _handle_open_player_head: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1388-1392
  _handle_open_player_info: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1383-1386
  _handle_open_points_store: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2462-2483
  _handle_open_sign_page_by_group: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1992-1995
  _handle_open_task_envelope_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2003-2006
  _handle_open_xiaji_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2801-2808
  _handle_p_b_on_board: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2614-2620
  _handle_painting_boat_building_co: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2549-2563
  _handle_painting_boat_free_party: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2565-2579
  _handle_painting_boat_free_party_card: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2581-2589
  _handle_painting_boat_free_party_pop_win: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2601-2612
  _handle_painting_boat_free_party_transfer: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3931-3937
  _handle_painting_boat_try_goto_free_party: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2591-2599
  _handle_private_hud_chat: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1196-1205
  _handle_recall_tutor_accept_share_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3939-3946
  _handle_report_annoy_player: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1225-1236
  _handle_report_player: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1399-1415
  _handle_report_player_coop: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1417-1437
  _handle_report_player_firework: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1439-1456
  _handle_report_player_sign: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1458-1463
  _handle_report_player_sign_get_player_model_callback: function(arg1, arg2, arg3, arg4)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1465-1482
  _handle_ride_backseat_rideoff: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1970-1972
  _handle_ride_invite_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1953-1960
  _handle_ride_send_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1962-1968
  _handle_room_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1362-1381
  _handle_room_call_member: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1351-1355
  _handle_room_callall: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1346-1349
  _handle_room_return: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1357-1360
  _handle_school_enroll: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2048-2053
  _handle_school_participate: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2055-2060
  _handle_set_team_tank: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1631-1668
  _handle_setup_industry: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:736-741
  _handle_share_position: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1527-1544
  _handle_share_sprite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4030-4042
  _handle_space_room_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1943-1951
  _handle_space_room_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1910-1917
  _handle_space_room_remove: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1919-1934
  _handle_space_room_remove_team: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1936-1941
  _handle_spring_festival_carnival_task_start: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3954-3966
  _handle_spring_festival_request_order: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3968-3972
  _handle_stuff_museum_info: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2172-2182
  _handle_stuff_museum_second: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2184-2189
  _handle_team_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:891-911
  _handle_team_apply_leader: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1271-1273
  _handle_team_apply_list: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1275-1277
  _handle_team_auto_match: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1283-1285
  _handle_team_cancel_auto_match: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1287-1289
  _handle_team_ccmini_change_voice: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1342-1344
  _handle_team_ccmini_listen: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1330-1332
  _handle_team_ccmini_mute: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1334-1336
  _handle_team_ccmini_speak: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1338-1340
  _handle_team_change_leader: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1106-1109
  _handle_team_create: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1097-1099
  _handle_team_follow: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1263-1265
  _handle_team_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:871-889
  _handle_team_invite_list: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1279-1281
  _handle_team_leave: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1093-1095
  _handle_team_leave_temp: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1267-1269
  _handle_team_make_friend: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1111-1116
  _handle_team_mute_player: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1291-1301
  _handle_team_recall: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1258-1261
  _handle_team_remove: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1101-1104
  _handle_team_unmute_player: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1303-1313
  _handle_tourist_school_ceremony: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2134-2143
  _handle_trigger_start_club_anbao: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2497-2517
  _handle_unlock_post: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2489-2491
  _handle_use_hongbao_stuff: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1689-1701
  _handle_use_post_recover: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2493-2495
  _handle_visit_npc: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2008-2011
  _handle_waiguan_borrow: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3894-3929
  _handle_waiguan_borrow_request: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3848-3881
  _handle_wenshi_answer_interact: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2757-2759
  _handle_wenshi_answer_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2761-2764
  _handle_wenshi_multi_ans_share_goto: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2731-2755
  _handle_wulinlu_goto_map: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1394-1397
  _handle_zft_enroll: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2062-2066
  _handle_zft_participate: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2068-2072
  _handler_open_school_select: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1997-2001
  _handler_open_tavern_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2165-2170
  _handler_team_ccmini_opt: function(arg1, arg2)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1316-1328
  _on_entry_open_bag: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:801-804
  _on_entry_open_baixiao: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:806-809
  _on_entry_open_building: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:811-813
  _on_entry_open_jishi: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:815-818
  _on_entry_open_lunjian: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:820-823
  _on_entry_open_mail: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:825-828
  _open_activity_recall_tutor: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4123-4127
  _trace_debate_battle_npc: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2218-2238
  _use_wenshi_menke_service: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2782-2794
  common_share_navigate_callback: function(arg1, arg2)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2042-2046
  ctor: function(arg1, arg2)  -- @hexm/client/ui/handlers/goto_event_handler.lua:16-20
  debate_npc_act: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2100-2108
  destroy_object: function(arg1)  -- @hexm/client/ui/handlers/goto_event_handler.lua:22-29
  generate_url_by_data: function(arg1, arg2)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3982-4003
  handle_battle_sparring_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3261-3265
  handle_battle_sparring_trace: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3267-3276
  handle_battle_sparring_transfer_to: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3278-3280
  handle_boat_game_start: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3195-3209
  handle_bounty_invite_fetch: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3282-3305
  handle_bounty_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3307-3309
  handle_chat_room_action_ban: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:489-493
  handle_chat_room_action_change_owner: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:513-534
  handle_chat_room_action_close_mic: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:507-511
  handle_chat_room_action_open_mic: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:501-505
  handle_chat_room_action_unban: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:495-499
  handle_chat_room_cancel_silence: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:483-487
  handle_chat_room_enter: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:449-469
  handle_chat_room_invite_mic: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:471-475
  handle_chat_room_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:435-447
  handle_chat_room_silence: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:477-481
  handle_club_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1016-1022
  handle_club_appoint_post: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:989-1002
  handle_club_edit_post: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:970-987
  handle_club_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:953-957
  handle_club_kick_member: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:959-968
  handle_club_room_kick: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1024-1027
  handle_club_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:940-951
  handle_club_transfer_master: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1004-1014
  handle_coop_game_share_invited: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3097-3119
  handle_coop_hoard_profiteer_send_msg: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3180-3193
  handle_coop_hoard_profiteer_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3132-3178
  handle_disease_apply_cure: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3550-3581
  handle_disfavorite_chat_room: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:542-546
  handle_favorite_chat_room: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:536-540
  handle_flying_dance_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3583-3603
  handle_gather_game_share_invited: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3122-3129
  handle_got_szyy_double_entry: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2986-3004
  handle_goto_check_player_card: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2932-2940
  handle_goto_compound: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2240-2242
  handle_goto_compound_assist: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2244-2246
  handle_goto_compound_handmade: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2248-2263
  handle_goto_create_coop_szyy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2962-2970
  handle_goto_disaster_build_qte_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3050-3052
  handle_goto_exchange_collection: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2942-2959
  handle_goto_friend_favorite_qingyilin: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3677-3681
  handle_goto_gang_build_qte: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2379-2389
  handle_goto_gang_build_qte_invite_click: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2391-2396
  handle_goto_gang_cook_compound: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2367-2377
  handle_goto_gang_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2359-2365
  handle_goto_immediate_dance_thank_admire: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3023-3031
  handle_goto_mentor_npc_when_valid: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3785-3797
  handle_goto_npc_prison_transfer: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2810-2812
  handle_goto_participate_szyy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2972-2976
  handle_goto_play_instrument_thank_admire: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3245-3253
  handle_goto_prison_build_qte_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2818-2820
  handle_goto_prison_build_qte_single: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2814-2816
  handle_goto_prison_material_exchange: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2822-2824
  handle_goto_prison_material_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2826-2828
  handle_goto_prison_reflect_transfer: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2830-2845
  handle_goto_prison_visit: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2847-2864
  handle_goto_qingyilin_friend_login: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3689-3698
  handle_goto_qingyilin_transfer: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3683-3687
  handle_goto_start_immediate_dance: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3018-3021
  handle_goto_start_sumo_pve: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3033-3048
  handle_goto_szyy_follow: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3006-3011
  handle_goto_szyy_leader_start_follow: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3013-3016
  handle_goto_szyy_single_entry: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2978-2984
  handle_goto_zhuoying_trace_clue: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2424-2432
  handle_goto_zhuoying_trace_npc: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2434-2445
  handle_guyun_paper_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3236-3243
  handle_invite_private_voice: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:572-607
  handle_locate_monster_by_reward: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3058-3095
  handle_mentor_share_card_goto: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3669-3675
  handle_npc_stuff_received: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2900-2923
  handle_open_achieve: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1088-1091
  handle_open_build_recipe_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3255-3259
  handle_open_compound_win: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3481-3519
  handle_open_horse_sale: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3540-3548
  handle_open_map_and_focus_nearest_evac: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:695-720
  handle_open_map_and_focus_one_evac: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:722-733
  handle_open_mic_opt_in_chat_page: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:621-638
  handle_open_role_attr_item: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:644-657
  handle_open_team_dungeon_win: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3460-3479
  handle_open_world_view_info_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3615-3638
  handle_open_world_view_kaoju_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3640-3648
  handle_open_wuxue_skill: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:674-693
  handle_qiyu_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2883-2898
  handle_qx_join_open_listen_float: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3521-3523
  handle_qx_join_start_need_moeny: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3536-3538
  handle_qx_join_start_no_moeny: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3525-3534
  handle_region_game_pursue_sync: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3799-3807
  handle_report_chat_room: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:548-570
  handle_school_chief_vote: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3211-3234
  handle_school_punish_zuihuayin: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3605-3612
  handle_send_chat_gift: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:609-619
  handle_sign_open_detail: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3054-3056
  handle_space_room_invite_chat: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3700-3712
  handle_space_room_rec_goto_map: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3714-3731
  handle_space_room_rec_goto_quick: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3733-3751
  handle_space_room_rec_goto_quick_guest: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3753-3770
  handle_task_progress_node_unlocked: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2879-2881
  handle_trade_open_diandang: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3311-3333
  handle_trade_open_jishou_buy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3387-3439
  handle_trade_open_sell: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3335-3361
  handle_trade_open_shop_buy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3363-3385
  handle_try_change_nickname: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3441-3458
  handle_xinfa_uprank_stuff_use: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:659-672
  handler_goto_parade_audience_enter: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2866-2869
  handler_goto_parade_prisoner_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2871-2877
  handler_group_setting_side: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1238-1248
  handler_help_finish_guild_miwuzhuxie_task: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2398-2406
  handler_multiplayer_event_track_event: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2925-2930
  handler_open_anim_action_window_force_anim: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3773-3783
  on_gang_info_back: function(arg1, arg2, arg3, arg4)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2408-2422
}


-- End of hexm.client.ui.handlers.goto_event_handler