-- ======================================================================
-- Module: hexm.client.ui.handlers.goto_event_handler
-- Source: package.loaded
-- Type: table
-- Order: #6573
-- ======================================================================

-- Module type: table

GotoEventHandler: class {
  -- Metatable:
  --   __tostring: yes
  __module__: "hexm/client/ui/handlers/goto_event_handler.lua"
  _add_events: function(arg1)  -- @hexm/client/ui/handlers/goto_event_handler.lua:32-567
  _building_interact_open_song_list_page: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5279-5285
  _chat_invite_meteor_shower: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5274-5277
  _doudizhu_kick_robot: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5089-5097
  _goto_compound: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2767-2859
  _handel_chase_player: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1603-1605
  _handel_replace_title: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1599-1601
  _handl_open_giftsend_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5070-5081
  _handle_MPlatform_goto_url: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5162-5167
  _handle_activity_cooling_fight_boss_interact: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5168-5180
  _handle_add_chat_npc_msg: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2083-2089
  _handle_ask_pray_drop: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1973-1980
  _handle_ask_pray_real_name: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1957-1971
  _handle_baiye_battle_kick_member: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4833-4839
  _handle_call_object_func: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5121-5160
  _handle_change_remark: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1836-1849
  _handle_change_second_password: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4777-4779
  _handle_character_interest_skill_unlock: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4750-4755
  _handle_chat_clear_msg: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2317-2338
  _handle_chat_link_stuff: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1472-1518
  _handle_chat_open_player_float: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1913-1937
  _handle_chat_open_stuff_float: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1939-1955
  _handle_chat_player_delete: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2304-2315
  _handle_chat_send_msg: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2474-2490
  _handle_chat_show_team_history: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2340-2341
  _handle_clear_dungeon_sp_skill_protect: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5632-5639
  _handle_clear_team_tank: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2048-2065
  _handle_club_info_back: function(arg1, arg2, arg3, arg4)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1357-1414
  _handle_club_room_invite_friend_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3038-3066
  _handle_common_share_navigate: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2525-2540
  _handle_dance_duel_share_goto: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3281-3304
  _handle_debate_battle: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2574-2600
  _handle_debate_battle_spectate: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2622-2634
  _handle_debate_eval_share_goto: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3341-3355
  _handle_del_friend: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2196-2205
  _handle_del_friend_confirm: function(arg1, arg2)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2207-2217
  _handle_delete_black: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1458-1460
  _handle_delete_enemy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1450-1452
  _handle_delete_master: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1990-1996
  _handle_delete_second_password: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4781-4783
  _handle_delete_student: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1982-1988
  _handle_dispatch_str_event: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5106-5119
  _handle_edit_building_area: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2653-2657
  _handle_employee_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3219-3234
  _handle_employer_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3200-3217
  _handle_enter_blueprint_space: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1177-1180
  _handle_expedition_team_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1170-1175
  _handle_fast_chat: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1520-1522
  _handle_focus_nearest_judian: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5100-5104
  _handle_gang_blueprint_build_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1191-1195
  _handle_gang_blueprint_design_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1187-1189
  _handle_gang_ui: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2659-2665
  _handle_go_explore: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2647-2651
  _handle_goto_social_recommend: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4866-4870
  _handle_goto_url: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4808-4826
  _handle_goto_webview_url: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4828-4831
  _handle_group_change_name: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2295-2302
  _handle_group_change_owner: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2360-2367
  _handle_group_create: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2219-2227
  _handle_group_dismiss: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2243-2268
  _handle_group_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2270-2277
  _handle_group_invite_person: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2279-2286
  _handle_group_kick_person: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2369-2374
  _handle_group_leave: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2376-2379
  _handle_group_manage: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2229-2241
  _handle_group_photo_share_detail: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5575-5588
  _handle_group_photo_share_update: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5590-5600
  _handle_group_tip_off: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2381-2408
  _handle_guise_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1851-1864
  _handle_gymnastics_share_goto: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3236-3260
  _handle_hire_homeland_npc: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2130-2144
  _handle_identity_pvp_observe: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1099-1104
  _handle_identity_pvp_single_attend: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1087-1097
  _handle_identity_pvp_team_attend: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1106-1117
  _handle_industry_accept_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1028-1037
  _handle_industry_open_detail: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1000-1005
  _handle_industry_open_main: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1007-1012
  _handle_industry_open_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1021-1026
  _handle_industry_remove_land: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1014-1019
  _handle_interact_chat_npc: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2091-2097
  _handle_interact_gang_boite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3141-3156
  _handle_interact_gang_pitch_pot: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3158-3171
  _handle_interact_homeland_npc: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2107-2128
  _handle_interact_with_employee: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2949-2962
  _handle_jieyi_change_leader: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4603-4606
  _handle_jieyi_confirm_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4504-4506
  _handle_jieyi_confirm_request: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4547-4549
  _handle_jieyi_force_quit: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4608-4611
  _handle_jieyi_notify: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4551-4553
  _handle_jieyi_open_chat: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4555-4557
  _handle_jieyuan_recruit_friend_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2004-2007
  _handle_join_donate_shop: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1182-1185
  _handle_join_group: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1535-1551
  _handle_look_person_info: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2343-2358
  _handle_make_black: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1454-1456
  _handle_make_enemy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1446-1448
  _handle_mentor_recruit_friend_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1998-2002
  _handle_move_event: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2693-2718
  _handle_multi_dance_share_goto: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3262-3279
  _handle_news_share_detail: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4508-4521
  _handle_npc_interact_intimacy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1119-1126
  _handle_open_activity_gift_send_page: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4921-4983
  _handle_open_bag_and_focus_stuff: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4872-4878
  _handle_open_bomb_qte: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1039-1056
  _handle_open_children_card_send_page: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5029-5068
  _handle_open_danmu: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1866-1877
  _handle_open_gacha_season: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2997-3006
  _handle_open_gameplay_task: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3173-3186
  _handle_open_gift_send_page: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4985-5027
  _handle_open_group_invite_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2288-2293
  _handle_open_identity_main_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2513-2523
  _handle_open_jianwen_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3371-3374
  _handle_open_main_store: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2987-2995
  _handle_open_newspaper_by_id: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4523-4536
  _handle_open_player_float: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1462-1470
  _handle_open_player_head: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1738-1742
  _handle_open_player_info: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1733-1736
  _handle_open_points_store: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2964-2985
  _handle_open_rank_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4855-4864
  _handle_open_sign_page_by_group: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2492-2495
  _handle_open_task_envelope_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2503-2506
  _handle_open_xiaji_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3376-3383
  _handle_p_b_on_board: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3133-3139
  _handle_painting_boat_building_co: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3068-3082
  _handle_painting_boat_free_party: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3084-3098
  _handle_painting_boat_free_party_card: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3100-3108
  _handle_painting_boat_free_party_pop_win: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3120-3131
  _handle_painting_boat_free_party_transfer: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4650-4656
  _handle_painting_boat_try_goto_free_party: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3110-3118
  _handle_private_hud_chat: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1524-1533
  _handle_recall_tutor_accept_share_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4658-4702
  _handle_remove_chat_npc: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2075-2081
  _handle_report_annoy_player: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1553-1564
  _handle_report_player: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1749-1765
  _handle_report_player_coop: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1767-1787
  _handle_report_player_firework: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1789-1808
  _handle_report_player_sign: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1810-1815
  _handle_report_player_sign_get_player_model_callback: function(arg1, arg2, arg3, arg4)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1817-1834
  _handle_reset_chat_npc: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2067-2073
  _handle_ride_backseat_rideoff: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2470-2472
  _handle_ride_invite_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2453-2460
  _handle_ride_send_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2462-2468
  _handle_room_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1711-1731
  _handle_room_call_member: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1700-1704
  _handle_room_callall: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1695-1698
  _handle_room_return: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1706-1709
  _handle_school_enroll: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2548-2553
  _handle_school_participate: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2555-2560
  _handle_set_chat_top: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2146-2159
  _handle_set_chat_untop: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2161-2164
  _handle_set_dungeon_sp_skill_protect: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5623-5630
  _handle_set_team_tank: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2009-2046
  _handle_setup_industry: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:993-998
  _handle_share_position: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1879-1911
  _handle_share_sprite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4841-4853
  _handle_space_room_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2443-2451
  _handle_space_room_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2410-2417
  _handle_space_room_remove: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2419-2434
  _handle_space_room_remove_team: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2436-2441
  _handle_spring_festival_carnival_task_start: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4757-4769
  _handle_spring_festival_request_order: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4771-4775
  _handle_start_chat_npc_wanfa: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2099-2105
  _handle_stuff_museum_info: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2674-2684
  _handle_stuff_museum_second: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2686-2691
  _handle_team_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1148-1168
  _handle_team_apply_leader: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1620-1622
  _handle_team_apply_list: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1624-1626
  _handle_team_auto_match: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1632-1634
  _handle_team_cancel_auto_match: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1636-1638
  _handle_team_ccmini_change_voice: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1691-1693
  _handle_team_ccmini_listen: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1679-1681
  _handle_team_ccmini_mute: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1683-1685
  _handle_team_ccmini_speak: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1687-1689
  _handle_team_change_leader: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1434-1437
  _handle_team_create: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1425-1427
  _handle_team_follow: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1612-1614
  _handle_team_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1128-1146
  _handle_team_invite_list: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1628-1630
  _handle_team_leave: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1421-1423
  _handle_team_leave_temp: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1616-1618
  _handle_team_make_friend: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1439-1444
  _handle_team_mute_player: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1640-1650
  _handle_team_recall: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1607-1610
  _handle_team_remove: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1429-1432
  _handle_team_unmute_player: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1652-1662
  _handle_tourist_school_ceremony: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2636-2645
  _handle_trace_vending_machine: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3188-3198
  _handle_trigger_start_club_anbao: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3016-3036
  _handle_unlock_post: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3008-3010
  _handle_use_hongbao_stuff: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2182-2194
  _handle_use_post_recover: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3012-3014
  _handle_vending_card_be_asked: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4880-4919
  _handle_visit_npc: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2508-2511
  _handle_waiguan_borrow: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4613-4648
  _handle_waiguan_borrow_request: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4559-4600
  _handle_watch_face_state_changed: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5083-5087
  _handle_wenshi_answer_interact: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3332-3334
  _handle_wenshi_answer_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3336-3339
  _handle_wenshi_multi_ans_share_goto: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3306-3330
  _handle_wulinlu_goto_map: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1744-1747
  _handle_zft_enroll: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2562-2566
  _handle_zft_participate: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2568-2572
  _handler_delete_chat_batch: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1578-1587
  _handler_open_school_select: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2497-2501
  _handler_open_tavern_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2667-2672
  _handler_set_friend_group: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1589-1597
  _handler_team_ccmini_opt: function(arg1, arg2)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1665-1677
  _handler_trace_miao_miao_cat: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4538-4544
  _leave_floatopia: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5229-5231
  _on_entry_open_bag: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1058-1061
  _on_entry_open_baixiao: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1063-1066
  _on_entry_open_building: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1068-1070
  _on_entry_open_jishi: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1072-1075
  _on_entry_open_lunjian: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1077-1080
  _on_entry_open_mail: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1082-1085
  _open_activity_center_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5602-5615
  _open_activity_recall_tutor: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5617-5621
  _open_building_guise_display: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5287-5294
  _open_building_horse_display: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5304-5310
  _open_building_weapon_display: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5296-5302
  _open_homeland_decompose_windows: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5209-5227
  _open_homeland_window_and_focus: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5197-5206
  _open_homeland_windows: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5182-5195
  _open_meteor_shower_comment_add_sidepage: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5247-5257
  _open_one_meteor_shower_comment: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5241-5245
  _real_join_chat_room: function(arg1, arg2)  -- @hexm/client/ui/handlers/goto_event_handler.lua:607-620
  _trace_debate_battle_npc: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2720-2740
  _try_focus_floatopia_bulletin: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5233-5239
  _try_open_meteor_shower_summon_sidepage: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5259-5272
  _use_wenshi_menke_service: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3357-3369
  common_share_navigate_callback: function(arg1, arg2)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2542-2546
  competition_get_team_id: function(arg1)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4704-4713
  ctor: function(arg1, arg2)  -- @hexm/client/ui/handlers/goto_event_handler.lua:17-21
  debate_npc_act: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2602-2610
  destroy_object: function(arg1)  -- @hexm/client/ui/handlers/goto_event_handler.lua:23-30
  generate_url_by_data: function(arg1, arg2)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4785-4806
  handle_battle_sparring_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3939-3943
  handle_battle_sparring_trace: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3945-3954
  handle_battle_sparring_transfer_to: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3956-3958
  handle_boat_game_start: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3775-3789
  handle_bounty_invite_fetch: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3976-3999
  handle_bounty_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4001-4003
  handle_bujianshan_track_agree_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5451-5470
  handle_bujianshan_track_goto_bigmap: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5441-5449
  handle_chat_room_action_ban: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:646-650
  handle_chat_room_action_change_owner: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:670-691
  handle_chat_room_action_close_mic: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:664-668
  handle_chat_room_action_open_mic: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:658-662
  handle_chat_room_action_unban: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:652-656
  handle_chat_room_cancel_silence: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:640-644
  handle_chat_room_enter: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:585-605
  handle_chat_room_invite_mic: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:622-626
  handle_chat_room_open_fudai: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:705-718
  handle_chat_room_rm_player: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:634-638
  handle_chat_room_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:571-583
  handle_chat_room_silence: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:628-632
  handle_club_apply: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1326-1332
  handle_club_appoint_post: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1267-1306
  handle_club_battle_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1339-1355
  handle_club_edit_post: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1248-1265
  handle_club_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1215-1224
  handle_club_kick_member: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1226-1246
  handle_club_room_kick: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1334-1337
  handle_club_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1202-1213
  handle_club_transfer_master: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1308-1324
  handle_coop_film_group_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5373-5397
  handle_coop_game_share_invited: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3677-3699
  handle_coop_group_photo_share_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5312-5333
  handle_coop_hoard_profiteer_send_msg: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3760-3773
  handle_coop_hoard_profiteer_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3712-3758
  handle_dance_duel_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3960-3974
  handle_disease_apply_cure: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4245-4276
  handle_disfavorite_chat_room: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:699-703
  handle_diva_work_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1197-1200
  handle_explore_hunt_use_stuff: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5564-5573
  handle_fashion_friend_deal_auth: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5472-5497
  handle_favorite_chat_room: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:693-697
  handle_flying_dance_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4278-4298
  handle_gather_game_share_invited: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3702-3709
  handle_go_to_enhancement_system: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:866-869
  handle_got_szyy_double_entry: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3566-3584
  handle_goto_check_player_card: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3512-3520
  handle_goto_compound: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2742-2744
  handle_goto_compound_assist: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2746-2748
  handle_goto_compound_handmade: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2750-2765
  handle_goto_create_coop_szyy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3542-3550
  handle_goto_disaster_build_qte_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3630-3632
  handle_goto_exchange_collection: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3522-3539
  handle_goto_friend_favorite_qingyilin: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4372-4377
  handle_goto_gang_build_qte: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2881-2891
  handle_goto_gang_build_qte_invite_click: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2893-2898
  handle_goto_gang_cook_compound: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2869-2879
  handle_goto_gang_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2861-2867
  handle_goto_immediate_dance_thank_admire: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3603-3611
  handle_goto_mentor_npc_when_valid: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4481-4493
  handle_goto_npc_prison_transfer: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3385-3387
  handle_goto_participate_szyy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3552-3556
  handle_goto_play_instrument_thank_admire: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3923-3931
  handle_goto_prison_build_qte_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3393-3395
  handle_goto_prison_build_qte_single: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3389-3391
  handle_goto_prison_material_exchange: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3397-3399
  handle_goto_prison_material_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3401-3403
  handle_goto_prison_reflect_transfer: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3405-3420
  handle_goto_prison_visit: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3422-3439
  handle_goto_qingyilin_friend_login: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4385-4394
  handle_goto_qingyilin_transfer: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4379-4383
  handle_goto_start_immediate_dance: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3598-3601
  handle_goto_start_sumo_pve: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3613-3628
  handle_goto_szyy_follow: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3586-3591
  handle_goto_szyy_leader_start_follow: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3593-3596
  handle_goto_szyy_single_entry: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3558-3564
  handle_goto_zhuoying_trace_clue: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2926-2934
  handle_goto_zhuoying_trace_npc: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2936-2947
  handle_guyun_paper_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3914-3921
  handle_homeland_inspection_end: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2171-2174
  handle_homeland_inspection_show: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2176-2180
  handle_homeland_inspection_start: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2166-2169
  handle_huajuan_club_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:907-910
  handle_huajuan_self_lit_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:912-915
  handle_huanjuan_club_lit_tip: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:917-922
  handle_invite_cloud_music_sync_song: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5499-5527
  handle_invite_private_voice: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:761-796
  handle_locate_monster_by_reward: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3638-3675
  handle_mentor_share_card_goto: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4364-4370
  handle_npc_stuff_received: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3480-3503
  handle_open_achieve: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1416-1419
  handle_open_build_recipe_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3933-3937
  handle_open_chiji_wuxue_skill: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:970-990
  handle_open_compound_win: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4175-4214
  handle_open_horse_sale: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4235-4243
  handle_open_map_and_focus_nearest_evac: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:924-952
  handle_open_map_and_focus_one_evac: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:954-968
  handle_open_mic_opt_in_chat_page: function(arg1, arg2)  -- @hexm/client/ui/handlers/goto_event_handler.lua:821-839
  handle_open_mic_opt_in_chat_page_gameplay: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:813-815
  handle_open_mic_opt_in_chat_page_invitation: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:817-819
  handle_open_mic_opt_in_chat_page_team: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:809-811
  handle_open_other_school_paper: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5529-5540
  handle_open_role_attr_item: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:851-864
  handle_open_team_dungeon_win: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4154-4173
  handle_open_world_view_info_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4310-4333
  handle_open_world_view_kaoju_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4335-4343
  handle_open_wuxue_skill: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:886-905
  handle_open_xiaozujian_send_page: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:841-845
  handle_pvp_room_change_owner: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:751-754
  handle_pvp_room_enter_room: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:744-749
  handle_pvp_room_remove_player: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:756-759
  handle_qiyu_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3463-3478
  handle_qx_join_open_listen_float: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4216-4218
  handle_qx_join_start_need_moeny: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4231-4233
  handle_qx_join_start_no_moeny: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4220-4229
  handle_region_game_pursue_sync: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4495-4503
  handle_report_chat_room: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:720-742
  handle_school_chief_toy_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3884-3889
  handle_school_chief_vote: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3791-3882
  handle_school_paper_invite_msg_accept: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5542-5551
  handle_school_paper_invite_msg_deny: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5553-5562
  handle_school_punish_zuihuayin: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4300-4307
  handle_send_chat_gift: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:798-807
  handle_send_moshandao_hide_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3892-3912
  handle_sign_open_detail: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3634-3636
  handle_space_room_invite_chat: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4396-4408
  handle_space_room_rec_goto_map: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4410-4427
  handle_space_room_rec_goto_quick: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4429-4447
  handle_space_room_rec_goto_quick_guest: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4449-4466
  handle_stacking_try_start: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3454-3457
  handle_task_progress_node_unlocked: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3459-3461
  handle_trade_open_diandang: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4005-4027
  handle_trade_open_jishou_buy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4081-4133
  handle_trade_open_sell: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4029-4055
  handle_trade_open_shop_buy: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4057-4079
  handle_try_change_nickname: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4135-4152
  handle_world_film_group_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5399-5439
  handle_world_group_photo_share_invite: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:5335-5371
  handle_xinfa_uprank_stuff_use: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:871-884
  handler_competition_pve_train: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4742-4744
  handler_competition_team_change_owner: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4720-4725
  handler_competition_team_join_from_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4734-4740
  handler_competition_team_kickout: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4727-4732
  handler_competition_team_leave: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4715-4718
  handler_competition_window: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4746-4748
  handler_goto_parade_audience_enter: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3441-3444
  handler_goto_parade_prisoner_share: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3446-3452
  handler_group_setting_side: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:1566-1576
  handler_help_finish_guild_miwuzhuxie_task: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2900-2908
  handler_multiplayer_event_track_event: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:3505-3510
  handler_open_anim_action_window_force_anim: function(arg1, arg2, arg3)  -- @hexm/client/ui/handlers/goto_event_handler.lua:4469-4479
  on_gang_info_back: function(arg1, arg2, arg3, arg4)  -- @hexm/client/ui/handlers/goto_event_handler.lua:2910-2924
}


-- End of hexm.client.ui.handlers.goto_event_handler