-- ======================================================================
-- Module: hexm.client.entities.local.player_avatar_members.map_marker_plugins.map_plugin_config
-- Source: package.loaded
-- Type: table
-- Order: #7134
-- ======================================================================

-- Module type: table

CLZ_CACHE: <dict>

PLUGIN_CONFIG: instance {
  -- Metatable:
  --   __index: table
  --   __tostring: yes
  2: "disaster_plugin.DisasterPlugin"
  3: "free_marker_plugin.FreeMarkerPlugin"
  5: "task_plugin.TaskPlugin"
  8: "post_house_plugin.PostHousePlugin"
  9: "collection_plugin.CollectionPlugin"
  18: "entrust_notice.EntrustNoticePlugin"
  21: "industry_plugin.IndustryPlugin"
  25: "shop_plugin.ShopPlugin"
  30: "guild_monster_plugin.GuildMonsterPlugin"
  33: "wulin_fengyun_plugin.WulinFengyunPlugin"
  34: "area_item_plugin.AreaItemPlugin"
  36: "entity_track.EntityTrack"
  37: "region_game_judian.RegionGameJuDian"
  40: "school_info_plugin.SchoolInfoPlugin"
  44: "stable_info_plugin.StableInfoPlugin"
  45: "gang_tavern_item_plugin.GangTavernItemPlugin"
  46: "paifang_plugin.PaifangPosPlugin"
  47: "miao_miao_cat_plugin.MiaoMiaoCatPlugin"
  50: "school_plugins.order_plugin_regular.OrderPluginRegular"
  51: "school_plugins.order_plugin_dazuo.OrderPluginDazuo"
  52: "school_plugins.order_plugin_monk.OrderPluginMonk"
  53: "school_plugins.order_plugin_regular.OrderPluginRegular"
  54: "school_plugins.order_plugin_rysx.OrderPluginRYSX"
  57: "listen_wind_plugin.ListenWindPlugin"
  58: "school_ceremony_plugin.SchoolCeremonyPlugin"
  61: "weather_normal_plugin.WeatherNormalPlugin"
  62: "weather_super_plugin.WeatherSuperPlugin"
  63: "school_plugins.order_plugin_jrfq_center.OrderJrfqCenterPlugin"
  64: "school_plugins.order_plugin_jrfq_npc.OrderJrfqNpcPlugin"
  65: "school_plugins.order_plugin_drink.OrderDrinkPlugin"
  69: "tanjing_area_plugin.TanjingAreaPlugin"
  70: "tanjing_label_plugin.TanjingLabelPlugin"
  71: "school_plugins.order_plugin_bomb.OrderBombPlugin"
  72: "tianyake_plugin.TianyakePlugin"
  73: "dock_plugin.DockPlugin"
  76: "consume_wanfa_plugin.ConsumeWanfaPlugin"
  77: "compound_plugin.CompoundPlugin"
  78: "instrument_collection_plugin.InstrumentCollectionPlugin"
  81: "school_guide_plugin.SchoolGuidePlugin"
  84: "miao_miao_store_plugin.MiaoMiaoStorePlugin"
  90: "horse_icon_plugin.HorseIconPlugin"
  91: "school_toushi_plugin.SchoolToushiPlugin"
  92: "sround_entity_plugin.SroundEntityPlugin"
  94: "entity_trace_plugins.chousha_xs.ChoushaXs"
  95: "entity_trace_plugins.shangjin_xs.ShangjinXs"
  96: "gang_dinner_cook_plugin.GangDinnerCookPlugin"
  97: "gang_dinner_waiter_plugin.GangDinerWaiterPlugin"
  99: "gang_drink_marker.GangDrinkPlugin"
  101: "region_game_judian_mask.RegionGameJuDianMask"
  102: "gameplay_entry_plugin.GameplayEntryPlugin"
  105: "plant_collection.PlantCollectionPlugin"
  106: "map_lock_area_plugin.MapLockAreaPlugin"
  108: "gang_build_qte_map_plugin.GangBuildQteMapPlugin"
  111: "narrator_plugin.NarratorPlugin"
  112: "entity_trace_plugins.xuanhu_xs.XuanhuXs"
  113: "ins_entity_marker.InsEntityPlugin"
  114: "fishing_contest_plugin.FishingContestPlugin"
  115: "private_workbench_plugin.PrivateWorkbenchPlugin"
  116: "npc_bag_plugin.NpcBagPlugin"
  117: "pitch_pot_marker.PitchPotPlugin"
  118: "theater_game_plugin.TheaterGamePlugin"
  119: "shadow_play_npc.ShadowPlayNpc"
  120: "multi_guard_plugin.MutliGuardPlugin"
  121: "school_plugins.order_plugin_range_trace.OrderPluginRangeTrace"
  122: "school_plugins.order_plugin_range_trace.OrderPluginRangeTrace"
  123: "school_plugins.order_plugin_range_trace.OrderPluginRangeTrace"
  124: "xuanhu_npc_plugin.XuanhuNpcPlugin"
  125: "debate_npc_plugin.DebateNPCPlugin"
  126: "interact_trace_plugin.InteractTracePlugin"
  128: "pitch_pot_pvp_plugin.PitchPotPVPPlugin"
  129: "police_plugin.PolicePlugin"
  131: "school_entry_event_plugin.SchoolEntryEventPlugin"
  132: "qizhen_trace_plugin.QizhenTracePlugin"
  135: "qizhen_submit_plugin.QizhenSubmitPlugin"
  137: "prison_info_plugin.PrisonInfoPlugin"
  138: "multiplayer_event_plugin.MultiplayerEventPlugin"
  139: "bluff_poker_plugin.BluffPokerPlugin"
  141: "archery_game_plugin.ArcheryGamePlugin"
  142: "world_shefu_plugin.WorldShefuPlugin"
  143: "cave_level_plugin.CaveLevelPlugin"
  144: "escort_game_plugin.EscortHorsePlugin"
  145: "escort_game_plugin.EscortDestinationPlugin"
  146: "escort_game_plugin.EscortBuildPlatformPlugin"
  147: "pve_battle_npc.PveBattleNpc"
  148: "rush_tower_plugin.RushTowerPlugin"
  149: "world_boss_plugin.WorldBossPlugin"
  150: "weaken_world_boss_plugin.WeakenWorldBossPlugin"
  153: "disguise_shop_plugin.DisguiseShopPlugin"
  154: "neigong_marker.NeigongMultiEventMarkerPlugin"
  156: "ins_entity_marker.InsEntityPlugin"
  157: "blue_print_mark_plugin.BluePrintMarkPlugin"
  158: "ins_entity_marker.InsEntityPlugin"
  160: "disaster_merit_pool_plugin.DisasterMeritsPoolPlugin"
  161: "disaster_wish_pool_plugin.DisasterWishPoolPlugin"
  163: "ins_entity_marker.InsEntityPlugin"
  164: "sumo_plugin.SumoPlugin"
  165: "temp_npc_tracing_plugin.TempNpcTracingPlugin"
  168: "hoard_profiteer_plugin.HoardProfiteerPlugin"
  169: "house_rent_plugin.HouseRentPlugin"
  170: "room_judian_plugin.RoomJudianPlugin"
  174: "club_build_area_plugin.ClubBuildAreaPlugin"
  175: "hoard_profiteer_plugin.HoardProfiteerTraderPlugin"
  176: "multi_mwzx_plugin.MultiMWZXxhjsPlugin"
  177: "school_plugins.tq_donation_point_plugin.TqDonationMarkerPlugin"
  178: "ins_entity_marker.InsEntityPlugin"
  179: "painting_boat.PaintingBoatWanfaTrackPlugin"
  180: "painting_boat.DockPlugin"
  181: "painting_boat.VehiclePlugin"
  182: "club_bath_plugin.ClubBathPlugin"
  183: "club_member_plugin.ClubMemberPlugin"
  184: "painting_boat.NavPointPlugin"
  187: "ins_entity_marker.InsEntityPlugin"
  188: "fishing_farm_plugin.FishingFarmPlugin"
  189: "ins_entity_marker.InsEntityPlugin"
  190: "ins_entity_marker.InsEntityPlugin"
  191: "ins_entity_marker.InsEntityPlugin"
  192: "ins_entity_marker.InsEntityPlugin"
  200: "ins_entity_marker.InsEntityMainOnlyPlugin"
  201: "ins_entity_marker.InsEntityMainOnlyPlugin"
  202: "region_sneak_plugin.RegionSneakPlugin"
  203: "ins_entity_marker.InsEntityPlugin"
  204: "ins_entity_marker.InsEntityPlugin"
  205: "photo_daka_plugin.PhotoDakaPlugin"
  206: "ask_for_direction_plugin.AskForDirectionPlugin"
  209: "informer_game_plugin.InformerGamePlugin"
  210: "qizhen_chase_plugin.QizhenChasePlugin"
  211: "painting_boat.DockBuildingPlugin"
  214: "ins_entity_marker.InsEntityPlugin"
  216: "ins_entity_marker.InsEntityPlugin"
  217: "ins_entity_marker.InsEntityPlugin"
  218: "ins_entity_marker.InsEntityMainOnlyPlugin"
  222: "ins_entity_marker.InsEntityMainOnlyPlugin"
  231: "ins_entity_marker.InsEntityMainOnlyPlugin"
  233: "ins_entity_marker.InsEntityPlugin"
  234: "npc_companion_plugin.NpcCompanionPlugin"
  235: "npc_companion_collection_plugin.NpcCompanionCollectionPlugin"
  239: "target_vision_plugin.TargetVisionPlugin"
  241: "club_battle_entity_marker.ClubBattleEntityPlugin"
  242: "club_battle_entity_marker.ClubBattleEntityPlugin"
  243: "club_battle_entity_marker.ClubBattleEntityPlugin"
  244: "club_battle_entity_marker.ClubBattleEntityPlugin"
  245: "club_battle_entity_marker.ClubBattleEntityPlugin"
  246: "club_battle_entity_marker.ClubBattleEntityPlugin"
  248: "goose_life_price_plugin.GooseLifePricePlugin"
  249: "tianquan_running_plugin.TianQuanRunningPlugin"
  250: "tianquan_running_plugin.TianQuanRunningLeaderPlugin"
  254: "mojin_plugin.MojinPlugin"
  257: "mojin_plugin.MojinPlugin"
  258: "new_year_firework_marker.NewYearFireworkPlugin"
  259: "informer_game_plugin.InformerInterPlugin"
  261: "ins_entity_marker.InsEntityPlugin"
  264: "ins_suogugong_entity_marker.SuogugongEntityMarker"
  265: "ins_suogugong_entity_marker.SuogugongEntityMarker"
  267: "ins_entity_marker.InsEntityPlugin"
  269: "interact_coop_gather_plugin.InteractCoopGatherPlugin"
  270: "qizhen_suogugong_submit_plugin.QizhenSuogugongSubmitPlugin"
  272: "prison_info_plugin.PrsionParadePlugin"
  275: "club_battle_entity_marker.ClubBattleEntityPlugin"
  276: "ins_entity_marker.InsEntityMainOnlyPlugin"
  277: "granny_race_plugin.GrannyRaceStartPlugin"
  278: "granny_race_plugin.GrannyRaceEndPlugin"
}

_gen_plugin_clz: function(arg1)  -- @hexm/client/entities/local/player_avatar_members/map_marker_plugins/map_plugin_config.lua:208-225

get_plugin_clz: function(arg1)  -- @hexm/client/entities/local/player_avatar_members/map_marker_plugins/map_plugin_config.lua:195-206

preload_all_plugin_clzs: function()  -- @hexm/client/entities/local/player_avatar_members/map_marker_plugins/map_plugin_config.lua:227-231


-- End of hexm.client.entities.local.player_avatar_members.map_marker_plugins.map_plugin_config