-- ======================================================================
-- Module: hexm.client.consts.collision_consts
-- Source: package.loaded
-- Type: table
-- Order: #2369
-- ======================================================================

-- Module type: table

CHECK_CAN_DESTRUCT: function()  -- @hexm/client/consts/collision_consts.lua:108-110

COLLISION_TYPE_AIAVT: 78

COLLISION_TYPE_AIRWALL: 3

COLLISION_TYPE_AIRWALL_EXCLUDE_PLAYER: 45

COLLISION_TYPE_ALL: 0

COLLISION_TYPE_ARROW: 34

COLLISION_TYPE_ARROW_AIM: 51

COLLISION_TYPE_ARROW_AIM_PHY: 70

COLLISION_TYPE_BATTLE_SPARRING: 84

COLLISION_TYPE_BOSS: 24

COLLISION_TYPE_CAMERA_COLLIDER: 37

COLLISION_TYPE_CHECKED: 4

COLLISION_TYPE_COMBAT_MONSTER: 20

COLLISION_TYPE_DESTRUCT_DISAPPEAR: 31

COLLISION_TYPE_DESTRUCT_MAINPLAYER: 60

COLLISION_TYPE_DESTRUCT_MOVE: 30

COLLISION_TYPE_DESTRUCT_SELF: 35

COLLISION_TYPE_DETECT_DANDAO: 69

COLLISION_TYPE_ENV_LAND: 19

COLLISION_TYPE_FALL_HURT: 14

COLLISION_TYPE_FLOATING_OBJECT: 29

COLLISION_TYPE_FLOWER: 92

COLLISION_TYPE_FLY_LAND: 15

COLLISION_TYPE_FULL_CAMERA_COLLIDER: 41

COLLISION_TYPE_GHOST_ENTITY: 95

COLLISION_TYPE_INDOOR: 32

COLLISION_TYPE_MARSH: 42

COLLISION_TYPE_MONSTER: 23

COLLISION_TYPE_NOTHING: 1

COLLISION_TYPE_NPC_MF: 38

COLLISION_TYPE_OBSTACLE: 39

COLLISION_TYPE_OTHER_PLAYER: 72

COLLISION_TYPE_PHYX_OCCLUDER: 47

COLLISION_TYPE_PLAYER: 22

COLLISION_TYPE_PLAYER_SPECIAL: 21

COLLISION_TYPE_QUERY_ACTOR: 26

COLLISION_TYPE_QUERY_AIRWALL: 64

COLLISION_TYPE_QUERY_INDOOR: 33

COLLISION_TYPE_QUERY_PLAYER: 16

COLLISION_TYPE_QUERY_STATIC: 25

COLLISION_TYPE_QUERY_SUNSHINE: 18

COLLISION_TYPE_QUERY_UDG: 55

COLLISION_TYPE_QUERY_WATER: 13

COLLISION_TYPE_QUERY_WATER_GROUND: 89

COLLISION_TYPE_QUERY_YUANLING: 66

COLLISION_TYPE_RADIATION: 61

COLLISION_TYPE_RIDE_NPC_COLLIDER: 45

COLLISION_TYPE_SCRIPT_RAYCAST: 10

COLLISION_TYPE_SNOW_SURFACE: 54

COLLISION_TYPE_STATIC: 2

COLLISION_TYPE_STATIC_EXCEPT_NPC: 9

COLLISION_TYPE_STATIC_WITHOUT_CAMERA_COLLIDER: 40

COLLISION_TYPE_TREE_BODY: 17

COLLISION_TYPE_UNDERGROUND: 53

COLLISION_TYPE_WATER: 27

COLLISION_TYPE_WIND_WALL: 100

COLLISION_TYPE_WITH_ENVIRONMENT_SENSOR: 28

COLLISION_TYPE_YUANLING: 6

COLLISION_TYPE_ZUOQI: 36

DESTRUCT_MAX: 5

DESTRUCT_NUM: 0

FILTER_FLAG_BUILDING: 8

FILTER_FLAG_CAMERA: 5

FILTER_FLAG_CLIMB: 7

FILTER_FLAG_INTERACT: 6

FILTER_FLAG_PLATFORM: 4

FILTER_FLAG_PUSH: 3

FILTER_FLAG_SLIDE: 2

FILTER_FLAG_STAND: 1

FILTER_FLAG_STEP: 0

FILTER_TYPE_IGNORE: 1

FILTER_TYPE_NONE: 0

FILTER_TYPE_ONLY: 2

MAX_COLLISION_TYPE: 64

QUERY_ALL_ENTITY: 3

QUERY_ALL_ENTITY_EXCEPT_MAIN_PLAYER: 9

QUERY_BOSS: 2

QUERY_BUILD: 7

QUERY_DYNAMIC_ENTITY: 4

QUERY_FoGuang_Light_OBSTACLE: 12

QUERY_LOCK_TARGET_OBSTACLE: 11

QUERY_MAIN_PLAYER: 1

QUERY_MANUALS: 50

QUERY_RADIATION: 5

QUERY_STATIC: 8

QUERY_Sunshine: 13

QUERY_WATER_AND_MARSH: 6


-- End of hexm.client.consts.collision_consts