-- ======================================================================
-- Module: hexm.client.consts.homeland_need_freeze_window_names
-- Source: package.loaded
-- Type: table
-- Order: #5931
-- ======================================================================

-- Module type: table

ALL_HOMELAND_WINDOWS: instance {
  -- Metatable:
  --   __index: table
  --   __tostring: yes
  1: "MusicBoxSongListPage"
  2: "HomelandFormulaWindow"
  3: "HomelandChapterCommitSidePage"
  4: "HomelandChapterWindow"
  5: "HomelandGenGoldMapSidePage"
  6: "HomelandGenGoldOrderSidePage"
  7: "HomelandGenGoldOrderWindow"
  8: "HomelandGenGoldRecycleWindow"
  9: "HomelandMateStateWindow"
  10: "BanquetPrepareSp"
  11: "BanquetPrepareWindow"
  12: "BanquetResultSp"
  13: "HomelandOneDayMasterMainWindow"
  14: "HomelandOnedayMasterEventSidePage"
  15: "HomelandPropWindow"
  16: "NativeProductChooseNativeSidePage"
  17: "NativeProductLineManageSidePage"
  18: "HomelandNativeProductMainPage"
  19: "HomelandIndustryActiveMarkerSidePage"
  20: "HomelandIndustryAutoPutSidePage"
  21: "HomelandIndustryMapSummarySidePage"
  22: "HomelandIndustryNotConstructedSidePage"
  23: "HomelandIndustryOverlapSelectSidePage"
  24: "HomelandIndustryRepairSidePage"
  25: "IndustryTableFoodSidePage"
  26: "IndustryUpgradeSidePage"
  27: "ProductionManageSidePage"
  28: "ProductionOperationSidePage"
  29: "ProductionRecordSidePage"
  30: "ProductionSellFoodSidePage"
  31: "ProductionSpeedUpSidePage"
  32: "HomelandBagWindow"
  33: "HomelandIndustryMainPage"
  34: "HomelandUpgradeWindow"
  35: "HomelandAllHouseSidePage"
  36: "HomelandLivingHouseEditSidePage"
  37: "HomelandLivingInviteSelectHouseSidePage"
  38: "HomelandLivingInviteSidePage"
  39: "HomelandMyHouseSidePage"
  40: "HomelandMateAgreementWindow"
  41: "HomelandDivorceDivisionSidePage"
  42: "HomelandMateAssetRecycleSidePage"
  43: "HomelandMateAssetSidePage"
  44: "HomelandMateInviteSidePage"
  45: "HomelandMateMembersSidePage"
  46: "HomelandPermissionSelectSidePage"
  47: "HomelandPermissionSidePage"
  48: "HomelandEventDetailsWindow"
  49: "HomelandEventMiwenDetailsWindow"
  50: "HomelandEventXinjianDetailsWindow"
  51: "HomelandNpcTravelRewardWindow"
  52: "HomelandNPCDetailSidePage"
  53: "HomelandNPCDiarySidePage"
  54: "HomelandNPCDiseaseSidePage"
  55: "HomelandNPCDispatchInfoSidePage"
  56: "HomelandNPCDispatchSidePage"
  57: "HomelandNPCDispatchWindow"
  58: "HomelandNPCEmploymentWindow"
  59: "HomelandNPCFloatWindow"
  60: "HomelandNPCGetQishuPopWindow"
  61: "HomelandNPCHiredTip"
  62: "HomelandNPCListSidePage"
  63: "HomelandNPCQishuInfoSidePage"
  64: "HomelandNPCRecruitListSidePage"
  65: "HomelandNPCRecruitProgressSidePage"
  66: "HomelandNPCRenameSidePage"
  67: "HomelandNPCSkillInfoSidePage"
  68: "HomelandNPCSkillUpgradeSidePage"
  69: "HomelandNPCTeachResultSidePage"
  70: "HomelandNPCTeachStartSidePage"
  71: "HomelandNPCTrainWindow"
  72: "HomelandNpcTravelJiesuanWindow"
  73: "HomelandNPCSelectItemWindow"
  74: "HomelandNPCTravelSidePage"
  75: "HomelandNPCTravelingSidePage"
  76: "HomelandNPCUnknownSidePage"
  77: "HomelandNPCYunYouMainWindow"
  78: "FarmlandBuildingFastBuildWindow"
  79: "FarmlandHostingSidepage"
  80: "FarmlandPlantResourceSidepage"
  81: "FarmlandPlantWindow"
  82: "FarmlandQiShuSidepage"
  83: "FarmlandSceneTipWindow"
  84: "HomelandScoreStoreFilterSidePage"
  85: "HomelandEventSidePage"
  86: "HomelandMainWindow"
  87: "HomelandLevelWindow"
}


-- End of hexm.client.consts.homeland_need_freeze_window_names