-- ======================================================================
-- Module: hexm.client.consts.photo_setting_config
-- Source: package.loaded
-- Type: table
-- Order: #338
-- ======================================================================

-- Module type: table

CLAMP_VALUE2PERCENT: instance {
  -- Metatable:
  --   __index: table
  --   __tostring: yes
  1: 23
  2: 10013
  3: 10005
  4: 8
  5: 3
  6: 17
  7: 21
  8: 16
  9: 4
  10: 19
}

PHOTO_SETTING_ACTION: 5

PHOTO_SETTING_APERTURE: 28

PHOTO_SETTING_CAMERA_ROLL: 27

PHOTO_SETTING_COLOR_H: 19

PHOTO_SETTING_COLOR_S: 18

PHOTO_SETTING_CONTRAST: 4

PHOTO_SETTING_DESIGN_DATA: 13

PHOTO_SETTING_DOF_DISTANCE: 10

PHOTO_SETTING_DOF_RANGE: 11

PHOTO_SETTING_EXPOSURE: 3

PHOTO_SETTING_FILTER: 20

PHOTO_SETTING_FILTER_INTENSITY: 23

PHOTO_SETTING_ITEM_IMAGE: 5

PHOTO_SETTING_ITEM_NONE: 0

PHOTO_SETTING_ITEM_SELECT_ANIM: 3

PHOTO_SETTING_ITEM_SELECT_ICON: 2

PHOTO_SETTING_ITEM_SELECT_TEXT: 1

PHOTO_SETTING_ITEM_SLIDER: 4

PHOTO_SETTING_ITEM_SWITCH: 7

PHOTO_SETTING_ITEM_TEMPLATE: 6

PHOTO_SETTING_LIGHT_OVER_INTENSITY: 16

PHOTO_SETTING_LIGHT_OVER_THRESHOLD: 21

PHOTO_SETTING_LOGO: 15

PHOTO_SETTING_LOOK_AT: 12

PHOTO_SETTING_MODEL_SCALE: 29

PHOTO_SETTING_NINE_LINE: 26

PHOTO_SETTING_POINT_LIGHT: 25

PHOTO_SETTING_SCREEN_SCALE: 14

PHOTO_SETTING_SIMPLE_ACTION: 10002

PHOTO_SETTING_SIMPLE_ACTION_MULTI: 10016

PHOTO_SETTING_SIMPLE_ACTION_PROGRESS: 10003

PHOTO_SETTING_SIMPLE_APERTURE: 10009

PHOTO_SETTING_SIMPLE_EMOTION: 10017

PHOTO_SETTING_SIMPLE_FILTER: 10010

PHOTO_SETTING_SIMPLE_FILTER_INTENSITY: 10013

PHOTO_SETTING_SIMPLE_FOCAL_LENGTH: 10008

PHOTO_SETTING_SIMPLE_LOOKAT: 10007

PHOTO_SETTING_SIMPLE_MODEL_SCALE: 10018

PHOTO_SETTING_SIMPLE_POINT_LIGHT_CUS: 10012

PHOTO_SETTING_SIMPLE_POINT_LIGHT_DIR: 10004

PHOTO_SETTING_SIMPLE_POINT_LIGHT_INTENSITY: 10005

PHOTO_SETTING_SIMPLE_POSE: 10011

PHOTO_SETTING_SIMPLE_TEMPLATE: 10001

PHOTO_SETTING_SIMPLE_TEMPLATE_COLLECTION: 10014

PHOTO_SETTING_SIMPLE_TEMPLATE_PRESET: 10015

PHOTO_SETTING_SIMPLE_VISIBLE: 10006

PHOTO_SETTING_TEMPLATE: 24

PHOTO_SETTING_TIME: 7

PHOTO_SETTING_VIGNETTE: 17

PHOTO_SETTING_VISIBLE: 1

PHOTO_SETTING_VISION: 2

PHOTO_SETTING_WATCH_FACE_LIGHT: 30

PHOTO_SETTING_WEATHER: 6

PHOTO_SETTING_WIND_FORCE: 8

PHOTO_SETTING_WIND_YAW: 9

PHOTO_SIMPLE_WATCH_FACE_LIGHT: 10019

clamp_value_to_percent: function(arg1, arg2, arg3)  -- @hexm/client/consts/photo_setting_config.lua:174-185

format_show_setting_value: function(arg1, arg2)  -- @hexm/client/consts/photo_setting_config.lua:148-172

get_setting_btn_controller_clz: function(arg1)  -- @hexm/client/consts/photo_setting_config.lua:107-145

get_setting_btn_view_clz: function(arg1)  -- @hexm/client/consts/photo_setting_config.lua:91-105


-- End of hexm.client.consts.photo_setting_config