-- ======================================================================
-- Module: hexm.client.entities.local.player_avatar_members.states.gameplay_state.state_gameplay_config
-- Source: package.loaded
-- Type: table
-- Order: #6754
-- ======================================================================

-- Module type: table

game_play_state_map: instance {
  -- Metatable:
  --   __index: table
  --   __tostring: yes
  bluff_poker: "state_gameplay_bluff_poker.StateBluffPoker"
  cook_qte: "state_gameplay_cook_qte.StateCookQte"
  debate_battle: "gameplay_debate_battle.state_debate_battle.StateWanfaDebateBattle"
  dice_game: "state_gameplay_dice_game.StateDiceGame"
  die_die_le: "state_gameplay_ddl.StateGameplayDDL"
  drink_pitch_pot: "state_gameplay_drink_pitch_pot.StateDrinkPitchPot"
  drink_qte: "state_gameplay_drink_qte.StateDrinkQte"
  gameplay_anim_action: "gameplay_anim_action.state_gameplay_anim_action.StateGameAnimAction"
  gameplay_baiye_truck: "gameplay_baiye_truck.state_gameplay_baiye_truck.StateGamePlayBaiyeTruck"
  gameplay_baoye_battle_qte: "gameplay_baiye_battle_qte.state_gameplay_baiye_battle_qte.StateGamePlayBaiyeB..."
  gameplay_battle_spar: "state_gameplay_battle_spar.StateBattleSpar"
  gameplay_blind: "gameplay_blind.state_gameplay_blind.StateGamePlayBlind"
  gameplay_build_qte: "gameplay_build_qte.state_gameplay_build_qte.StateBuildQte"
  gameplay_clock: "gameplay_clock.state_gameplay_clock.StateGamePlayClock"
  gameplay_club_auto_build_acc: "gameplay_club_auto_build_acc.state_club_auto_build_acc.StateClubAutoBuildAcc"
  gameplay_club_massage: "state_gameplay_club_massage.StateClubMassage"
  gameplay_club_room: "gameplay_club_room.state_gameplay_club_room.StateClubRoom"
  gameplay_color_mix: "gameplay_color_mix.state_color_mixing.StateColorMixing"
  gameplay_crane: "state_gameplay_crane.StateGamePlayCrane"
  gameplay_cuju: "gameplay_cuju.state_gameplay_cuju.StateGamePlayCuju"
  gameplay_dance_duel_play: "gameplay_dance_duel.state_gameplay_dance_duel_play.StateGamePlayDanceDuelPlay"
  gameplay_dance_duel_watch: "gameplay_dance_duel.state_gameplay_dance_duel_watch.StateGamePlayDanceDuelWatch"
  gameplay_disease: "gameplay_disease.state_gameplay_disease.StateDisease"
  gameplay_doudizhu: "gameplay_table_game.state_gameplay_doudizhu.StateGamePlayDoudizhu"
  gameplay_dung_truck: "gameplay_dung_truck.state_gameplay_dung_truck.StateGamePlayDungTruck"
  gameplay_feed_fish: "state_feed_fish.StateFeedFish"
  gameplay_feiying_cike: "gameplay_feiying_cike.state_gameplay_feiying_cike.StateGamePlayFeiyingCike"
  gameplay_fishing: "gameplay_fishing.state_gameplay_fishing.StateGamePlayFishing"
  gameplay_flame_turret: "gameplay_flame_turret.state_gameplay_flame_turret.StateGamePlayFlameTurret"
  gameplay_flame_turret_bullet: "gameplay_flame_turret_bullet.state_gameplay_flame_turret_bullet.StateGamePlay..."
  gameplay_game_level: "state_gameplay_game_level.StateGamePlayGameLevel"
  gameplay_guandan: "gameplay_table_game.state_gameplay_guandan.StateGamePlayGuandan"
  gameplay_guhuo: "state_gameplay_guhuo.StateGamePlayGuHuo"
  gameplay_gundam_control: "gameplay_gundam_control.state_gameplay_gundam_control.StateGundamControl"
  gameplay_hand_gear: "state_gameplay_hand_gear.StateGamePlayHandGear"
  gameplay_hold_on_carriage: "gameplay_hold_on_carriage.state_gameplay_hold_on_carriage.StateGamePlayHoldOn..."
  gameplay_homeland_npc_teach: "gameplay_homeland_npc_teach.state_gameplay_homeland_npc_teach.StateGameplayHo..."
  gameplay_inference_clue: "gameplay_inference_clue.state_inference_clue.StateGameplayInference"
  gameplay_instrument: "gameplay_instrument.state_gameplay_instrument.StateGamePlayInstrument"
  gameplay_jieyuan_answer: "gameplay_jieyuan_answer.state_gameplay_jieyuan_answer.StateWanfaJieyuanAnswer"
  gameplay_lion_tomb_search: "state_gameplay_liontomb_search.StateGameLionTombSearch"
  gameplay_multi_dance_play: "gameplay_multi_dance.state_gameplay_multi_dance_play.StateGamePlayMultiDancePlay"
  gameplay_multi_dance_watch: "gameplay_multi_dance.state_gameplay_multi_dance_watch.StateGamePlayMultiDance..."
  gameplay_play_fireworks: "state_gameplay_play_fireworks.StateGamePlayPlayFireworks"
  gameplay_prison_parade: "state_gameplay_parade.StateGamePlayParade"
  gameplay_qingchuan_switch: "gameplay_qinchuan.state_gameplay_qinchuan_switch.StateGameplayQinchuanSwitch"
  gameplay_qixi_qte: "state_gameplay_qixi_qte.StateGameplayQixiQte"
  gameplay_quxiecao: "gameplay_quxiecao.state_gameplay_quxiecao.StateGamePlayQuexiecao"
  gameplay_quxiecao_gopher: "gameplay_quxiecao.state_gameplay_quxiecao_gopher.StateGamePlayQuxiecaoGopher"
  gameplay_quxiecao_rhythm: "gameplay_quxiecao.state_gameplay_quxiecao_rhythm.StateGamePlayQuxiecaoRhythm"
  gameplay_rhythm_game: "gameplay_rhythm_game.state_gameplay_rhythm_game.StateGamePlayRhythmGame"
  gameplay_roller_coaster: "gameplay_roller_coaster.state_gameplay_roller_coaster.StateGameplayRollerCoaster"
  gameplay_ronglu_ladder: "gameplay_ronglu_ladder.state_gameplay_ronglu_ladder.StateGamePlayRongluLadder"
  gameplay_rotate_entity: "gameplay_rotate_entity.state_gameplay_rotate_entity.StateGamePlayRotateEntity"
  gameplay_scouting: "gameplay_scouting.state_gameplay_scouting.StateGameplayScouting"
  gameplay_shefu: "gameplay_shefu.state_gameplay_shefu.StateGamePlayShefu"
  gameplay_shrink_bone_turret: "gameplay_flame_turret.state_gameplay_turret_target_shooting.StateGamePlayTurr..."
  gameplay_simple_sitdown: "gameplay_simple_sitdown.state_gameplay_simple_sitdown.StateGamePlaySimpleSitdown"
  gameplay_stacking: "state_gameplay_stacking.StateGameplayStacking"
  gameplay_stone_skipping: "gameplay_stone_skipping.state_stone_skipping.StateStoneSkipping"
  gameplay_sumo: "gameplay_sumo.state_gameplay_sumo.StateGamePlaySumo"
  gameplay_swing: "state_gameplay_swing.StateSwing"
  gameplay_telekinesis_climb: "gameplay_telekinesis_climb.state_gameplay_telekinesis_climb.StateGameplayTele..."
  gameplay_tipsy: "state_gameplay_tipsy.StateGamePlayTipsy"
  gameplay_tjz: "state_gameplay_tjz.StateGamePlayTJZ"
  gameplay_touch_animal: "gameplay_touch_animal.state_touch_animal.StateTouchAnimal"
  gameplay_touch_cat: "state_touch_cat.StateTouchCat"
  gameplay_toushi_qte: "gameplay_toushi_qte.state_gameplay_toushi_qte.StateToushiQte"
  gameplay_transform_child_attach_animal: "gameplay_transform_child.state_gameplay_transform_child_attach_animal.StateTr..."
  gameplay_turret_baiye: "gameplay_turret_baiye.state_gameplay_turret_baiye.StateGamePlayTurretBaiye"
  gameplay_turret_baiye_fly: "gameplay_turret_baiye.state_gameplay_turret_baiye_fly.StateGamePlayTurretBaiy..."
  gameplay_water_turret: "gameplay_water_turret.state_water_turret.StateWaterTurret"
  gameplay_zuihuayin_dance: "gameplay_zuihuayin_dance.state_gameplay_dance.StateGamePlayDance"
  hospital_therapy: "gameplay_hospital_therapy.state_hospital_therapy.StateHospitalTherapy"
  hupai: "state_gameplay_hupai.StateGamePlayHupai"
  mahjong: "state_gameplay_mahjong.StateGamePlayMahjong"
  ride_anim_action: "state_gameplay_ride_anim_action.StateRideAnimAction"
  ride_dance: "state_gameplay_ride_dance.StateGamePlayRideDance"
  ride_dance_leader: "state_gameplay_ride_dance_leader.StateRideDanceLeader"
  ride_wolf_follow: "state_gameplay_ride_wolf.StateGamePlayRideWolfFollow"
  take_carriage: "state_gameplay_carriage.StateCarriage"
  wenshi_multi_answer: "gameplay_wenshi_multi_answer.state_wenshi_multi_answer.StateWanfaWenshiMultiA..."
  zaotang_lay: "gameplay_zaotang.state_gameplay_zaotang_lay.StateZaotangLay"
  zaotang_massage: "gameplay_zaotang.state_gameplay_zaotang_massage.StateZaotangMassage"
  zaotang_pool: "gameplay_zaotang.state_gameplay_zaotang_pool.StateZaotangPool"
}


-- End of hexm.client.entities.local.player_avatar_members.states.gameplay_state.state_gameplay_config